using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.RegularExpressions;
using CircuitRF.Ui.Diagnostics;
using CircuitRF.Ui.Schematic;
using CircuitRF.Ui.Theming;
using Xunit;

namespace CircuitRF.Ui.Tests;

/// <summary>
/// Gates for the User-Docs Factory (docs/sonnet-briefs/brief-docs-factory-infrastructure.md §10).
///
/// <para>These assert over the GENERATED ARTEFACTS in <c>docs/user/</c>, not over a live capture.
/// That is deliberate and it is not a weaker test: this project's <c>Ui.Tests</c> deliberately
/// touches no Avalonia runtime API, and standing up a drawing-capable headless platform inside a
/// 5,000-test suite to re-render every figure would trade a 27-second gate for a much longer and
/// much more fragile one. The generator itself already fails hard at capture time on an empty
/// figure, a dropped paint, an unopened popup, an unknown placeholder and an unresolvable
/// cross-link; what these tests add is that nobody can hand-edit or delete the result and have it
/// go unnoticed, and that the catalog and the anchor contract stay in step with the code.</para>
/// </summary>
public class DocsFactoryTests
{
    private static string RepoRoot([CallerFilePath] string here = "")
    {
        var dir = Path.GetDirectoryName(here);
        while (dir is not null && !File.Exists(Path.Combine(dir, "CLAUDE.md")))
            dir = Path.GetDirectoryName(dir);
        Assert.True(dir is not null, "Could not locate the repo root (no CLAUDE.md walking up from this test file).");
        return dir!;
    }

    private static string DocsRoot() => Path.Combine(RepoRoot(), "docs", "user");
    private static string Figures()  => Path.Combine(DocsRoot(), "assets", "figures");
    private static string Symbols()  => Path.Combine(DocsRoot(), "assets", "symbols");

    private static IEnumerable<string> AllSvgs()
        => Directory.EnumerateFiles(DocsRoot(), "*.svg", SearchOption.AllDirectories);

    private static IEnumerable<string> AllPages()
        => Directory.EnumerateFiles(DocsRoot(), "*.html", SearchOption.AllDirectories);

    /// <summary>
    /// <b>No shipped figure may carry a trailing separator on a per-glyph <c>x</c>/<c>y</c> list.</b>
    ///
    /// <para>Owner-reported, 2026-08-21: figure text "missing or else really small" in Firefox on
    /// Ubuntu, while macOS and Windows were perfect. Skia's SVG device writes
    /// <c>x="0, 8.11, ..., 87.37, "</c> — an SVG <c>list-of-coordinates</c> may not end in a
    /// separator, Gecko applies strict error handling and drops the whole attribute, and every run is
    /// then drawn at the element origin a line above its baseline, where the control's clip removes
    /// all but a sliver of each glyph. Blink and WebKit accept it, so the two platforms whose default
    /// browsers are Edge and Safari looked fine; it reproduces in Firefox on every platform.
    /// <c>SvgFontNormalizer.TrimCoordinateLists</c> is the repair.</para>
    ///
    /// <para>This gate is over the ARTEFACTS, not the normaliser (which has its own unit tests),
    /// because the failure that actually reaches a reader is a figure regenerated by an older build
    /// and committed — the unit tests cannot see that, and 170 files renders it invisible by hand.</para>
    /// </summary>
    [Fact]
    public void NoShippedFigureCarriesATrailingSeparatorInAPositionList()
    {
        var rx      = new Regex(@"\s(?:x|y)\s*=\s*""[^""]*[,\s]""");
        var offenders = new List<string>();

        foreach (var path in AllSvgs().Concat(AllPages()))
            if (rx.IsMatch(File.ReadAllText(path)))
                offenders.Add(Path.GetFileName(path));

        Assert.True(offenders.Count == 0,
            "These generated documents still carry Skia's trailing separator on a per-glyph x/y list, "
          + "so their text renders unreadably in Firefox — regenerate with "
          + "`dotnet run --project tools/DocGen -- --out docs/user`: "
          + string.Join(", ", offenders.Take(12)) + (offenders.Count > 12 ? $" (+{offenders.Count - 12} more)" : ""));
    }

    // ── §10.1 — every catalog figure renders, in both variants ────────────────

    [Fact]
    public void EveryCapturedFigureExistsInBothVariantsAndDrawsSomething()
    {
        foreach (var row in FigureCatalog.Catalog)
            foreach (var variant in new[] { ColorVariant.Light, ColorVariant.Dark })
                AssertFigure(Path.Combine(Figures(), UiArtworkGenerator.FileStem(row.Id, variant) + ".svg"));
    }

    [Fact]
    public void EveryToolbarFigureExistsPlainAndIndexedInBothVariants()
    {
        foreach (var row in ToolbarCatalog.Catalog)
            foreach (var stem in new[] { "toolbar-" + row.Id, "toolbar-" + row.Id + "-indexed" })
                foreach (var variant in new[] { ColorVariant.Light, ColorVariant.Dark })
                    AssertFigure(Path.Combine(Figures(), UiArtworkGenerator.FileStem(stem, variant) + ".svg"));
    }

    [Fact]
    public void EverySymbolFigureExistsInBothVariantsAndDrawsSomething()
    {
        foreach (var (_, file, _) in SymbolArtworkGenerator.Catalog)
            foreach (var suffix in new[] { ".svg", "-dark.svg" })
                AssertFigure(Path.Combine(Symbols(), file + suffix));
    }

    /// <summary>
    /// A blank box on a page nobody re-reads is the failure mode this exists to catch, so "the file
    /// is there" is not enough — it must contain something that puts ink on the page.
    /// </summary>
    private static void AssertFigure(string path)
    {
        Assert.True(File.Exists(path),
            $"{Path.GetFileName(path)} has not been generated. Run: dotnet run --project tools/DocGen -- --out docs/user");

        var svg = File.ReadAllText(path);
        Assert.True(svg.Length > 0, $"{Path.GetFileName(path)} is empty.");
        Assert.True(SvgLint.HasDrawingElements(svg),
            $"{Path.GetFileName(path)} contains no drawing elements. An empty capture is a bug, not an "
          + "empty figure — the usual cause is a XAML refactor that broke the headless capture.");
    }

    // ── §10.2 — the dropped-paint lint over everything emitted ────────────────

    [Fact]
    public void NoEmittedFigureHasADroppedPaint()
    {
        var failures = new List<string>();
        foreach (var path in AllSvgs())
        {
            var findings = SvgLint.DroppedPaint(File.ReadAllText(path));
            if (findings.Count > 0)
                failures.Add(SvgLint.Explain(Path.GetRelativePath(DocsRoot(), path), findings));
        }

        Assert.True(failures.Count == 0, string.Join("\n", failures));
    }

    [Fact]
    public void NoDocumentationImageIsABitmap()
    {
        var bitmaps = Directory.EnumerateFiles(DocsRoot(), "*.*", SearchOption.AllDirectories)
            .Where(f => Path.GetExtension(f).ToLowerInvariant() is ".png" or ".jpg" or ".jpeg" or ".gif" or ".bmp")
            .Select(f => Path.GetRelativePath(DocsRoot(), f))
            .ToList();

        Assert.True(bitmaps.Count == 0,
            "The user documentation is vector only. If a figure can only be produced as a raster, that is "
          + "a finding to report, not a PNG to ship. Found: " + string.Join(", ", bitmaps));
    }

    // ── §10.3 — the anchor contract ───────────────────────────────────────────

    [Fact]
    public void EveryDeepLinkDocLauncherCanEmitResolvesInTheGeneratedHtml()
    {
        var offered = new HashSet<string>(StringComparer.Ordinal);
        foreach (var page in AllPages())
        {
            string rel = Path.GetRelativePath(DocsRoot(), page).Replace(Path.DirectorySeparatorChar, '/');
            offered.Add(rel);
            foreach (System.Text.RegularExpressions.Match m in Regex.Matches(File.ReadAllText(page), @"id=""(?<id>[^""]+)"""))
                offered.Add(rel + "#" + m.Groups["id"].Value);
        }

        var missing = DocAnchors.All()
            .Where(l => !offered.Contains(l.Anchor.Length == 0 ? l.Page : l.Page + "#" + l.Anchor))
            .Select(l => l.ToString())
            .ToList();

        Assert.True(missing.Count == 0,
            "These Help-button destinations do not exist in the generated documentation, so the button "
          + "would open the page at the top and say nothing:\n  " + string.Join("\n  ", missing));
    }

    // ── §10.4 — no unexpanded placeholder survives ────────────────────────────

    [Fact]
    public void NoEmittedPageContainsAnUnexpandedPlaceholder()
    {
        var offenders = new List<string>();
        foreach (var page in AllPages())
        {
            var m = Regex.Match(File.ReadAllText(page), @"\{\{[^}]*\}\}");
            if (m.Success)
                offenders.Add($"{Path.GetRelativePath(DocsRoot(), page)}: {m.Value}");
        }

        Assert.True(offenders.Count == 0,
            "A placeholder reached a shipped page as literal braces:\n  " + string.Join("\n  ", offenders));
    }

    // ── §10.5 — the toolbar manifest and its table agree ──────────────────────

    [Fact]
    public void EveryToolbarManifestIsGeneratedAndItsTableMatchesItRowForRow()
    {
        foreach (var row in ToolbarCatalog.Catalog)
        {
            string json = Path.Combine(Figures(), "toolbar-" + row.Id + ".json");
            Assert.True(File.Exists(json), $"No manifest for the '{row.Id}' toolbar. Regenerate the docs.");

            var entries = ReadManifest(json);
            Assert.NotEmpty(entries);

            var numbered = entries.Where(e => e.Index > 0).ToList();
            Assert.True(numbered.Count > 0, $"The '{row.Id}' toolbar manifest numbers nothing.");

            // Numbering must be 1..N with no gaps: the prose says "3 — Rotate", and a gap makes it wrong.
            Assert.Equal(Enumerable.Range(1, numbered.Count), numbered.Select(e => e.Index));

            var table = DocTables.ToolbarButtons(entries);
            var cells = Regex.Matches(table, @"<tr><td>(?<n>\d+)</td>").Select(m => int.Parse(m.Groups["n"].Value));
            Assert.Equal(numbered.Select(e => e.Index), cells);
        }
    }

    // ── The workspace figure's regions and its legend agree ───────────────────

    [Fact]
    public void EveryWorkspaceRegionIsNumberedOnceAndAppearsInTheLegendInOrder()
    {
        var regions = WorkspaceRegions.Catalog;
        Assert.NotEmpty(regions);

        // 1..N with no gaps and no repeats: the page says "3 — Project panel", and the number in the
        // picture is placed from this same list, so a gap or a duplicate makes one of them wrong.
        Assert.Equal(Enumerable.Range(1, regions.Count), regions.Select(r => r.Index));

        var legend = DocTables.WorkspaceRegionLegend();
        var cells = Regex.Matches(legend, @"<tr><td>(?<n>\d+)</td>").Select(m => int.Parse(m.Groups["n"].Value));
        Assert.Equal(regions.Select(r => r.Index), cells);

        foreach (var r in regions)
        {
            Assert.False(string.IsNullOrWhiteSpace(r.Title), $"Region {r.Index} has no title.");
            Assert.False(string.IsNullOrWhiteSpace(r.What),  $"Region {r.Index} ('{r.Title}') says nothing.");
            Assert.Contains(WebUtility.HtmlEncode(r.Title), legend);
        }
    }

    /// <summary>
    /// The generated page must actually carry the legend, not just be able to produce one — the
    /// figure's numbers mean nothing on a page that lost the table beside them.
    /// </summary>
    [Fact]
    public void TheWorkspacePageCarriesTheRegionLegend()
    {
        string page = Path.Combine(DocsRoot(), "reference", "workspace.html");
        Assert.True(File.Exists(page), "reference/workspace.html has not been generated.");

        string html = File.ReadAllText(page);
        foreach (var r in WorkspaceRegions.Catalog)
            Assert.Contains(WebUtility.HtmlEncode(r.Title), html);
    }

    [Fact]
    public void EveryToolbarButtonHasATooltip()
    {
        var silent = new List<string>();
        foreach (var row in ToolbarCatalog.Catalog)
        {
            // NOT "if (!File.Exists) continue": a gate that passes because its input is missing is
            // worse than no gate. If the manifest is absent the docs are stale, and that is the
            // finding.
            string json = Path.Combine(Figures(), "toolbar-" + row.Id + ".json");
            Assert.True(File.Exists(json),
                $"No manifest for the '{row.Id}' toolbar, so this check cannot run. Regenerate the docs.");
            foreach (var e in ReadManifest(json))
                if (e.Index > 0 && e.Kind is "button" or "toggle" && e.Tooltip.Length == 0)
                    silent.Add($"{row.Id} item {e.Index} ({(e.Id.Length == 0 ? e.Icon : e.Id)})");
        }

        Assert.True(silent.Count == 0,
            "A toolbar button with no tooltip is a UI bug, not a blank table cell — the documentation "
          + "cannot say what it does because the application does not:\n  " + string.Join("\n  ", silent));
    }

    private static IReadOnlyList<ToolbarCatalog.Entry> ReadManifest(string path)
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement.GetProperty("buttons").EnumerateArray()
            .Select(b => new ToolbarCatalog.Entry(
                b.GetProperty("Index").GetInt32(),
                b.GetProperty("Slot").GetInt32(),
                b.GetProperty("Id").GetString() ?? "",
                b.GetProperty("Tooltip").GetString() ?? "",
                b.GetProperty("Icon").GetString() ?? "",
                b.GetProperty("Command").ValueKind == JsonValueKind.Null ? null : b.GetProperty("Command").GetString(),
                b.GetProperty("Kind").GetString() ?? ""))
            .ToList();
    }

    // ── §10.6 — symbol catalog completeness ───────────────────────────────────

    [Fact]
    public void EveryUserPlaceableSymbolKindHasASymbolCatalogRow()
    {
        var documented = SymbolArtworkGenerator.Catalog.Select(r => r.Kind).ToHashSet();
        var missing = Enum.GetValues<SymbolKind>()
            .Where(k => !SymbolArtworkGenerator.NotUserPlaceable.Contains(k))
            .Where(k => !documented.Contains(k))
            .ToList();

        Assert.True(missing.Count == 0,
            "A new component type has no documentation figure. Add a row to "
          + "SymbolArtworkGenerator.Catalog, or add the kind to NotUserPlaceable if a user cannot place "
          + "it — this test exists so that decision is made rather than skipped:\n  "
          + string.Join("\n  ", missing));
    }

    [Fact]
    public void TheOnlyUndocumentedKindsAreTheTwoThatCannotBePlaced()
    {
        // Hard-coded on purpose: widening this list must be a deliberate edit, visible in a diff.
        Assert.Equal(new[] { SymbolKind.Generic, SymbolKind.Unknown },
                     SymbolArtworkGenerator.NotUserPlaceable.ToArray());
    }

    [Fact]
    public void EverySymbolFileStemIsUnique()
    {
        var dupes = SymbolArtworkGenerator.Catalog.GroupBy(r => r.File)
            .Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        Assert.True(dupes.Count == 0,
            "Two catalog rows write the same file, so one silently overwrites the other: "
          + string.Join(", ", dupes));
    }

    [Fact]
    public void EveryFigureIdIsUnique()
    {
        var dupes = FigureCatalog.Catalog.GroupBy(r => r.Id).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        Assert.True(dupes.Count == 0, "Duplicate figure id(s): " + string.Join(", ", dupes));
    }

    // ── The stale hand-made FET artwork is gone ───────────────────────────────

    [Fact]
    public void TheHandMadeFetSymbolIsGoneAndNothingStillReferencesIt()
    {
        foreach (var stale in new[] { "fet.svg", "fet-dark.svg" })
            Assert.False(File.Exists(Path.Combine(Symbols(), stale)),
                $"{stale} was hand-made and produced by nothing. The five FET laws now generate their own "
              + "figures; delete it rather than letting a stale drawing outlive the code.");

        foreach (var page in AllPages())
        {
            var text = File.ReadAllText(page);
            Assert.DoesNotContain("symbols/fet.svg", text, StringComparison.Ordinal);
            Assert.DoesNotContain("symbols/fet-dark.svg", text, StringComparison.Ordinal);
        }
    }

    // ── Fonts ─────────────────────────────────────────────────────────────────

    [Fact]
    public void NoEmittedFigureNamesAFontCircuitRfDoesNotShip()
    {
        // The gate this replaces accepted any name that STARTED with a shipped family, which is how
        // "IBM Plex Sans SemiBold" passed while being a family no @font-face declares — the browser
        // skipped it, fell back to the base family at the wrong weight, and every symbol caption
        // shipped Regular instead of SemiBold. An exact match is the only useful check.
        var offenders = new List<string>();
        foreach (var svg in AllSvgs())
        {
            if (Path.GetRelativePath(DocsRoot(), svg).Replace('\\', '/').StartsWith("assets/img/")) continue;

            foreach (System.Text.RegularExpressions.Match m in Regex.Matches(File.ReadAllText(svg), @"font-family=""(?<f>[^""]+)"""))
            {
                string value = m.Groups["f"].Value;
                if (!SvgFontNormalizer.ShippedFamilies.Contains(value, StringComparer.OrdinalIgnoreCase))
                    offenders.Add($"{Path.GetRelativePath(DocsRoot(), svg)}: '{value}'");
            }
        }

        Assert.True(offenders.Count == 0,
            "A figure names a font circuitRF does not ship. Either Skia wrote a face name the browser "
          + "cannot resolve, or it substituted a platform font for a glyph our typefaces lack — both "
          + "render wrongly and neither reports itself:\n  " + string.Join("\n  ", offenders.Distinct()));
    }

    [Fact]
    public void EveryFontFamilyAndWeightAnInlinedFigureUsesIsDeclaredInTheStylesheet()
    {
        string fontsDir = Path.Combine(DocsRoot(), "assets", "fonts");
        Assert.True(Directory.Exists(fontsDir), "docs/user/assets/fonts does not exist. Regenerate the docs.");

        string css = File.ReadAllText(Path.Combine(DocsRoot(), "assets", "css", "circuitrf-docs.css"));
        var declared = Regex.Matches(css,
                @"@font-face\s*\{[^}]*font-family:\s*""(?<f>[^""]+)""[^}]*url\(""\.\./fonts/(?<file>[^""]+)""\)[^}]*font-weight:\s*(?<w>\d+)[^}]*font-style:\s*(?<s>\w+)")
            .Select(m => (Family: m.Groups["f"].Value,
                          File:   Uri.UnescapeDataString(m.Groups["file"].Value),
                          Weight: int.Parse(m.Groups["w"].Value),
                          Style:  m.Groups["s"].Value))
            .ToList();

        Assert.NotEmpty(declared);

        foreach (var d in declared)
            Assert.True(File.Exists(Path.Combine(fontsDir, d.File)),
                $"circuitrf-docs.css declares @font-face for '{d.File}' but that file was not extracted.");

        // Only pages matter: a figure is inlined into a page, and only then does the page's CSS have
        // to be able to resolve it.
        var missing = new List<string>();
        foreach (var page in AllPages())
        {
            foreach (System.Text.RegularExpressions.Match m in Regex.Matches(File.ReadAllText(page), @"<text[^>]*>"))
            {
                var tag = m.Value;
                var fam = Regex.Match(tag, @"font-family=""(?<f>[^""]+)""");
                if (!fam.Success) continue;

                string family = fam.Groups["f"].Value;
                var wm = Regex.Match(tag, @"font-weight=""(?<w>\d+)""");
                int weight = wm.Success ? int.Parse(wm.Groups["w"].Value) : 400;
                string style = Regex.IsMatch(tag, @"font-style=""italic""") ? "italic" : "normal";

                if (!declared.Any(d => d.Family.Equals(family, StringComparison.OrdinalIgnoreCase)
                                    && d.Weight == weight && d.Style == style))
                    missing.Add($"{Path.GetRelativePath(DocsRoot(), page)}: {family} {weight} {style}");
            }
        }

        Assert.True(missing.Count == 0,
            "An inlined figure asks for a face the stylesheet does not declare, so the browser picks "
          + "the nearest declared weight and the figure renders in a weight it was not drawn in:\n  "
          + string.Join("\n  ", missing.Distinct()));
    }

    [Fact]
    public void TheFontLicencesTravelWithTheFonts()
    {
        string fontsDir = Path.Combine(DocsRoot(), "assets", "fonts");
        foreach (var licence in new[] { "OFL.txt", "DejaVu Fonts License.txt" })
            Assert.True(File.Exists(Path.Combine(fontsDir, licence)),
                $"{licence} must ship beside the extracted typefaces.");
    }

    // ── Inlined SVGs share the page's id namespace ────────────────────────────

    /// <summary>
    /// <b>No two elements on a generated page may share an id.</b>
    ///
    /// <para>This is the gate for the defect that produced four separate bug reports at once
    /// (2026-08-20). Figures are INLINED, so several SVGs land in one HTML document and share its
    /// single id namespace; <c>SvgPostPass.DedupePaths</c> numbers its hoisted paths <c>d0, d1, …</c>
    /// from zero per file, and Skia numbers its embedded images <c>img_0, img_1</c> the same way. A
    /// second figure's <c>&lt;use href="#d0"&gt;</c> then silently resolved to the FIRST figure's
    /// geometry. Symptoms: the Data Display toolbar "glitched out", the snap-glyph strip drew over
    /// corrupted metal while being perfect as a standalone file, the Wire Profile panel drew rulers
    /// and no wires, and the harmonicaRF page's DARK figure rendered the LIGHT contour raster.</para>
    /// </summary>
    [Fact]
    public void NoGeneratedPageHasTwoElementsWithTheSameId()
    {
        var idRx = new Regex(@"\bid=""(?<id>[^""]+)""", RegexOptions.Compiled);
        foreach (var page in AllPages())
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            var dupes = new List<string>();
            foreach (System.Text.RegularExpressions.Match m in idRx.Matches(File.ReadAllText(page)))
                if (!seen.Add(m.Groups["id"].Value)) dupes.Add(m.Groups["id"].Value);

            Assert.True(dupes.Count == 0,
                $"{Path.GetRelativePath(DocsRoot(), page)} defines these ids more than once: "
              + string.Join(", ", dupes.Distinct().Take(8))
              + ". Inlined figures share one id namespace, so a reference resolves to whichever "
              + "figure came first on the page. SvgPostPass scopes every id to its file for exactly "
              + "this reason — something has bypassed it.");
        }
    }

    /// <summary>
    /// <b>Every emitted figure carries a <c>viewBox</c>.</b> Without one an inline
    /// <c>&lt;svg&gt;</c> does not scale: the stylesheet's <c>max-width: 100%</c> narrows the
    /// element's box and the drawing is CLIPPED at full size rather than resized. Reported as "the
    /// schematic svg is not sized to the frame"; the symbol figures never showed it only because
    /// they are smaller than the column they sit in.
    /// </summary>
    [Fact]
    public void EveryEmittedFigureCarriesAViewBox()
    {
        foreach (var svg in AllSvgs())
        {
            if (Path.GetRelativePath(DocsRoot(), svg).Replace('\\', '/').StartsWith("assets/img/")) continue;

            var root = Regex.Match(File.ReadAllText(svg), @"<svg\b[^>]*>");
            Assert.True(root.Success, $"{Path.GetFileName(svg)} has no <svg> root element.");
            Assert.True(root.Value.Contains("viewBox=", StringComparison.Ordinal),
                $"{Path.GetFileName(svg)} has no viewBox, so inlined in a page it will be clipped "
              + "rather than scaled.");
        }
    }

    // ── Small numbers keep their precision ────────────────────────────────────

    /// <summary>
    /// <b>A magnitude below one is rounded to significant figures, not to two decimal places.</b>
    ///
    /// <para>Every ComboBox in the docs was drawing HALF a drop-down chevron. The chevron is a
    /// 2010-unit-wide geometry scaled into a 12 px icon box — <c>matrix(0.00597 0 0 0.00597 …)</c> —
    /// and rounding that scale to 2 dp made it <c>0.01</c>, blowing the glyph up by 67 % inside a
    /// clip that was still 12 px wide. Two decimal places is a hundredth of a pixel on a coordinate
    /// and a two-thirds error on a matrix scale.</para>
    /// </summary>
    [Theory]
    [InlineData("matrix(0.00597 0 0 0.00597 228 70.23)", "matrix(0.00597 0 0 0.00597 228 70.23)")]
    [InlineData("matrix(0.5 0 0 0.5 148 713)",           "matrix(0.5 0 0 0.5 148 713)")]
    [InlineData("M8.30361 12.99999L0.000123 1",          "M8.3 13L0.000123 1")]
    public void SmallMagnitudesKeepTheirPrecision(string input, string expected)
        => Assert.Equal(expected, SvgPostPass.RoundAll(input));

    // ── The opaque design payload is not a documented parameter ───────────────

    /// <summary>
    /// Match's and wBond's <c>Design</c> is base64 of the whole design's JSON. The parameter panel
    /// already refuses to show it as a text row; a documentation table listing it invites exactly
    /// the hand edit the interface declines to offer (owner, 2026-08-20).
    /// </summary>
    [Theory]
    [InlineData(CircuitRF.Ui.Schematic.SymbolKind.Match)]
    [InlineData(CircuitRF.Ui.Schematic.SymbolKind.WBond)]
    public void TheOpaqueDesignPayloadIsNotListedAsAParameter(SymbolKind kind)
    {
        Assert.Contains(ComponentTypeRegistry.DefaultParameters(kind, 2), p => p.Name == "Design");
        Assert.DoesNotContain("<td>Design</td>", DocTables.ComponentParameters(kind, 2));
    }

    // ── Generated files say how to regenerate themselves ──────────────────────

    [Fact]
    public void EveryGeneratedFileCarriesARegenerationBanner()
    {
        foreach (var svg in AllSvgs())
        {
            // The brand artwork under assets/img is authored, not generated.
            if (Path.GetRelativePath(DocsRoot(), svg).Replace('\\', '/').StartsWith("assets/img/")) continue;

            var head = File.ReadAllText(svg);
            Assert.True(head.Contains("GENERATED FILE", StringComparison.Ordinal),
                $"{Path.GetRelativePath(DocsRoot(), svg)} carries no banner saying which command regenerates it.");
        }
    }

    // ── The slide decks ───────────────────────────────────────────────────────

    /// <summary>
    /// Every <c>kind: slides</c> source under <c>docs/user/src/slides/</c>, as (path, front-matter,
    /// body). The decks are the one part of this pipeline that is NOT regenerated by the routine
    /// <c>--out docs/user</c> command and whose output is git-ignored, so nothing else in the repo
    /// would notice a deck that has stopped building.
    /// </summary>
    private static IEnumerable<(string Path, string Head, string Body)> DeckSources()
    {
        string dir = Path.Combine(DocsRoot(), "src", "slides");
        if (!Directory.Exists(dir)) yield break;

        foreach (var path in Directory.EnumerateFiles(dir, "*.md", SearchOption.AllDirectories)
                                      .OrderBy(p => p, StringComparer.Ordinal))
        {
            var text = File.ReadAllText(path).Replace("\r\n", "\n");
            int end = text.IndexOf("\n---", 4, StringComparison.Ordinal);
            if (!text.StartsWith("---\n", StringComparison.Ordinal) || end < 0) continue;
            yield return (path, text[4..end], text[(end + 4)..]);
        }
    }

    private static string FrontMatter(string head, string key)
    {
        foreach (var raw in head.Split('\n'))
        {
            var line = raw.Trim();
            int colon = line.IndexOf(':');
            if (colon > 0 && line[..colon].Trim() == key) return line[(colon + 1)..].Trim();
        }
        return "";
    }

    /// <summary>
    /// <b>Every deck the command line documents still exists.</b>
    ///
    /// <para><c>--deck overview</c> and its three siblings are advertised in the tool's own usage
    /// text and in the design note. A renamed or deleted source would make one of them an error the
    /// day somebody typed it, and nothing else here would fail: decks are built on demand and their
    /// PDFs are git-ignored, so the routine gate never touches them.</para>
    /// </summary>
    [Theory]
    [InlineData("overview")]
    [InlineData("new-user")]
    [InlineData("quick-start")]
    [InlineData("reference")]
    public void EveryDocumentedDeckIdHasASource(string deck)
    {
        var decks = DeckSources()
                   .Where(d => FrontMatter(d.Head, "kind") == "slides")
                   .Select(d => FrontMatter(d.Head, "deck"))
                   .ToList();

        Assert.True(decks.Contains(deck),
            $"No slide source declares 'deck: {deck}', so "
          + $"`dotnet run --project tools/DocGen -- --slides docs/slides --deck {deck}` now fails. "
          + $"Sources found: {(decks.Count == 0 ? "(none)" : string.Join(", ", decks))}.");
    }

    /// <summary>
    /// <b>Every deck declares a deck id, and no two decks share one.</b> A slides page without one
    /// can only ever be built as part of "all" — which is the state <c>--deck</c> exists to fix —
    /// and two pages sharing an id would build one and silently skip the other.
    /// </summary>
    [Fact]
    public void DeckIdsAreDeclaredAndUnique()
    {
        var ids = new List<string>();
        foreach (var (path, head, _) in DeckSources())
        {
            if (FrontMatter(head, "kind") != "slides") continue;
            var id = FrontMatter(head, "deck");
            Assert.True(id.Length > 0,
                $"{Path.GetFileName(path)} is a 'kind: slides' page with no 'deck:' id in its front-matter.");
            ids.Add(id);
        }

        var dupes = ids.GroupBy(i => i).Where(g => g.Count() > 1).Select(g => g.Key).ToList();
        Assert.True(dupes.Count == 0,
            "Two slide sources declare the same deck id, so --deck would build one of them and "
          + "silently skip the other: " + string.Join(", ", dupes));
    }

    /// <summary>
    /// <b>Every figure a deck cites is in the catalog, and every deck placeholder is one the deck
    /// backend knows.</b>
    ///
    /// <para>The generator raises both of these, but only when a deck is actually built — and a deck
    /// is built on demand. This is the gate that fails in the routine suite the moment a
    /// <c>FigureCatalog</c> row is renamed out from under a slide.</para>
    /// </summary>
    [Fact]
    public void EveryDeckPlaceholderResolves()
    {
        var known    = FigureCatalog.Catalog.Select(r => r.Id).ToHashSet(StringComparer.Ordinal);
        var problems = new List<string>();

        foreach (var (path, _, body) in DeckSources())
        {
            string name = Path.GetFileName(path);
            foreach (System.Text.RegularExpressions.Match m in Regex.Matches(body, @"\{\{\s*(?<kind>[a-z]+)\s*:\s*(?<arg>[^}]*)\}\}"))
            {
                var kind = m.Groups["kind"].Value;
                if (kind is not ("ui" or "caption" or "stats"))
                {
                    problems.Add($"{name}: placeholder '{kind}' is not one a deck understands "
                               + "(ui, caption, stats).");
                    continue;
                }
                if (kind != "ui") continue;

                var id = m.Groups["arg"].Value.Split('|')[0].Trim();
                if (!known.Contains(id))
                    problems.Add($"{name}: figure '{id}' is not in FigureCatalog.");
            }
        }

        Assert.True(problems.Count == 0, string.Join("\n", problems));
    }

    /// <summary>
    /// <b>A slide's caption belongs to a figure on the same slide.</b> A caption with no figure is
    /// not an error the backend can raise — it simply never draws — so the sentence disappears and
    /// the deck still generates cleanly.
    /// </summary>
    [Fact]
    public void EveryDeckCaptionSitsOnASlideThatHasAFigure()
    {
        var orphans = new List<string>();

        foreach (var (path, _, body) in DeckSources())
        {
            bool figureOnThisSlide = false;
            foreach (var raw in body.Split('\n'))
            {
                var line = raw.Trim();
                if (line.StartsWith("#", StringComparison.Ordinal)) { figureOnThisSlide = false; continue; }
                if (Regex.IsMatch(line, @"^\{\{\s*ui\s*:")) { figureOnThisSlide = true; continue; }
                if (Regex.IsMatch(line, @"^\{\{\s*caption\s*:") && !figureOnThisSlide)
                    orphans.Add($"{Path.GetFileName(path)}: {line}");
            }
        }

        Assert.True(orphans.Count == 0,
            "These captions are on a slide with no figure, so they are silently dropped:\n  "
          + string.Join("\n  ", orphans));
    }

    /// <summary>
    /// <b>A documentation schematic is not a template.</b>
    ///
    /// <para><c>src/Ui/resources/doc-schematics/*.csch</c> exist so a user-doc figure can photograph a
    /// two-component circuit a reader is about to build. They are embedded exactly like the shipped
    /// templates and <c>ShippedSchematicTemplates.Discover</c> scans every embedded <c>.csch</c>, so
    /// the ONLY thing keeping them out of the template picker is the logical-name filter. Dropping
    /// that filter would add teaching examples to the product's template list silently — a product
    /// change made by accident, which is precisely the class of thing a gate is for.</para>
    /// </summary>
    [Fact]
    public void DocumentationSchematicsAreNotOfferedAsTemplates()
    {
        var offered = ShippedSchematicTemplates.All.Select(t => t.Id).ToList();

        string dir = Path.Combine(RepoRoot(), "src", "Ui", "resources", "doc-schematics");
        Assert.True(Directory.Exists(dir),
            $"{dir} is missing, so every figure built on a documentation schematic has no source.");

        var docStems = Directory.EnumerateFiles(dir, "*.csch")
                                .Select(Path.GetFileNameWithoutExtension)
                                .ToList();
        Assert.NotEmpty(docStems);

        var leaked = docStems.Where(stem => offered.Contains(stem!)).ToList();
        Assert.True(leaked.Count == 0,
            "These documentation-only schematics are being offered in the template picker: "
          + string.Join(", ", leaked) + ". They are embedded with a distinct LogicalName so "
          + "ShippedSchematicTemplates.Discover can skip them; that filter has been lost.");

        // …and each one still loads through the real reader, which is the whole reason they are
        // files rather than hand-built view-models.
        foreach (var stem in docStems)
        {
            var model = ShippedSchematicTemplates.LoadDocSchematic(stem!);
            Assert.True(model.Components.Count > 0,
                $"Documentation schematic '{stem}' parsed to an empty circuit.");
        }
    }

    // ── Documentation search ─────────────────────────────────────────────────
    //
    // The search is two halves that have to agree: a GENERATED index
    // (assets/js/search-index.js, rebuilt by tools/DocGen) and a HAND-WRITTEN reader
    // (assets/js/docs-search.js). Neither announces its own failure — a stale index
    // sends readers to anchors that no longer exist, a missing script leaves a search
    // box that silently does nothing, and both look completely normal in a browser
    // until you type. These gates are what notice.

    private static string SearchIndexPath() => Path.Combine(DocsRoot(), "assets", "js", "search-index.js");
    private static string SearchScriptPath() => Path.Combine(DocsRoot(), "assets", "js", "docs-search.js");

    /// <summary>The index's payload, parsed out of the one assignment the generated file contains.</summary>
    private static JsonElement SearchIndexJson()
    {
        string js = File.ReadAllText(SearchIndexPath());
        int eq = js.IndexOf("window.CRF_DOCS_SEARCH = ", StringComparison.Ordinal);
        Assert.True(eq >= 0,
            "search-index.js does not assign window.CRF_DOCS_SEARCH. docs-search.js reads exactly that "
          + "global and gives up silently when it is absent, so the search boxes would never appear.");

        string json = js[(eq + "window.CRF_DOCS_SEARCH = ".Length)..].TrimEnd().TrimEnd(';');
        return JsonDocument.Parse(json).RootElement.Clone();
    }

    /// <summary>
    /// <b>Every search result must land on an anchor that exists.</b>
    ///
    /// <para>This is the same failure the Help-button gate above catches, arriving by a different
    /// road: a section is renamed or an explicit <c>{#id}</c> changes, the index still carries the
    /// old anchor, and every result for that section opens the page scrolled to the top with no
    /// error anywhere. Regenerating fixes it — which is exactly why the check has to be automatic,
    /// because nobody re-reads 450 search results by hand.</para>
    /// </summary>
    [Fact]
    public void EverySearchResultResolvesToAnAnchorInTheShippedPages()
    {
        var offered = new HashSet<string>(StringComparer.Ordinal);
        foreach (var page in AllPages())
        {
            string rel = Path.GetRelativePath(DocsRoot(), page).Replace(Path.DirectorySeparatorChar, '/');
            offered.Add(rel);
            foreach (System.Text.RegularExpressions.Match m in Regex.Matches(File.ReadAllText(page), @"id=""(?<id>[^""]+)"""))
                offered.Add(rel + "#" + m.Groups["id"].Value);
        }

        var root = SearchIndexJson();
        var pages = root.GetProperty("p").EnumerateArray().Select(p => p[0].GetString()!).ToList();

        var broken = new List<string>();
        foreach (var s in root.GetProperty("s").EnumerateArray())
        {
            string slug = pages[s[0].GetInt32()];
            string anchor = s[1].GetString()!;
            string link = anchor.Length == 0 ? slug : slug + "#" + anchor;
            if (!offered.Contains(link)) broken.Add($"{link}  (\"{s[2].GetString()}\")");
        }

        Assert.True(broken.Count == 0,
            "These search results point at anchors that are not in the shipped HTML, so choosing one "
          + "opens the page at the top and says nothing. Re-run tools/DocGen:\n  "
          + string.Join("\n  ", broken));
    }

    /// <summary>
    /// <b>The index must cover the whole reading order.</b>
    ///
    /// <para>A page missing from it is unfindable while looking completely normal to a reader who
    /// arrives by a link — the exact invisibility the reading-order orphan check exists to prevent
    /// on the navigation side.</para>
    /// </summary>
    [Fact]
    public void TheSearchIndexCoversEveryPageInTheReadingOrder()
    {
        var indexed = SearchIndexJson().GetProperty("p").EnumerateArray()
                                       .Select(p => p[0].GetString()!)
                                       .ToHashSet(StringComparer.Ordinal);

        var expected = AllPages()
            .Select(p => Path.GetRelativePath(DocsRoot(), p).Replace(Path.DirectorySeparatorChar, '/'))
            .ToList();

        var missing = expected.Where(p => !indexed.Contains(p)).ToList();
        Assert.True(missing.Count == 0,
            "These pages ship but are not in the search index, so nothing a reader types can find "
          + "them:\n  " + string.Join("\n  ", missing));
    }

    /// <summary>
    /// <b>No figure geometry may reach the index.</b>
    ///
    /// <para>Pages are ~1 MB each because their figures are inlined as <c>&lt;svg&gt;</c>. The
    /// extraction removes those by counting tag depth, and if that ever stops working the index does
    /// not break — it silently grows by two orders of magnitude, ships to every reader, and matches
    /// queries against path coordinates. A size ceiling plus a look for path data catches both
    /// halves of that.</para>
    /// </summary>
    [Fact]
    public void TheSearchIndexCarriesProseAndNotFigureGeometry()
    {
        long bytes = new FileInfo(SearchIndexPath()).Length;
        Assert.True(bytes < 1_500_000,
            $"search-index.js is {bytes:N0} bytes. It holds the prose of ~33 pages and should be well "
          + "under a megabyte; this size means figure geometry is being indexed as text.");

        var offenders = new List<string>();
        var root = SearchIndexJson();
        var pages = root.GetProperty("p").EnumerateArray().Select(p => p[0].GetString()!).ToList();

        foreach (var s in root.GetProperty("s").EnumerateArray())
        {
            string text = s[3].GetString()!;
            // Three consecutive SVG coordinate pairs: prose does not contain this and path data is
            // nothing but this.
            if (Regex.IsMatch(text, @"(-?\d+\.\d+[ ,]+){6}"))
                offenders.Add($"{pages[s[0].GetInt32()]}#{s[1].GetString()}");
        }

        Assert.True(offenders.Count == 0,
            "These indexed sections contain SVG path data rather than prose:\n  "
          + string.Join("\n  ", offenders));
    }

    /// <summary>
    /// <b>Every page carries the search box and both scripts, at the right relative depth.</b>
    ///
    /// <para>The docs are opened from a web host, from the loopback server the Help menu starts, and
    /// straight off disk, so every reference between them is relative. A wrong number of
    /// <c>../</c> segments is invisible on the landing page and broken everywhere below it.</para>
    /// </summary>
    [Fact]
    public void EveryPageCarriesTheSearchBoxAndItsScripts()
    {
        var offenders = new List<string>();
        foreach (var page in AllPages())
        {
            string rel  = Path.GetRelativePath(DocsRoot(), page).Replace(Path.DirectorySeparatorChar, '/');
            string html = File.ReadAllText(page);
            string depth = string.Concat(Enumerable.Repeat("../", rel.Count(c => c == '/')));

            if (!html.Contains("class=\"doc-search\" data-crf-search", StringComparison.Ordinal))
                offenders.Add($"{rel}: no header search box");
            if (!html.Contains($"data-root=\"{depth}\"", StringComparison.Ordinal))
                offenders.Add($"{rel}: search box data-root is not \"{depth}\", so every result would "
                            + "link to the wrong place");
            foreach (var script in new[] { "search-index.js", "docs-search.js" })
                if (!html.Contains($"src=\"{depth}assets/js/{script}\"", StringComparison.Ordinal))
                    offenders.Add($"{rel}: does not load {depth}assets/js/{script}");
        }

        Assert.True(offenders.Count == 0,
            "The search is wired wrongly on these pages:\n  " + string.Join("\n  ", offenders));
    }

    /// <summary>
    /// <b>The hand-written half of the search still exists and still reads the generated half.</b>
    ///
    /// <para><c>docs-search.js</c> is not generated, so nothing else in this pipeline would notice it
    /// being deleted or renamed — and the symptom is a search box that accepts typing and does
    /// nothing, on every page, with no error.</para>
    /// </summary>
    [Fact]
    public void TheSearchScriptIsShippedAndReadsTheGeneratedIndex()
    {
        Assert.True(File.Exists(SearchScriptPath()),
            "docs/user/assets/js/docs-search.js is missing. It is hand-written, not generated, so "
          + "re-running tools/DocGen will not bring it back.");

        string js = File.ReadAllText(SearchScriptPath());
        Assert.Contains("window.CRF_DOCS_SEARCH", js);
        Assert.Contains("data-crf-search", js);
    }

    /// <summary>
    /// <b>The landing page's own search box sits where a reader arriving with a question will look
    /// for it</b> — below the three guide cards, above the prose. Asserted by position, because the
    /// box existing somewhere on the page is not the thing that was asked for.
    /// </summary>
    [Fact]
    public void TheLandingPageCarriesTheSearchBoxBetweenTheCardsAndTheProse()
    {
        string html = File.ReadAllText(Path.Combine(DocsRoot(), "index.html"));

        int cards = html.IndexOf("class=\"card-grid\"", StringComparison.Ordinal);
        int hero  = html.IndexOf("class=\"search-hero\"", StringComparison.Ordinal);
        int prose = html.IndexOf("id=\"what-is-circuitrf\"", StringComparison.Ordinal);

        Assert.True(hero >= 0, "The landing page has no search box. It comes from {{search: hero}} in "
                             + "docs/user/src/index.md.");
        Assert.True(cards >= 0 && cards < hero && hero < prose,
            "The landing page's search box is not between the guide cards and \"What is circuitRF?\".");
    }
}
