using CircuitRF.Ui.Layout;
using CircuitRF.Design.Layout.Interchange;
using CircuitRF.Ui.Schematic;

namespace CircuitRF.Ui.Tests;

/// <summary>
/// Gate R-dxf-3 (docs/sonnet-briefs/brief-dxf-version-support.md §3) — real R12, R2000, and R2018 files
/// from a tool that is NOT this one (L4b's gate 12 precedent). All three fixtures were generated by
/// <c>ezdxf 1.4.4</c> (a real, independent, spec-compliant Python DXF library — confirmed openable by
/// BOTH ezdxf's own reader and QCAD 3.32.9's bundled ODA-based `dwginfo` converter before being checked
/// in), each carrying: a closed 4-vertex polyline with one 90-degree bulge (R-L4b-3 — this is the least-
/// exercised path for R12's own old-style POLYLINE/VERTEX form), a layer named "Défense" (a character
/// representable in Windows-1252 but not ASCII), and a TEXT label "Résistance Ω" (mixing a Windows-1252-
/// representable character with one that is NOT — Ω forces even ezdxf's own R12/R2000 writer to fall back
/// to a `\U+XXXX` escape, which is exactly the real-world case R-dxf-2 exists to handle correctly).
/// Fixtures live in testdata/dxf-version-samples/.
/// </summary>
public class DxfVersionToleranceTests : IDisposable
{
    private readonly string _dir = Directory.CreateTempSubdirectory("dxf-version-tolerance-test-").FullName;

    public void Dispose() => Directory.Delete(_dir, recursive: true);

    private static string FixturePath(string name)
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            var candidate = Path.Combine(dir, "testdata", "dxf-version-samples", name);
            if (File.Exists(candidate)) return candidate;
            dir = Path.GetDirectoryName(dir);
        }
        throw new FileNotFoundException($"Fixture not found: {name}");
    }

    private DxfImport.ImportResult ImportFixture(string fileName, bool insUnitsPresent)
    {
        using var stream = File.OpenRead(FixturePath(fileName));
        // A real destination technology (none of whose layers are named "Défense") so the layer
        // reconciliation pass actually produces a row — with destTech: null, "keep as unknown" is
        // decided with nothing to compare against and no row is ever reported (verified directly: a
        // null destTech left the layer-mapping summary message entirely absent).
        return DxfImport.Import(
            stream, _dir, destTech: StarterTechnologies.Pcb2Layer(), destDbuPerMicron: 1000,
            resolveUnits: insUnitsPresent ? null : (_ => DxfUnits.Millimeters));
    }

    private LayoutView LoadModelSpaceView(DxfImport.ImportResult result)
    {
        string cellName = result.CellNameByBlockName[DxfReader.ModelSpaceName];
        var cellDir = Path.Combine(_dir, cellName);
        var layoutDir = CellFolder.SubFolderPath(cellDir, ViewType.Layout);
        return LayoutPersistence.LoadFromFile(Path.Combine(layoutDir, $"{cellName}.clay"));
    }

    // ── R12 (AC1009) — produced by ezdxf 1.4.4; opens cleanly in ezdxf and QCAD/ODA's dwginfo ─────────

    [Fact]
    public void R12File_ImportsWithoutRejection_BulgeIntact_NonAsciiLayerAndTextDecodeCorrectly()
    {
        var result = ImportFixture("r12-ezdxf-sample.dxf", insUnitsPresent: false); // R12 never writes $INSUNITS
        Assert.False(result.Cancelled);

        AssertVersionAndEncodingReported(result, expectUtf8: false);
        AssertLayerNameSurvived(result, "Défense");
        AssertBulgeAndTextSurvived(result);
    }

    // ── R2000 (AC1015) — produced by ezdxf 1.4.4; the exact version this exporter itself writes ────────

    [Fact]
    public void R2000File_ImportsWithoutRejection_BulgeIntact_NonAsciiLayerAndTextDecodeCorrectly()
    {
        var result = ImportFixture("r2000-ezdxf-sample.dxf", insUnitsPresent: true);
        Assert.False(result.Cancelled);

        AssertVersionAndEncodingReported(result, expectUtf8: false);
        AssertLayerNameSurvived(result, "Défense");
        AssertBulgeAndTextSurvived(result);
    }

    // ── R2018 (AC1032) — produced by ezdxf 1.4.4; real UTF-8 on the wire, no escapes needed ────────────

    [Fact]
    public void R2018File_ImportsWithoutRejection_BulgeIntact_NonAsciiLayerAndTextDecodeCorrectly()
    {
        var result = ImportFixture("r2018-ezdxf-sample.dxf", insUnitsPresent: true);
        Assert.False(result.Cancelled);

        AssertVersionAndEncodingReported(result, expectUtf8: true);
        AssertLayerNameSurvived(result, "Défense");
        AssertBulgeAndTextSurvived(result);
    }

    /// <summary>"Nothing rejects a file merely for its version" — a broader $ACADVER never causes a
    /// version-gate refusal; the CLASSES/OBJECTS sections R2018 carries (much larger than R2000's, per
    /// the brief's own §3 wording) are skipped cleanly rather than tripping any parsing assumption.</summary>
    [Fact]
    public void AllThreeVersions_AreNeverRefusedForTheirVersion()
    {
        Assert.False(ImportFixture("r12-ezdxf-sample.dxf", insUnitsPresent: false).Cancelled);
        Assert.False(ImportFixture("r2000-ezdxf-sample.dxf", insUnitsPresent: true).Cancelled);
        Assert.False(ImportFixture("r2018-ezdxf-sample.dxf", insUnitsPresent: true).Cancelled);
    }

    private static void AssertVersionAndEncodingReported(DxfImport.ImportResult result, bool expectUtf8)
    {
        string? encodingMsg = result.Messages.FirstOrDefault(m => m.StartsWith("Text encoding:"));
        Assert.NotNull(encodingMsg);
        if (expectUtf8) Assert.Contains("UTF-8", encodingMsg);
        else Assert.Contains("code page", encodingMsg, StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>With no destination technology and no interactive layer-mapping resolution, every new
    /// layer defaults to "keep as unknown" — it never lands in <c>LayersToAdd</c>. The decoded raw name
    /// is instead visible in the layer-mapping summary message (<c>LayoutLayerMapping.SummarizeMapping</c>,
    /// the same one the Retarget/paste dialogs show), so that is what this test checks.</summary>
    private static void AssertLayerNameSurvived(DxfImport.ImportResult result, string expectedLayerName)
    {
        Assert.Contains(result.Messages, m => m.Contains(expectedLayerName, StringComparison.Ordinal));
    }

    private void AssertBulgeAndTextSurvived(DxfImport.ImportResult result)
    {
        var view = LoadModelSpaceView(result);

        // R-L4b-3: bulges are load-bearing on import — must not have silently become a chord, for
        // EITHER the old-style POLYLINE/VERTEX form (R12) or LWPOLYLINE (R2000/R2018).
        var curve = view.Shapes.OfType<CurveShape>().SingleOrDefault(c => c.Edges is { Count: > 0 });
        Assert.NotNull(curve);
        Assert.Contains(curve!.Edges!, e => e.Kind == EdgeKind.Arc && Math.Abs(e.Bulge - 0.4142135623730951) < 1e-6);

        var label = view.Shapes.OfType<LabelShape>().SingleOrDefault();
        Assert.NotNull(label);
        Assert.Equal("Résistance Ω", label!.Text);
    }
}
