// R-em-20 — the .snp carries a provenance stamp, and a stale one is DETECTED rather than silently
// believed. §10.8 is explicit that this is the one failure mode the design introduces (an .snp
// referenced by a schematic can outlive the layout it came from) and that the whole mitigation is a
// header stamp plus a warning.
//
// **Hash the extracted EmProblem, not the raw file bytes.** A cosmetic layout edit — moving a
// silkscreen label, renaming a net, nudging a via — must NOT report staleness, and a change that
// genuinely moves the cross-section must ALWAYS report it. The EmProblem is exactly "everything the
// answer depends on and nothing else", so hashing it makes both halves of that true by construction
// rather than by a heuristic about which edits matter.

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using CircuitRF.Engine.Mom;

namespace CircuitRF.Ui.Layout.Em;

/// <summary>The fields of a provenance stamp, parsed back out of an existing <c>.snp</c> header.</summary>
public sealed record EmProvenanceStamp(string GeometryHash, string MeshHash, string PortHash)
{
    public const string Marker         = "circuitRF-EM";
    public const string GeometryPrefix = "circuitRF-EM geometry: ";
    public const string MeshPrefix     = "circuitRF-EM mesh: ";
    public const string PortPrefix     = "circuitRF-EM ports: ";
}

public static class EmSnpProvenance
{
    /// <summary>The header lines to stamp into a freshly written <c>.snp</c>.</summary>
    public static IReadOnlyList<string> BuildHeader(
        EmProblem problem, EmMeshSettings mesh, string setupName, string layoutRef, DateTimeOffset when)
        => BuildHeader(QuasiStaticKernel.KernelName,
                       GeometryHash(problem), MeshHash(mesh), PortHash(problem),
                       setupName, layoutRef, when);

    /// <summary>
    /// D9 — the planar counterpart. <b>A planar run through the same <c>.snp</c> path with no planar
    /// hashes would write a stamp that CANNOT go stale, which is worse than no stamp at all</b>: the
    /// warning §10.8 calls "the one failure mode this design introduces" would simply stay silent
    /// while a schematic went on reading a result the layout no longer produces.
    /// </summary>
    public static IReadOnlyList<string> BuildHeader(
        PlanarProblem problem, PlanarMeshSettings mesh, IReadOnlyList<PlanarPort> ports,
        string setupName, string layoutRef, DateTimeOffset when)
        => BuildHeader(PlanarKernel.KernelName,
                       GeometryHash(problem), MeshHash(mesh), PortHash(ports),
                       setupName, layoutRef, when);

    private static IReadOnlyList<string> BuildHeader(
        string kernelName, string geometry, string mesh, string ports,
        string setupName, string layoutRef, DateTimeOffset when)
        => [
            $"Generated by circuitRF — EM: {kernelName}",
            $"circuitRF-EM setup: {setupName}",
            $"circuitRF-EM layout: {layoutRef}",
            $"circuitRF-EM written: {when.ToString("u", CultureInfo.InvariantCulture)}",
            EmProvenanceStamp.GeometryPrefix + geometry,
            EmProvenanceStamp.MeshPrefix     + mesh,
            EmProvenanceStamp.PortPrefix     + ports,
            "circuitRF-EM: re-running the EM setup rewrites this file. If circuitRF reports it as " +
            "stale, the layout's cross-section changed after this file was written.",
        ];

    /// <summary>
    /// The stackup identity, conductor outlines and length — everything the extracted cross-section
    /// consists of. Deliberately excludes port reference impedances and mesh settings, which get
    /// their own lines so a mismatch can say WHICH of the three moved.
    /// </summary>
    public static string GeometryHash(EmProblem p)
    {
        var sb = new StringBuilder();
        sb.Append("L=").Append(R(p.LengthMeters)).Append('|');
        foreach (var c in p.Conductors)
        {
            sb.Append("C:").Append(c.Name).Append(':').Append(R(c.SigmaSm)).Append(':');
            foreach (var pt in c.Outline) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
            sb.Append('|');
        }
        foreach (var r in p.Regions)
            sb.Append("R:").Append(R(r.YBottom)).Append(':').Append(R(r.YTop)).Append(':')
              .Append(R(r.Material.EpsR)).Append(':').Append(R(r.Material.TanD)).Append(':')
              .Append(R(r.Material.MuR)).Append('|');
        sb.Append("G:").Append(p.Ground is null ? "none" : R(p.Ground.Y) + ":" + R(p.Ground.SigmaSm));
        return Sha(sb.ToString());
    }

    public static string MeshHash(EmMeshSettings m)
        => Sha($"{m.MinCellsAcrossWidth}|{m.EdgeCells}|{R(m.EdgeFractionOfWidth)}|" +
               $"{R(m.EdgeGrowthRatio)}|{R(m.TruncationHeights)}|{m.TruncationTailCells}");

    public static string PortHash(EmProblem p)
    {
        var sb = new StringBuilder();
        foreach (var port in p.Ports)
            sb.Append(port.Number).Append(':').Append(port.Conductor).Append(':')
              .Append(port.ReferenceConductor ?? "gnd").Append(':')
              .Append(R(port.Z0.Real)).Append(',').Append(R(port.Z0.Imaginary)).Append('|');
        return Sha(sb.ToString());
    }

    // ── D9: the planar hashes ─────────────────────────────────────────────────────────────────
    //
    // Same rule as kernel A's, applied to the other problem type: hash EXACTLY what the answer
    // depends on. For a planar run that is the conductor artwork in metres, the slab, and the
    // sweep's top frequency (which is what sizes the mesh, R-msh-3) — plus the mesh controls and the
    // ports, each on their own line so a mismatch can still say WHICH of the three moved.

    public static string GeometryHash(PlanarProblem p)
    {
        var sb = new StringBuilder();
        sb.Append("F=").Append(R(p.MaxFrequencyHz)).Append('|');
        sb.Append("S:").Append(R(p.Slab.HeightM)).Append(':')
          .Append(R(p.Slab.Material.EpsR)).Append(':')
          .Append(R(p.Slab.Material.TanD)).Append(':')
          .Append(R(p.Slab.Material.MuR)).Append('|');

        // L9d — the general MEDIUM and each level's own z, or the answer changes with nothing the
        // hash can see. Before L9d there was one level on one slab and the slab line above said all
        // of it; a two-level problem that keeps the same artwork and moves a spacer is a different
        // structure, and staleness has to notice.
        if (p.MediumStack is { } ms)
        {
            sb.Append("M:").Append(R(ms.Bottom.Material.EpsR)).Append(':')
              .Append(R(ms.Top.Material.EpsR)).Append(':');
            foreach (var ml in ms.Layers)
                sb.Append(R(ml.ThicknessM)).Append(',').Append(R(ml.Material.EpsR)).Append(',')
                  .Append(R(ml.Material.TanD)).Append(',').Append(R(ml.Material.MuR)).Append(';');
            sb.Append('|');
        }

        foreach (var via in p.ViaList)
        {
            sb.Append("V:").Append(via.LowerLayerIndex).Append("->").Append(via.UpperLayerIndex)
              .Append(':').Append(R(via.SigmaSm)).Append(':');
            foreach (var poly in via.Polygons)
                foreach (var pt in poly.Outer) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
            sb.Append('|');
        }

        for (int li = 0; li < p.Layers.Count; li++)
        {
            var layer = p.Layers[li];
            sb.Append("L:").Append(layer.Name).Append(':').Append(R(layer.SigmaSm)).Append(':')
              .Append(R(layer.ThicknessM)).Append(':').Append(R(p.LevelZ(li))).Append('|');
            foreach (var poly in layer.Polygons)
            {
                foreach (var pt in poly.Outer) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
                sb.Append('/');
                foreach (var hole in poly.HoleRings)
                {
                    foreach (var pt in hole) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
                    sb.Append('/');
                }
                sb.Append('|');
            }
        }
        return Sha(sb.ToString());
    }

    public static string MeshHash(PlanarMeshSettings m)
        => Sha($"{m.Auto}|{m.CellsPerWavelength}|{m.EdgeMesh}|{m.EdgeCells}");

    /// <summary>
    /// A port's identity for staleness purposes is its number, its POSITION, its inferred side and
    /// its reference impedance. Position is in because moving a port label to the other end of the
    /// conductor changes the answer completely and changes nothing else the other two hashes see.
    /// </summary>
    public static string PortHash(IReadOnlyList<PlanarPort> ports)
    {
        var sb = new StringBuilder();
        foreach (var p in ports)
            sb.Append(p.Number).Append(':').Append(p.Side).Append(':').Append(p.LayerIndex).Append(':')
              .Append(R(p.Location.X)).Append(',').Append(R(p.Location.Y)).Append(':')
              .Append(R(p.Z0.Real)).Append(',').Append(R(p.Z0.Imaginary)).Append(':')
              .Append(p.Reference).Append('|');
        return Sha(sb.ToString());
    }

    /// <summary>Reads a stamp back out of a <c>.snp</c>'s header comments. Null when the file is not
    /// circuitRF-EM-stamped (a hand-written or third-party Touchstone), which is not staleness —
    /// there is simply nothing to compare against.</summary>
    public static EmProvenanceStamp? TryRead(string snpPath)
    {
        if (!File.Exists(snpPath)) return null;
        string? geo = null, mesh = null, ports = null;
        try
        {
            foreach (var raw in File.ReadLines(snpPath))
            {
                string line = raw.TrimStart();
                if (line.StartsWith('#')) break;          // the option line ends the header
                if (!line.StartsWith('!')) continue;
                line = line[1..].Trim();
                if (line.StartsWith(EmProvenanceStamp.GeometryPrefix, StringComparison.Ordinal))
                    geo = line[EmProvenanceStamp.GeometryPrefix.Length..].Trim();
                else if (line.StartsWith(EmProvenanceStamp.MeshPrefix, StringComparison.Ordinal))
                    mesh = line[EmProvenanceStamp.MeshPrefix.Length..].Trim();
                else if (line.StartsWith(EmProvenanceStamp.PortPrefix, StringComparison.Ordinal))
                    ports = line[EmProvenanceStamp.PortPrefix.Length..].Trim();
            }
        }
        catch (IOException) { return null; }

        return geo is null || mesh is null || ports is null
            ? null
            : new EmProvenanceStamp(geo, mesh, ports);
    }

    /// <summary>
    /// Compares an existing <c>.snp</c>'s stamp against what a run would produce NOW. Returns null
    /// when there is nothing to warn about (no file, no stamp, or everything matches).
    /// </summary>
    public static string? DescribeStaleness(
        string snpPath, EmProblem problem, EmMeshSettings mesh)
        => Compare(snpPath, GeometryHash(problem), MeshHash(mesh), PortHash(problem),
                   "the cross-section geometry", "the port reference impedances");

    /// <summary>D9 — the planar counterpart, so a planar run's stamp can go stale at all.</summary>
    public static string? DescribeStaleness(
        string snpPath, PlanarProblem problem, PlanarMeshSettings mesh, IReadOnlyList<PlanarPort> ports)
        => Compare(snpPath, GeometryHash(problem), MeshHash(mesh), PortHash(ports),
                   "the layout geometry", "the ports");

    private static string? Compare(
        string snpPath, string geometry, string mesh, string ports,
        string geometryLabel, string portLabel)
    {
        var stamp = TryRead(snpPath);
        if (stamp is null) return null;

        var changed = new List<string>();
        if (stamp.GeometryHash != geometry) changed.Add(geometryLabel);
        if (stamp.MeshHash     != mesh)     changed.Add("the mesh settings");
        if (stamp.PortHash     != ports)    changed.Add(portLabel);
        if (changed.Count == 0) return null;

        return $"'{Path.GetFileName(snpPath)}' was written from a different setup — " +
               $"{string.Join(" and ", changed)} changed since. Any schematic referencing it was " +
               "using stale s-parameters; this run has just rewritten it.";
    }

    private static string R(double v) => v.ToString("R", CultureInfo.InvariantCulture);

    private static string Sha(string s)
        => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s)))[..16].ToLowerInvariant();
}
