// ================================================================
//  HarmonicaInterchange.cs  —  M4 of brief-harmonicarf-h7
//
//  R-h7-11  .gam in and out through the EXISTING GamReader / GamWriter (src/Engine/Loadpull), used
//           as-is. A grid imported from .gam is an arbitrary scatter, which is what ContourGrid was
//           built for (§6.4).
//  R-h7-13  Export testbench must produce a RUNNABLE .cnl that reproduces the current harmonicaRF
//           state through the ordinary HB path. HarmonicaContext.NetlistText is the OPEN-port form;
//           the terminations are deliberately not in it, so the export adds them.
// ================================================================

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Numerics;
using System.Text;
using CircuitRF.Engine.Loadpull;
using CircuitRF.Harmonica;

namespace CircuitRF.Ui.Harmonica;

/// <summary>
/// §7.8's clipboard and interchange: <c>.gam</c> grids in and out, the termination set as pasteable
/// text, and a runnable testbench.
///
/// <para><b>Framework-free on purpose.</b> Every method takes and returns strings and value objects,
/// so the whole of M4's behaviour — including the exported netlist that R-h7-13 gates on — is
/// exercisable without a window and runnable through the CLI.</para>
/// </summary>
public static class HarmonicaInterchange
{
    private static string Num(double v) => v.ToString("G17", CultureInfo.InvariantCulture);

    // ── .gam (R-h7-11) ────────────────────────────────────────────────────────

    /// <summary>
    /// Reads a <c>.gam</c> file's Γ points, through <see cref="GamReader"/> unchanged.
    ///
    /// <para>A freq-tagged file selects the block nearest <paramref name="targetFreqHz"/> —
    /// <c>GamReader.SelectForFreq</c>'s own rule, not a second one. Points at or beyond |Γ| = 1 are
    /// DROPPED with a note rather than accepted: the grid sweeps a passive load termination, and
    /// Γ = 1 is an open whose impedance the solve cannot represent.</para>
    /// </summary>
    public static IReadOnlyList<Complex> ImportGam(string text, double targetFreqHz,
                                                   out IReadOnlyList<string> notes)
    {
        var blocks = GamReader.ReadBlocksText(text);
        var grid   = GamReader.SelectForFreq(blocks, targetFreqHz);

        var kept    = new List<Complex>(grid.Points.Count);
        var dropped = new List<string>();

        foreach (var p in grid.Points)
        {
            if (p.Gamma.Magnitude >= 1.0)
            {
                dropped.Add($"line {p.LineNumber}: |Γ| = {p.Gamma.Magnitude:0.###}");
                continue;
            }
            kept.Add(p.Gamma);
        }

        var n = new List<string>();
        if (blocks.Count > 1)
            n.Add($"The file carries {blocks.Count} frequency blocks; the one nearest " +
                  $"{targetFreqHz / 1e9:0.###} GHz was used.");
        if (dropped.Count > 0)
            n.Add($"{dropped.Count} point(s) at or outside the unit circle were dropped " +
                  $"({string.Join("; ", dropped.Take(4))}" + (dropped.Count > 4 ? "; …" : "") + ").");
        notes = n;
        return kept;
    }

    /// <summary>
    /// Writes a Γ grid as <c>.gam</c> text through <see cref="GamWriter"/>'s own format — the
    /// <c>re+j*imag</c> impedance form with a <c>Z0=</c> header, which <see cref="GamReader"/> reads
    /// back.
    ///
    /// <para><b>Holes travel.</b> A point that did not reach compression is still a point of the
    /// grid — the user placed it, or imported it, and the run's answer there is "did not compress"
    /// rather than "absent". Dropping holes on export would silently shrink the grid every time it
    /// was round-tripped, so every point is written and the holes are marked in a comment.</para>
    /// </summary>
    public static string ExportGam(IReadOnlyList<HarmonicaGridPoint> points, double z0 = 50.0,
                                   double? freqHz = null)
    {
        ArgumentNullException.ThrowIfNull(points);

        var sb = new StringBuilder();
        sb.Append("# impedance Z0=").Append(Num(z0)).AppendLine(" re+j*imag");
        sb.AppendLine("# Generated by circuitRF harmonicaRF (harmonicarf.md §7.8)");

        int holes = points.Count(p => p.IsHole);
        if (holes > 0)
            sb.Append("# ").Append(holes).AppendLine(
                " of these points did not reach the compression target in the run they came from.");

        if (freqHz is { } f)
            sb.Append("freq=").Append(f.ToString("G10", CultureInfo.InvariantCulture)).AppendLine("Hz");

        foreach (var p in points)
        {
            Complex z = z0 * (Complex.One + p.Gamma) / (Complex.One - p.Gamma);
            sb.Append(z.Real.ToString("G10", CultureInfo.InvariantCulture))
              .Append(z.Imaginary >= 0 ? "+" : "")
              .Append(z.Imaginary.ToString("G10", CultureInfo.InvariantCulture))
              .Append('j');
            if (p.IsHole) sb.Append("   ; hole");
            sb.AppendLine();
        }
        return sb.ToString();
    }

    // ── Copy termination set (§7.8) ───────────────────────────────────────────

    /// <summary>
    /// §7.8's <i>Copy termination set</i>: a <c>Tuner</c> pair ready to paste into a schematic's
    /// <c>.cnl</c>.
    ///
    /// <para><b>A Tuner is right HERE and wrong in the exported testbench</b>, and the difference is
    /// worth stating because §7.8 asks for a Tuner in both places. A Tuner pasted into a schematic is
    /// driven by the loadpull engine, which sets its role, its tone and its drive; a Tuner in a plain
    /// <c>type=hb</c> netlist is driven by nothing, so it presents Z[1] flat at every harmonic and
    /// emits no drive at all. See <see cref="ExportTestbench"/>.</para>
    /// </summary>
    public static string CopyTerminationSet(TerminationSet terminations, BiasSpec bias)
    {
        ArgumentNullException.ThrowIfNull(terminations);

        var sb = new StringBuilder();
        sb.AppendLine("; harmonicaRF — termination set (harmonicarf.md §7.8).");
        sb.AppendLine("; Paste into a .cnl beside the DUT; the loadpull engine assigns the roles.");
        sb.Append(TunerLine("Src",  TerminationSide.Source, terminations, bias.Vgs ?? 0.0));
        sb.Append(TunerLine("Load", TerminationSide.Load,   terminations, bias.Vds));
        return sb.ToString();
    }

    private static string TunerLine(string name, TerminationSide side,
                                    TerminationSet t, double vbias)
    {
        var sb = new StringBuilder();
        sb.Append("Tuner:").Append(name).Append("  ")
          .Append(side == TerminationSide.Source
                      ? HarmonicaNetlist.SourcePlane : HarmonicaNetlist.LoadPlane)
          .Append(" 0 ");

        foreach (int band in t.MarkedBands(side).OrderBy(b => b))
            sb.Append("  Z[").Append(band).Append("]=").Append(Complex_(t.Z(side, band)));

        // The unmarked bands' near-short is D9's own value, written explicitly rather than left to a
        // default — a Tuner's Zdefault is 50 Ω, so omitting it would silently change the circuit.
        sb.Append("  Zdefault=").Append(Num(TerminationSet.UnmarkedBandOhms))
          .Append("  BiasTee=on  Vbias=").Append(Num(vbias));
        return sb.AppendLine().ToString();
    }

    /// <summary>A complex value in the form the <c>.cnl</c> expression parser reads, with NO spaces —
    /// the generic instance-line parser splits on whitespace and would read the tail as nets.</summary>
    private static string Complex_(Complex z)
        => z.Imaginary == 0 ? Num(z.Real) : $"complex({Num(z.Real)},{Num(z.Imaginary)})";

    // ── Export testbench (R-h7-13) ────────────────────────────────────────────

    /// <summary>
    /// R-h7-13 — a runnable <c>.cnl</c> reproducing the current harmonicaRF state, checkable through
    /// the reference engine (§9).
    ///
    /// <para><b>The terminations are NOT written as a <c>Tuner</c> pair, and that is a departure from
    /// §7.8 with a measured reason.</b> A <c>Tuner</c> is inert under a plain <c>type=hb</c> run:
    /// nothing in <c>HbEngine</c> calls <c>SetRole</c>, <c>SetTone</c> or <c>SetSourceDrive</c> —
    /// those are the <b>loadpull</b> engine's, and the CLI has no loadpull verb. A Tuner-pair export
    /// would therefore present Z[1] at every harmonic and emit no drive whatsoever, i.e. it would run
    /// and be wrong. <c>P1Tone</c> and <c>PnTone</c> are the two components <c>HbEngine</c> DOES give
    /// a band ruler to, so they are what the export uses:</para>
    ///
    /// <list type="bullet">
    /// <item><b>Source</b> — a <c>P1Tone</c> at the available power of the operating point, with
    /// <c>Z[k]</c> per marked band. Its drive is <c>|Vs| = √(8·Pavl·Re Z(1))</c>, byte-for-byte the
    /// rule <c>HarmonicaContext.DriveVolts</c> applies.</item>
    /// <item><b>Load</b> — a <c>PnTone</c> declaring NO tones. Its drive phasor is then zero at every
    /// spectral line while its per-band <c>Z[k]</c> is live, which is exactly "a per-harmonic passive
    /// termination" and is the only way to spell one in an HB netlist today.</item>
    /// <item><b>The DC block</b> is written explicitly, in series, at each plane. §6.2 folds it into
    /// the termination admittance rather than the netlist, so the exported circuit has to state it or
    /// the two are not the same circuit — and at DC it is what keeps the termination from shorting
    /// the bias supply.</item>
    /// </list>
    ///
    /// <para>The bias supplies, the chokes, the embedding stack and the DUT are
    /// <see cref="HarmonicaNetlist"/>'s own text, unchanged.</para>
    /// </summary>
    /// <param name="pavlDbm">
    /// The drive to reproduce — the frame's operating point. This is what makes the export comparable
    /// to a frame at all: intrinsic impedance and every FOM are drive-dependent.
    /// </param>
    public static string ExportTestbench(CircuitModel model, TerminationSet terminations,
                                         double pavlDbm)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentNullException.ThrowIfNull(terminations);

        var sb = new StringBuilder();
        sb.AppendLine("; ================================================================");
        sb.AppendLine("; harmonicaRF — exported testbench (harmonicarf.md §7.8).");
        sb.AppendLine(";");
        sb.AppendLine("; Reproduces one harmonicaRF operating point through the ordinary HB path, so");
        sb.AppendLine("; every finding is checkable by the reference engine:");
        sb.AppendLine(";     dotnet run --project src/Cli -- hb <this file>");
        sb.AppendLine("; ================================================================");
        sb.AppendLine();
        sb.Append("RFfreq = ").AppendLine(Num(model.Settings.FrequencyHz));
        sb.AppendLine();

        // The open-port netlist, verbatim: the DUT, the embedding stack and the ideal bias.
        sb.AppendLine(HarmonicaNetlist.Build(model).Text);

        sb.AppendLine("; ── the terminations (§6.2 closes these algebraically; here they are stamped) ──");
        sb.Append(SourceTermination(model, terminations, pavlDbm));
        sb.Append(LoadTermination(model, terminations));
        sb.AppendLine();

        sb.Append("analysis HB1 type=hb Tone=RFfreq MaxHarm=")
          .Append(model.Settings.HarmonicCount)
          .Append(" Tol=").Append(Num(model.Settings.Tol))
          .Append(" MaxIter=").Append(model.Settings.MaxIter);
        if (model.Settings.GuardHarmonic > 0)
            sb.Append(" GuardHarmonic=").Append(model.Settings.GuardHarmonic);
        if (model.Settings.Lambda != 1.0)
            sb.Append(" Lambda=").Append(Num(model.Settings.Lambda));
        sb.AppendLine();

        return sb.ToString();
    }

    private static string SourceTermination(CircuitModel model, TerminationSet t, double pavlDbm)
    {
        var sb = new StringBuilder();
        sb.Append("C:CBLKS  ").Append(HarmonicaNetlist.SourcePlane).Append(" n_srcz  C=")
          .AppendLine(Num(model.Settings.DcBlockFarads));

        sb.Append("P1Tone:PIN  n_srcz 0  Freq=").Append(Num(model.Settings.FrequencyHz))
          .Append("  Pavl=").Append(Num(pavlDbm))
          .Append("  Z=").Append(Num(TerminationSet.UnmarkedBandOhms));
        AppendBands(sb, t, TerminationSide.Source);
        return sb.AppendLine().ToString();
    }

    private static string LoadTermination(CircuitModel model, TerminationSet t)
    {
        var sb = new StringBuilder();
        sb.Append("C:CBLKL  ").Append(HarmonicaNetlist.LoadPlane).Append(" n_ldz  C=")
          .AppendLine(Num(model.Settings.DcBlockFarads));

        // A PnTone with no Freq[i] declares no tones, so its drive phasor is zero at every spectral
        // line while its per-band Z[k] is live. That is a per-harmonic passive termination.
        sb.Append("PnTone:PLOAD  n_ldz 0  Z=").Append(Num(TerminationSet.UnmarkedBandOhms));
        AppendBands(sb, t, TerminationSide.Load);
        return sb.AppendLine().ToString();
    }

    private static void AppendBands(StringBuilder sb, TerminationSet t, TerminationSide side)
    {
        foreach (int band in t.MarkedBands(side).OrderBy(b => b))
            sb.Append("  Z[").Append(band).Append("]=").Append(Complex_(t.Z(side, band)));
    }
}
