using System.Numerics;

namespace CircuitRF.Core.Devices;

/// <summary>
/// The passive-intermod overlay (brief-sys-4): everything that turns a frequency-flat ideal S-block
/// into a memoryless nonlinearity generating a stated third-order product, derived once at
/// construction from the block's own S-matrix.
///
/// <para><b>The form.</b> A nonlinearity in this repository is <c>Evaluate(v)</c> — memoryless in
/// the port voltages — so a PIM-capable block must be writable as <c>i = f(v)</c>. Writing
/// <c>T = (I + S)⁻¹</c>, <c>G = diag(1/√Z0_p)</c> and <c>ψ(x) = Vsat·tanh(x/Vsat) − x</c>:</para>
/// <code>
///   Y = G·T·(I − S)·G            the block's admittance matrix — the linear half, unchanged
///   R = Re(T·G)                  port voltages → the wave INCIDENT on each port
///   N = −2·G·T·S                 the distortion → port currents
///
///   i(v) = Y·v  +  N·ψ(R·v)
/// </code>
/// <para>with the complex halves carried by the weighting mechanism: <c>H[0] = 1</c> takes
/// <c>Re(Y)</c> and <c>Re(N)</c>, <c>H[2](ω) = j·sign(ω)</c> takes <c>Im(Y)</c> and <c>Im(N)</c>.
/// That second bucket is what lets a block with a genuinely complex S — the 90° hybrid — host PIM at
/// all, and it vanishes at ω = 0 as a frequency-domain factor must.</para>
///
/// <para><b>Why the incident wave and not the port voltage, which is what brief-sys-4 specifies.</b>
/// The brief's form is <c>i = Y·φ(v)</c> — the limiter on the port voltages, then the linear map.
/// <b>That form generates no PIM at all on an ideal circulator, and puts what it does generate at
/// the wrong port.</b> Both are arithmetic, not opinion. Under matched terminations the third-order
/// deviation that escapes a block is</para>
/// <code>
///   δb = −(1/(3·Vsat²))·(I − S)·v⁽³⁾        for the brief's port-voltage form
/// </code>
/// <para>and for the ideal circulator driven at port 1, <c>v = √Z0·a·(e₁ + e₂)</c> — the port-1 and
/// port-2 voltages are EQUAL, because a lossless circulator carries the whole wave from one to the
/// other. <c>(I − S)</c> annihilates that vector at port 2 exactly, so the product at port 2 is
/// zero; the residue comes out at port 3, the ISOLATED port. Measured, not argued: a 3×3 solve of
/// the brief's own equations gives <c>b = [8.33, 0, −8.33]</c>. The same cancellation makes an
/// attenuator's PIM vanish as its loss goes to zero, which is precisely the <c>Loss = 0</c>
/// standalone generator the brief holds up as the reason to put PIM on the attenuator.</para>
///
/// <para>Applying the limiter to the wave INCIDENT on each port instead — which is what a nonlinear
/// contact in a connector actually sees — removes both problems, because it is the same statement a
/// datasheet makes: <c>b = S·φ(a)</c>, distortion generated where the signal arrives and then
/// routed by the block's own S. The closed form falls out with no matrix inverse left in it:</para>
/// <code>
///   δb = −(1/(3·Vsat²))·S·x⁽³⁾ ,   x = R·v  ( = a exactly, whenever S is real)
/// </code>
/// <para>so a product generated by two tones into port 1 leaves port 2 through <c>S21</c> and port 3
/// through <c>S31</c> — isolated by the block's own isolation, which is brief-sys-4's own routing
/// gate, met by construction rather than by tuning.</para>
///
/// <para><b>R is exact wherever it matters and a projection where it cannot be.</b>
/// <c>x = R·v = Re(T·G)·v</c> is the incident wave EXACTLY whenever S is real — the attenuator, the
/// circulator, the in-phase and 180° couplers, every block whose PIM the owner asked for except
/// one. For the quadrature coupler <c>T</c> is complex and the true incident wave is a Hilbert
/// transform of the port voltages, which no memoryless function can compute; the real part is the
/// memoryless projection of it. Nothing observable is left approximate by that: the routing is
/// carried by <c>N</c> and stays exact (the isolated port of a hybrid with PIM on measures zero),
/// and the LEVEL is calibrated below against whatever R actually is.</para>
///
/// <para><b>Y must exist, and the constructor checks.</b> <c>T = (I + S)⁻¹</c> is where the refusal
/// lives, and it is not a formality — <c>det(I + S) = 0</c> exactly for a matched 0 dB attenuator
/// (an ideal through has no Y at all) and for a 0 dB coupler. See <see cref="Build"/>.</para>
/// </summary>
public sealed class PimOverlay
{
    private readonly double[,] _y0, _y2, _n0, _n2, _r;
    private readonly double    _vsat;
    private readonly int       _n;

    private PimOverlay(double[,] y0, double[,] y2, double[,] n0, double[,] n2, double[,] r,
                       double vsat, bool hasQuadrature)
    {
        _y0 = y0; _y2 = y2; _n0 = n0; _n2 = n2; _r = r;
        _vsat = vsat;
        _n = y0.GetLength(0);
        HasQuadrature = hasQuadrature;
    }

    /// <summary>
    /// Whether any entry of <c>Im(Y)</c> or <c>Im(N)</c> is non-zero — i.e. whether this block needs
    /// the <c>H[2](ω) = j·sign(ω)</c> bucket at all. False for every real-S block, which is what
    /// keeps them on the plain conductive fast path with no weighted term to carry.
    /// </summary>
    public bool HasQuadrature { get; }

    /// <summary>
    /// The soft-limit scale, in incident-wave units (√W, since <c>x = R·v</c> is a wave amplitude).
    /// Diagnostic only — no gate reads a level back out of it; they compute the expected dBm from
    /// the dBm the user typed.
    /// </summary>
    public double Saturation => _vsat;

    /// <summary>
    /// At or below this stated product level (dBm) the block is EXACTLY linear and no overlay is
    /// built at all — the same standard as <c>MixerModel</c>'s <c>IIP3</c>: the ideal device takes
    /// the identity path rather than a path that merely rounds to it.
    ///
    /// <para><b>Why −190 and not the family's usual 150.</b> The 150 dB elsewhere in this family is
    /// a SUPPRESSION — a ratio, and 150 dB of it is beyond any part. A PIM figure is an ABSOLUTE
    /// level, and −150 dBm is a perfectly ordinary number for a good passive part to claim, so
    /// borrowing that threshold would silently switch off a specification a user meant. −190 sits
    /// 10 dB inside the −200 dBm default, exactly as <c>MixerModel</c>'s 90 dBm sits 10 dB inside
    /// its 100 dBm one, and 10 dB of a sentinel is nobody's real number.</para>
    /// </summary>
    public const double PimOffDbm = -190.0;

    /// <summary>Whether a stated product level means "there is no intermod here".</summary>
    public static bool IsOff(double pimDbm) => pimDbm <= PimOffDbm;

    /// <summary>
    /// Derives the overlay for a block whose flat S-matrix is <paramref name="s"/>, refusing by name
    /// when the block cannot host a memoryless nonlinearity at all.
    /// </summary>
    /// <param name="s">The block's frequency-flat S-matrix.</param>
    /// <param name="z0">Per-port reference impedance, ohms.</param>
    /// <param name="pimDbm">The stated third-order product level, dBm, at the output port.</param>
    /// <param name="pimPcDbm">Power per carrier the level above was stated at, dBm.</param>
    /// <param name="inPort">Port the two carriers enter — index, 0-based.</param>
    /// <param name="outPort">Port the product level is stated at — index, 0-based.</param>
    /// <param name="blockName">The block's own name, for the refusals.</param>
    public static PimOverlay Build(Complex[,] s, IReadOnlyList<double> z0,
                                   double pimDbm, double pimPcDbm,
                                   int inPort, int outPort, string blockName)
    {
        int n = z0.Count;

        // T = (I + S)⁻¹. The ONE structural refusal: an ideal through (a matched 0 dB attenuator)
        // and a 0 dB coupler are permutation-like matrices with −1 in their spectrum, so I + S is
        // singular EXACTLY and the block has no Y at all. Refusing here names the block; a NaN born
        // inside a Newton iteration names nothing.
        var ipS = new Complex[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            ipS[p, q] = (p == q ? Complex.One : Complex.Zero) + s[p, q];

        var t = Invert(ipS)
            ?? throw new InvalidOperationException(
                $"{blockName}: passive intermod needs an S-matrix this block can write as a "
              + $"memoryless i = f(v), and this one cannot — det(I + S) is zero, so the block has "
              + $"no admittance matrix at all. A perfectly matched 0 dB attenuator is an ideal "
              + $"through and a 0 dB coupler is a swap; both are wires, and a wire has no Y. Give "
              + $"the block a small insertion loss (0.01 dB is electrically invisible) or a finite "
              + $"return loss, and the same PIM specification then works.");

        var g    = new double[n];                       // diag(1/√Z0)
        var gInv = new double[n];                       // diag(√Z0)
        for (int p = 0; p < n; p++) { gInv[p] = Math.Sqrt(z0[p]); g[p] = 1.0 / gInv[p]; }

        // Y = G·T·(I − S)·G   and   N = −2·G·T·S
        var imS = new Complex[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            imS[p, q] = (p == q ? Complex.One : Complex.Zero) - s[p, q];

        var y = Scale(g, Multiply(t, imS), g);
        var nm = Scale(g, Multiply(t, s), null);
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            nm[p, q] *= -2.0;

        // R = Re(T·G): port voltages → the wave incident on each port. Exact whenever S is real.
        var r = new double[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            r[p, q] = (t[p, q] * g[q]).Real;

        var (y0, y2) = Split(y);
        var (n0, n2) = Split(nm);
        bool quad = AnyNonZero(y2) || AnyNonZero(n2);

        double vsat = Calibrate(s, r, gInv, pimDbm, pimPcDbm, inPort, outPort, blockName);
        return new PimOverlay(y0, y2, n0, n2, r, vsat, quad);
    }

    /// <summary>
    /// Turns the stated product level into the soft-limit scale, by doing the block's own
    /// third-order arithmetic rather than assuming it is a unity-gain box.
    ///
    /// <para>Two carriers of power <c>Pc</c> each enter <paramref name="inPort"/> with every port
    /// matched. The wave the limiter sees at port q is <c>x_q = ρ_q·a</c> with
    /// <c>ρ = R·G⁻¹·(I + S)·e_in</c> and <c>|a|² = 2·Pc</c>, and the product leaving
    /// <paramref name="outPort"/> is <c>δb = −(a³/(4·Vsat²))·Λ</c> with
    /// <c>Λ = Σ_q S[out,q]·|ρ_q|²·ρ_q</c> — the 3/4 being the third-order coefficient a real
    /// two-tone cube carries at 2ω₁ − ω₂. Equating <c>|δb|²/2</c> to the stated level inverts to</para>
    /// <code>
    ///   Vsat² = Pc^(3/2)·|Λ| / (2·√P_im3)
    /// </code>
    /// <para><b>This reduces to brief-sys-4's own one-liner exactly when |Λ| = 1</b> — a unity
    /// transmission with R exact, where ρ = e_in and Λ = S[out,in]. The brief's
    /// <c>IIP3 = (3·PIMPc − PIM)/2</c> then gives <c>Vsat = ½√(2·P_iip3·Z0)</c>, which is this
    /// formula written in volts at a Z0 port. |Λ| is the generalisation the brief's line is missing:
    /// a block that attenuates, splits or projects has to distort correspondingly harder to put the
    /// stated absolute level on its output, and it is not the user's job to know by how much.</para>
    /// </summary>
    private static double Calibrate(Complex[,] s, double[,] r, double[] gInv,
                                    double pimDbm, double pimPcDbm,
                                    int inPort, int outPort, string blockName)
    {
        int n = gInv.Length;

        // ρ = R·G⁻¹·(I + S)·e_in
        var col = new Complex[n];
        for (int q = 0; q < n; q++)
            col[q] = gInv[q] * ((q == inPort ? Complex.One : Complex.Zero) + s[q, inPort]);

        var rho = new Complex[n];
        for (int p = 0; p < n; p++)
        {
            Complex acc = Complex.Zero;
            for (int q = 0; q < n; q++) acc += r[p, q] * col[q];
            rho[p] = acc;
        }

        Complex lambda = Complex.Zero;
        for (int q = 0; q < n; q++)
            lambda += s[outPort, q] * (rho[q].Magnitude * rho[q].Magnitude) * rho[q];

        double mag = lambda.Magnitude;
        if (!double.IsFinite(mag) || mag <= 0.0)
            throw new InvalidOperationException(
                $"{blockName}: this block carries nothing from the port the carriers enter to the "
              + $"port the intermod level is stated at, so no amount of distortion can put a "
              + $"product there. Give the path a transmission — a finite loss, isolation or "
              + $"directivity — or leave PIM at its default.");

        double pc  = 1e-3 * Math.Pow(10.0, pimPcDbm / 10.0);
        double pim = 1e-3 * Math.Pow(10.0, pimDbm   / 10.0);

        double vsatSq = Math.Pow(pc, 1.5) * mag / (2.0 * Math.Sqrt(pim));
        return Math.Sqrt(vsatSq);
    }

    // ── Evaluation ────────────────────────────────────────────────────────────

    /// <summary>
    /// Writes the <c>H[0] = 1</c> bucket — <c>Re(Y)·v + Re(N)·ψ(R·v)</c> and its Jacobian — into the
    /// caller's buffers, and returns the ψ/ψ' work so the quadrature bucket can reuse it rather than
    /// running the limiter twice.
    /// </summary>
    public void EvaluateInto(in PortVoltages v, double[] i, double[,] dg, Span<double> psi, Span<double> dpsi)
    {
        for (int q = 0; q < _n; q++)
        {
            double x = 0.0;
            for (int k = 0; k < _n; k++) x += _r[q, k] * v[k];

            double u  = x / _vsat;
            double th = Math.Tanh(u);
            psi[q]  = _vsat * TanhMinusIdentity(u);
            dpsi[q] = -th * th;                       // sech²(u) − 1, written where it cannot cancel
        }

        Accumulate(_y0, _n0, v, psi, dpsi, i, dg);
    }

    /// <summary>The <c>H[2](ω) = j·sign(ω)</c> bucket, from ψ/ψ' already computed.</summary>
    public void EvaluateQuadratureInto(in PortVoltages v, ReadOnlySpan<double> psi, ReadOnlySpan<double> dpsi,
                                       double[] value, double[,] jac)
        => Accumulate(_y2, _n2, v, psi, dpsi, value, jac);

    private void Accumulate(double[,] m, double[,] nm, in PortVoltages v,
                            ReadOnlySpan<double> psi, ReadOnlySpan<double> dpsi,
                            double[] value, double[,] jac)
    {
        for (int p = 0; p < _n; p++)
        {
            double acc = 0.0;
            for (int q = 0; q < _n; q++) acc += m[p, q] * v[q] + nm[p, q] * psi[q];
            value[p] = acc;

            for (int k = 0; k < _n; k++)
            {
                double d = m[p, k];
                for (int q = 0; q < _n; q++) d += nm[p, q] * dpsi[q] * _r[q, k];
                jac[p, k] = d;
            }
        }
    }

    /// <summary>
    /// <c>tanh(u) − u</c>, which IS the whole nonlinearity and is a difference of two nearly equal
    /// numbers at every drive a PIM specification actually describes.
    ///
    /// <para>A part quoted at −110 dBm against +43 dBm carriers has an intercept near 120 dBm, so
    /// <c>u ≈ 3e−4</c> and the answer is ~1e−8 of each term: computing it as written throws away
    /// eight of the sixteen digits, and a stricter specification throws away all of them. The series
    /// <c>−u³/3 + 2u⁵/15 − 17u⁷/315 + 62u⁹/2835</c> has no cancellation in it and is exact to
    /// double precision below |u| = 0.1, where its next term is ~1e−12 of the result.</para>
    ///
    /// <para>ψ' needs no such care: <c>sech²(u) − 1 = −tanh²(u)</c> exactly.</para>
    /// </summary>
    private static double TanhMinusIdentity(double u)
    {
        if (Math.Abs(u) < 0.1)
        {
            double u2 = u * u;
            return u * u2 * (-1.0 / 3.0
                 + u2 * (2.0 / 15.0
                 + u2 * (-17.0 / 315.0
                 + u2 * (62.0 / 2835.0))));
        }
        return Math.Tanh(u) - u;
    }

    // ── Small dense complex helpers (n ≤ 4 here) ──────────────────────────────

    private static Complex[,]? Invert(Complex[,] a)
    {
        int n = a.GetLength(0);
        var m = new Complex[n, 2 * n];
        for (int p = 0; p < n; p++)
        {
            for (int q = 0; q < n; q++) m[p, q] = a[p, q];
            m[p, n + p] = Complex.One;
        }

        // The scale the pivots are judged against: a pivot far below the matrix's own magnitude is
        // a singular I + S, not a small one. 1e-12 relative is the same order the rest of this
        // family gates on, and it separates "an ideal through" from "a 0.01 dB pad", which really
        // does invert.
        double scale = 0.0;
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            scale = Math.Max(scale, a[p, q].Magnitude);
        if (scale <= 0.0) return null;

        for (int c = 0; c < n; c++)
        {
            int best = c;
            for (int p = c + 1; p < n; p++)
                if (m[p, c].Magnitude > m[best, c].Magnitude) best = p;
            if (m[best, c].Magnitude <= 1e-12 * scale) return null;

            if (best != c)
                for (int q = 0; q < 2 * n; q++)
                    (m[c, q], m[best, q]) = (m[best, q], m[c, q]);

            Complex piv = m[c, c];
            for (int q = 0; q < 2 * n; q++) m[c, q] /= piv;

            for (int p = 0; p < n; p++)
            {
                if (p == c) continue;
                Complex f = m[p, c];
                if (f == Complex.Zero) continue;
                for (int q = 0; q < 2 * n; q++) m[p, q] -= f * m[c, q];
            }
        }

        var inv = new Complex[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            inv[p, q] = m[p, n + q];
        return inv;
    }

    private static Complex[,] Multiply(Complex[,] a, Complex[,] b)
    {
        int n = a.GetLength(0);
        var c = new Complex[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
        {
            Complex acc = Complex.Zero;
            for (int k = 0; k < n; k++) acc += a[p, k] * b[k, q];
            c[p, q] = acc;
        }
        return c;
    }

    /// <summary>Left-scales by <paramref name="left"/> and, when given, right-scales by <paramref name="right"/>.</summary>
    private static Complex[,] Scale(double[] left, Complex[,] a, double[]? right)
    {
        int n = a.GetLength(0);
        var c = new Complex[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
            c[p, q] = left[p] * a[p, q] * (right is null ? 1.0 : right[q]);
        return c;
    }

    private static (double[,] Re, double[,] Im) Split(Complex[,] a)
    {
        int n = a.GetLength(0);
        var re = new double[n, n];
        var im = new double[n, n];
        for (int p = 0; p < n; p++)
        for (int q = 0; q < n; q++)
        {
            re[p, q] = a[p, q].Real;
            im[p, q] = a[p, q].Imaginary;
        }
        return (re, im);
    }

    private static bool AnyNonZero(double[,] a)
    {
        foreach (double x in a) if (x != 0.0) return true;
        return false;
    }
}
