// R-em-20 — the .snp carries a provenance stamp, and a stale one is DETECTED rather than silently
// believed. §10.8 is explicit that this is the one failure mode the design introduces (an .snp
// referenced by a schematic can outlive the layout it came from) and that the whole mitigation is a
// header stamp plus a warning.
//
// **Hash the extracted EmProblem, not the raw file bytes.** A cosmetic layout edit — moving a
// silkscreen label, renaming a net, nudging a via — must NOT report staleness, and a change that
// genuinely moves the cross-section must ALWAYS report it. The EmProblem is exactly "everything the
// answer depends on and nothing else", so hashing it makes both halves of that true by construction
// rather than by a heuristic about which edits matter.

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using CircuitRF.Engine.Mom;

namespace CircuitRF.Design.Layout.Em;

/// <summary>The fields of a provenance stamp, parsed back out of an existing <c>.snp</c> header.</summary>
public sealed record EmProvenanceStamp(string GeometryHash, string MeshHash, string PortHash)
{
    public const string Marker         = "circuitRF-EM";
    public const string GeometryPrefix = "circuitRF-EM geometry: ";
    public const string MeshPrefix     = "circuitRF-EM mesh: ";
    public const string PortPrefix     = "circuitRF-EM ports: ";
}

public static class EmSnpProvenance
{
    /// <summary>The header lines to stamp into a freshly written <c>.snp</c>.</summary>
    public static IReadOnlyList<string> BuildHeader(
        EmProblem problem, EmMeshSettings mesh, string setupName, string layoutRef, DateTimeOffset when)
        => BuildHeader(QuasiStaticKernel.KernelName,
                       GeometryHash(problem), MeshHash(mesh), PortHash(problem),
                       setupName, layoutRef, when);

    /// <summary>
    /// D9 — the planar counterpart. <b>A planar run through the same <c>.snp</c> path with no planar
    /// hashes would write a stamp that CANNOT go stale, which is worse than no stamp at all</b>: the
    /// warning §10.8 calls "the one failure mode this design introduces" would simply stay silent
    /// while a schematic went on reading a result the layout no longer produces.
    /// </summary>
    public static IReadOnlyList<string> BuildHeader(
        PlanarProblem problem, PlanarMeshSettings mesh, IReadOnlyList<PlanarPort> ports,
        string setupName, string layoutRef, DateTimeOffset when)
        => BuildHeader(PlanarKernel.KernelName,
                       GeometryHash(problem), MeshHash(mesh), PortHash(ports),
                       setupName, layoutRef, when);

    private static IReadOnlyList<string> BuildHeader(
        string kernelName, string geometry, string mesh, string ports,
        string setupName, string layoutRef, DateTimeOffset when)
        => [
            $"Generated by circuitRF — EM: {kernelName}",
            $"circuitRF-EM setup: {setupName}",
            $"circuitRF-EM layout: {layoutRef}",
            $"circuitRF-EM written: {when.ToString("u", CultureInfo.InvariantCulture)}",
            EmProvenanceStamp.GeometryPrefix + geometry,
            EmProvenanceStamp.MeshPrefix     + mesh,
            EmProvenanceStamp.PortPrefix     + ports,
            "circuitRF-EM: re-running the EM setup rewrites this file. If circuitRF reports it as " +
            "stale, the layout's cross-section changed after this file was written.",
        ];

    /// <summary>
    /// The stackup identity, conductor outlines and length — everything the extracted cross-section
    /// consists of. Deliberately excludes port reference impedances and mesh settings, which get
    /// their own lines so a mismatch can say WHICH of the three moved.
    /// </summary>
    public static string GeometryHash(EmProblem p)
    {
        var sb = new StringBuilder();
        sb.Append("L=").Append(R(p.LengthMeters)).Append('|');
        foreach (var c in p.Conductors)
        {
            sb.Append("C:").Append(c.Name).Append(':').Append(R(c.SigmaSm)).Append(':');
            foreach (var pt in c.Outline) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
            sb.Append('|');
        }
        foreach (var r in p.Regions)
            sb.Append("R:").Append(R(r.YBottom)).Append(':').Append(R(r.YTop)).Append(':')
              .Append(R(r.Material.EpsR)).Append(':').Append(R(r.Material.TanD)).Append(':')
              .Append(R(r.Material.MuR)).Append('|');
        sb.Append("G:").Append(p.Ground is null ? "none" : R(p.Ground.Y) + ":" + R(p.Ground.SigmaSm));
        return Sha(sb.ToString());
    }

    public static string MeshHash(EmMeshSettings m)
        => Sha($"{m.MinCellsAcrossWidth}|{m.EdgeCells}|{R(m.EdgeFractionOfWidth)}|" +
               $"{R(m.EdgeGrowthRatio)}|{R(m.TruncationHeights)}|{m.TruncationTailCells}");

    public static string PortHash(EmProblem p)
    {
        var sb = new StringBuilder();
        foreach (var port in p.Ports)
            sb.Append(port.Number).Append(':').Append(port.Conductor).Append(':')
              .Append(port.ReferenceConductor ?? "gnd").Append(':')
              .Append(R(port.Z0.Real)).Append(',').Append(R(port.Z0.Imaginary)).Append('|');
        return Sha(sb.ToString());
    }

    // ── D9: the planar hashes ─────────────────────────────────────────────────────────────────
    //
    // Same rule as kernel A's, applied to the other problem type: hash EXACTLY what the answer
    // depends on. For a planar run that is the conductor artwork in metres, the slab, and the
    // sweep's top frequency (which is what sizes the mesh, R-msh-3) — plus the mesh controls and the
    // ports, each on their own line so a mismatch can still say WHICH of the three moved.

    public static string GeometryHash(PlanarProblem p)
    {
        var sb = new StringBuilder();
        sb.Append("F=").Append(R(p.MaxFrequencyHz)).Append('|');
        sb.Append("S:").Append(R(p.Slab.HeightM)).Append(':')
          .Append(R(p.Slab.Material.EpsR)).Append(':')
          .Append(R(p.Slab.Material.TanD)).Append(':')
          .Append(R(p.Slab.Material.MuR)).Append('|');

        // L9d — the general MEDIUM and each level's own z, or the answer changes with nothing the
        // hash can see. Before L9d there was one level on one slab and the slab line above said all
        // of it; a two-level problem that keeps the same artwork and moves a spacer is a different
        // structure, and staleness has to notice.
        if (p.MediumStack is { } ms)
        {
            sb.Append("M:").Append(R(ms.Bottom.Material.EpsR)).Append(':')
              .Append(R(ms.Top.Material.EpsR)).Append(':');
            foreach (var ml in ms.Layers)
                sb.Append(R(ml.ThicknessM)).Append(',').Append(R(ml.Material.EpsR)).Append(',')
                  .Append(R(ml.Material.TanD)).Append(',').Append(R(ml.Material.MuR)).Append(';');
            sb.Append('|');
        }

        foreach (var via in p.ViaList)
        {
            sb.Append("V:").Append(via.LowerLayerIndex).Append("->").Append(via.UpperLayerIndex)
              .Append(':').Append(R(via.SigmaSm)).Append(':');
            foreach (var poly in via.Polygons)
                foreach (var pt in poly.Outer) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
            sb.Append('|');
        }

        for (int li = 0; li < p.Layers.Count; li++)
        {
            var layer = p.Layers[li];
            sb.Append("L:").Append(layer.Name).Append(':').Append(R(layer.SigmaSm)).Append(':')
              .Append(R(layer.ThicknessM)).Append(':').Append(R(p.LevelZ(li))).Append('|');
            foreach (var poly in layer.Polygons)
            {
                foreach (var pt in poly.Outer) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
                sb.Append('/');
                foreach (var hole in poly.HoleRings)
                {
                    foreach (var pt in hole) sb.Append(R(pt.X)).Append(',').Append(R(pt.Y)).Append(';');
                    sb.Append('/');
                }
                sb.Append('|');
            }
        }
        return Sha(sb.ToString());
    }

    /// <summary>
    /// <b>The BOUNDARY-CELL model is in the hash, and leaving it out would have been the exact
    /// staleness failure R-em-20 exists to prevent.</b> A staircased disc and a conformal disc are
    /// different geometry, so an <c>.snp</c> produced with one boundary model is not current for the
    /// other — and without this term the stamp would go on saying it was, silently. One line, and
    /// easy to forget.
    ///
    /// <para><b><see cref="PlanarMeshSettings.MeshFrequencyHz"/> is in it for exactly the same
    /// reason.</b> An <c>.snp</c> produced with the mesh sized at 10 GHz is not current for one
    /// sized at 20 GHz — different cells, different unknowns, different numbers — and the hash is
    /// the only thing that can say so. One more line, equally easy to forget.</para>
    ///
    /// <para><b><see cref="PlanarMeshSettings.MinCellsAcrossConductor"/> too</b> (2026-09-09) — it
    /// sets the transverse pitch directly, so it changes the cells, the unknowns and the answer.
    /// <b>Appended at the END and only when it is off its default</b>, so every <c>.snp</c> stamped
    /// before this control existed keeps the hash it already carries and does not read as stale.</para>
    ///
    /// <para><b><see cref="PlanarMeshSettings.CurrentModel"/> too</b> (2026-09-09 as the
    /// transmission-line boolean, 2026-09-10 as ANT-3's three-way) — it changes both pitches, so it
    /// changes the cells, the unknowns and the answer more than any other mesh control does.
    /// <b>Appended at the END and only when it is off its default</b>, for the same reason.</para>
    ///
    /// <para><b>ANT-3 kept the transmission-line term's exact BYTES — <c>|tline=True</c> — rather
    /// than re-spelling it as the enum.</b> That value's meaning did not change, only its name in
    /// C#, so an <c>.snp</c> stamped under the boolean must go on reading as current; a tidier
    /// <c>|model=TransmissionLine</c> would have marked every one of them stale for no reason a user
    /// could see. The new value gets its own term.</para>
    ///
    /// <para><b><see cref="PlanarMeshSettings.DetailFloorDivisor"/> too</b> (ANT-2, 2026-09-10) — it
    /// decides which drawn geometry is allowed to set the pitch, so it changes the mesh and therefore
    /// the answer. <b>Appended at the END and ALWAYS, which breaks the omit-at-default rule above on
    /// purpose.</b> That rule exists so a <c>.snp</c> stamped before a control existed keeps the hash
    /// it carries, and it is sound for every control whose default reproduces the older behaviour —
    /// which is all of them so far. This one's default is ON. A file stamped before ANT-2 describes a
    /// mesh built with NO detail floor, and on any artwork carrying sub-λ_g/200 detail that is a
    /// different mesh; omitting the divisor at its default would leave such a file reading as current
    /// while describing a result the tool can no longer reproduce, which is precisely what this field
    /// exists to prevent. So every pre-ANT-2 planar <c>.snp</c> reads as stale once, correctly.</para>
    /// </summary>
    public static string MeshHash(PlanarMeshSettings m)
        => Sha($"{m.Auto}|{m.CellsPerWavelength}|{m.EdgeMesh}|{m.EdgeCells}|{m.BoundaryCells}|" +
               $"{(m.MeshFrequencyHz is { } f ? R(f) : "auto")}" +
               (m.MinCellsAcrossConductor == PlanarMeshSettings.DefaultMinCellsAcrossConductor
                    ? "" : $"|across={m.MinCellsAcrossConductor}") +
               (m.CurrentModel == PlanarCurrentModel.TransmissionLine ? "|tline=True" : "")
             + (m.CurrentModel == PlanarCurrentModel.Sheet ? "|sheet=True" : "")
             + $"|detail={m.DetailFloorDivisor}");

    /// <summary>
    /// A port's identity for staleness purposes is its number, its POSITION, its inferred side and
    /// its reference impedance. Position is in because moving a port label to the other end of the
    /// conductor changes the answer completely and changes nothing else the other two hashes see.
    /// </summary>
    public static string PortHash(IReadOnlyList<PlanarPort> ports)
    {
        var sb = new StringBuilder();
        foreach (var p in ports)
        {
            sb.Append(p.Number).Append(':').Append(p.Side).Append(':').Append(p.LayerIndex).Append(':')
              .Append(R(p.Location.X)).Append(',').Append(R(p.Location.Y)).Append(':')
              .Append(R(p.Z0.Real)).Append(',').Append(R(p.Z0.Imaginary)).Append(':')
              .Append(p.Reference);

            // ── THE PORT TYPE IS PART OF THE ANSWER, AND IT IS APPENDED ONLY WHEN IT IS NOT THE
            //    DEFAULT — the same omit-at-default rule the `.cem` itself follows, for a reason
            //    that is specific to a HASH rather than cosmetic.
            //
            // Changing an edge port into an internal delta gap moves the excitation and turns
            // de-embedding off for it, so an `.snp` written under one type is emphatically not
            // current for the other: leaving it out would be exactly the staleness failure R-em-20
            // exists to prevent. But appending it unconditionally would change the hash of every
            // all-edge port set, i.e. of every `.snp` this application has ever written — reporting
            // a one-time false staleness on files nothing has actually invalidated. Appending it
            // only when a port is internal makes the pre-existing case bit-identical and still moves
            // the hash the moment any port's type does.
            if (p.Kind != PlanarPortKind.Edge) sb.Append(":K=").Append(p.Kind);

            sb.Append('|');
        }
        return Sha(sb.ToString());
    }

    /// <summary>Reads a stamp back out of a <c>.snp</c>'s header comments. Null when the file is not
    /// circuitRF-EM-stamped (a hand-written or third-party Touchstone), which is not staleness —
    /// there is simply nothing to compare against.</summary>
    public static EmProvenanceStamp? TryRead(string snpPath)
    {
        if (!File.Exists(snpPath)) return null;
        string? geo = null, mesh = null, ports = null;
        try
        {
            foreach (var raw in File.ReadLines(snpPath))
            {
                string line = raw.TrimStart();
                if (line.StartsWith('#')) break;          // the option line ends the header
                if (!line.StartsWith('!')) continue;
                line = line[1..].Trim();
                if (line.StartsWith(EmProvenanceStamp.GeometryPrefix, StringComparison.Ordinal))
                    geo = line[EmProvenanceStamp.GeometryPrefix.Length..].Trim();
                else if (line.StartsWith(EmProvenanceStamp.MeshPrefix, StringComparison.Ordinal))
                    mesh = line[EmProvenanceStamp.MeshPrefix.Length..].Trim();
                else if (line.StartsWith(EmProvenanceStamp.PortPrefix, StringComparison.Ordinal))
                    ports = line[EmProvenanceStamp.PortPrefix.Length..].Trim();
            }
        }
        catch (IOException) { return null; }

        return geo is null || mesh is null || ports is null
            ? null
            : new EmProvenanceStamp(geo, mesh, ports);
    }

    /// <summary>
    /// Compares an existing <c>.snp</c>'s stamp against what a run would produce NOW. Returns null
    /// when there is nothing to warn about (no file, no stamp, or everything matches).
    /// </summary>
    public static string? DescribeStaleness(
        string snpPath, EmProblem problem, EmMeshSettings mesh)
        => Compare(snpPath, GeometryHash(problem), MeshHash(mesh), PortHash(problem),
                   "the cross-section geometry", "the port reference impedances");

    /// <summary>D9 — the planar counterpart, so a planar run's stamp can go stale at all.</summary>
    public static string? DescribeStaleness(
        string snpPath, PlanarProblem problem, PlanarMeshSettings mesh, IReadOnlyList<PlanarPort> ports)
        => Compare(snpPath, GeometryHash(problem), MeshHash(mesh), PortHash(ports),
                   "the layout geometry", "the ports");

    private static string? Compare(
        string snpPath, string geometry, string mesh, string ports,
        string geometryLabel, string portLabel)
    {
        var stamp = TryRead(snpPath);
        if (stamp is null) return null;

        var changed = new List<string>();
        if (stamp.GeometryHash != geometry) changed.Add(geometryLabel);
        if (stamp.MeshHash     != mesh)     changed.Add("the mesh settings");
        if (stamp.PortHash     != ports)    changed.Add(portLabel);
        if (changed.Count == 0) return null;

        return $"'{Path.GetFileName(snpPath)}' was written from a different setup — " +
               $"{string.Join(" and ", changed)} changed since. Any schematic referencing it was " +
               "using stale s-parameters; this run has just rewritten it.";
    }

    private static string R(double v) => v.ToString("R", CultureInfo.InvariantCulture);

    private static string Sha(string s)
        => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s)))[..16].ToLowerInvariant();
}
