#!/usr/bin/env python3
"""Regenerates the Power Rail example's board.

IT WRITES THE ARTWORK AND NOTHING ELSE (brief-authored-board-3 R-ab3-4).  It used to write the
IPC-D-356 netlist and the placement table beside it, because the three files MUST agree and
hand-editing three files to stay in step is how that goes wrong silently.  Those two are now
PROJECTED from this `.clay` by circuitRF itself:

    dotnet run --project src/Cli -- netlist "examples/Power Rail/Sensor board/layout/Board.clay" \
        --ipc      "examples/Power Rail/Sensor board/layout/Board.ipc" \
        --placement "examples/Power Rail/Sensor board/layout/Board.placement.csv"

One invocation, one projection, two files that cannot disagree — and half of the audit this file
used to perform became STRUCTURALLY IMPOSSIBLE with it: a netlist projected from the lands cannot
name a pad that is not under one.  The other half is a real geometric check about the artwork and
stays right here, where the artwork is written.

THE LANDS ARE NOT DRAWN HERE.  Every part is an INSTANCE of a footprint cell under
`examples/Power Rail/footprints/`, and this script READS those cells for its pad rectangles rather
than computing an IPC-7351B land pattern of its own — circuitRF already has exactly one of those
(`ChipLandPatternGenerator`), the cells were generated by it, and a second implementation here would
be free to drift from the one the application places.  So the pad geometry below is measured off the
same artwork the board draws, which is what makes the audit at the foot of this file mean anything.
"""
import json, math, os, sys

MM = 1_000_000          # DBU per mm (DbuPerMicron = 1000)
def mm(v): return int(round(v * MM))

L_TOP, L_GND, L_IN3, L_BOT, L_MASK, L_SILK, L_OUTLINE, L_VIA = 1, 2, 3, 4, 5, 6, 7, 10

VIA_PAD, VIA_DRILL = 0.55, 0.30
ANTI = 0.415746          # anti-pad apothem, as the board's existing three are drawn

BOARD_W, BOARD_H = 30.0, 20.0

root = sys.argv[1]
FOOTPRINTS = os.path.join(root, "footprints")

# ── THE DELIBERATE FAULT ───────────────────────────────────────────────────────────────────────
# The audit's whole value is that it REFUSES, and a refusal nobody has ever seen fire is a refusal
# nobody knows still works.  This environment variable introduces, on purpose, the defect this
# file's docstring names — a power via with no anti-pad under it — so the gate can run this
# generator and assert it wrote nothing.  Off, and absent from every ordinary run.
#
# There used to be a second one, CRF_BREAK_PAD, which moved a netlist pad off its land.  It is gone
# because the defect is: the netlist is projected from the lands now, so a pad that is not under
# one is not a thing this generator can write.
BREAK_ANTIPAD = os.environ.get("CRF_BREAK_ANTIPAD") == "1"

# ── the footprint cells ────────────────────────────────────────────────────────────────────────
# Each is an ordinary cell folder holding one generated land pattern.  What is read out of it is the
# two COPPER pads: their local rectangle, in the cell's own frame, origin at the pattern's centre.

def read_footprint(cell):
    path = os.path.join(FOOTPRINTS, cell, "layout", cell + ".clay")
    view = json.load(open(path))
    pads = {}
    for s in view["Shapes"]:
        if s["Layer"]["Layer"] == L_TOP and s.get("Pin") in ("1", "2"):
            pads[s["Pin"]] = (s["X1"] / MM, s["Y1"] / MM, s["X2"] / MM, s["Y2"] / MM)
    if set(pads) != {"1", "2"}:
        raise SystemExit(f"{path} does not hold two copper pads named 1 and 2")
    return pads

CELLS = {c: read_footprint(c) for c in ("C0402", "C0603", "C0805", "C7343-31")}

# ── THE THREE PARTS THE BOARD DOES NOT DRAW ────────────────────────────────────────────────────
# The regulator and the two loads are not on this board as artwork: what the board has is the bare
# copper their terminals land on.  Until brief-authored-board-3 that was said only in the `.ipc`,
# which is exactly the gap that series closes — a board circuitRF drew must STATE everything the
# netlist would state, or the netlist cannot be projected from it and the anchors `U1.VDD`,
# `U2.OUT` and `U3.VDD` resolve to nothing.
#
# So each is a PLACEMENT of a cell holding ONE PIN AND NO COPPER.  No copper on purpose: the rail's
# own run already covers that point, and a land drawn here would be a second shape over the same
# metal, which changes what the fast model decomposes into sections and therefore changes the
# answer.  A pin says "this part's terminal is here" and draws nothing, which is precisely the
# claim the netlist record used to make on its own.

def terminal_cell(name, pin):
    """A one-pin, no-copper footprint cell — see the note above."""
    cell = os.path.join(FOOTPRINTS, name)
    os.makedirs(os.path.join(cell, "layout"), exist_ok=True)
    with open(os.path.join(cell, ".ccell"), "w") as f:
        json.dump({"FormatVersion": 1, "Parameters": [], "IsTestBench": False, "NumPorts": 0},
                  f, indent=2)
    with open(os.path.join(cell, "layout", name + ".clay"), "w") as f:
        json.dump({"FormatVersion": 1, "DbuPerMicron": 1000, "DisplayUnit": "Nm", "SnapDbu": 0,
                   "AngleMode": "AnyAngle",
                   "Pins": [{"Name": pin, "X": 0, "Y": 0, "WidthDbu": mm(0.30),
                             "OutwardDeg": 0, "Layer": {"Layer": L_TOP, "Datatype": 0}}],
                   "Shapes": [], "Instances": []}, f, indent=2)
        f.write("\n")

terminal_cell("TERM-OUT", "OUT")
terminal_cell("TERM-VDD", "VDD")

def placed(cell, cx, cy, rot, pin):
    """One pad of a placed instance, in board coordinates: (centre x, centre y, w, h)."""
    x1, y1, x2, y2 = CELLS[cell][pin]
    if rot == 180:
        x1, y1, x2, y2 = -x2, -y2, -x1, -y1
    elif rot != 0:
        raise SystemExit(f"rotation {rot} is not one this generator places")
    return (cx + (x1 + x2) / 2, cy + (y1 + y2) / 2, x2 - x1, y2 - y1)

shapes, instances = [], []

# THE NET IS STAMPED ON THE ROOT'S OWN COPPER, AND THAT IS AN AUTHORING ACT (brief-authored-board-2).
# Nothing in circuitRF writes `Net` automatically — Update Layout does not stamp it — because a
# re-derived name cannot go stale and a stamped one is what a board with no schematic behind it
# needs.  This board has none, so the stamps below are how it says what its copper is, exactly as
# LayoutShapePropertiesViewModel's Net field would for a board drawn by hand.
#
# ONLY THE ROOT'S OWN SHAPES, NEVER A FOOTPRINT CELL'S: a land pattern is one cell shared by every
# placement of it, and a Net stamped inside C0402 would put nine capacitors on one net.  A stated
# name reaches its whole connected piece, so naming the pour names every land that reaches it.
RAIL, GND = "+3V3", "GND"

def rect(x1, y1, x2, y2, layer, net=None):
    shape = {"$type": "Rect", "X1": mm(x1), "Y1": mm(y1), "X2": mm(x2), "Y2": mm(y2),
             "Layer": {"Layer": layer, "Datatype": 0}}
    if net:
        shape["Net"] = net
    shapes.append(shape)

def via(x, y, landing=L_TOP):
    shapes.append({"$type": "Via", "X": mm(x), "Y": mm(y),
                   "PadSize": mm(VIA_PAD), "DrillSize": mm(VIA_DRILL),
                   "LandingLayer": {"Layer": landing, "Datatype": 0},
                   "Layer": {"Layer": L_VIA, "Datatype": 0}})

def octagon(cx, cy, a):
    """The eight-vertex anti-pad the board's existing three are drawn as."""
    t = a * math.tan(math.radians(22.5))
    pts = [(cx + a, cy + t), (cx + a, cy - t), (cx + t, cy - a), (cx - t, cy - a),
           (cx - a, cy - t), (cx - a, cy + t), (cx - t, cy + a), (cx + t, cy + a)]
    out = []
    for px, py in pts:
        out += [mm(px), mm(py)]
    return out

def poly(x1, y1, x2, y2, layer, holes, net=None):
    shape = {"$type": "Poly",
             "Xy": [mm(x1), mm(y1), mm(x2), mm(y1), mm(x2), mm(y2), mm(x1), mm(y2)],
             "Holes": holes,
             "Layer": {"Layer": layer, "Datatype": 0}}
    if net:
        shape["Net"] = net
    shapes.append(shape)

def instance(ref, cell, cx, cy, rot=0):
    """A placed part.  The DESIGNATOR is the placement's, and only its PLACEMENT is stored —
    brief-footprint-4b: the text is derived and the offset left AUTO, so re-pointing a part at a
    bigger case size moves its label clear of the new body instead of leaving it frozen inside."""
    inst = {"CellRef": "../../footprints/" + cell,
            "X": mm(cx), "Y": mm(cy),
            "Rot": {0: "R0", 90: "R90", 180: "R180", 270: "R270"}[rot],
            "MirrorX": False, "Mag": 1.0, "Rows": 1, "Cols": 1, "PitchX": 0, "PitchY": 0,
            "RefDes": ref}
    instances.append(inst)

# ── the board outline ──────────────────────────────────────────────────────────────────────────
# R-fp5-3c: the 30 x 20 mm extent is DRAWN rather than implied by where the copper stops.  On the
# Edge.Cuts layer, which is what the technology's own interchange alias says that layer is.
shapes.append({"$type": "Path",
               "Xy": [mm(0), mm(0), mm(BOARD_W), mm(0), mm(BOARD_W), mm(BOARD_H),
                      mm(0), mm(BOARD_H), mm(0), mm(0)],
               "Width": mm(0.15), "End": "Flush",
               "Layer": {"Layer": L_OUTLINE, "Datatype": 0}})

# ── the regulator end of the rail ──────────────────────────────────────────────────────────────
# U2's output land, the ferrite that is now a part rather than a term in the source, and the run
# that reaches the transition onto BOT.  THE COPPER IS GENUINELY CUT AT FB1: the rail arrives on one
# of its lands and leaves on the other, which is what makes the partition a MEASUREMENT.
RAIL_RUNS = []                                 # the rail's own bare TOP copper, for the audit

def rail_run(x1, y1, x2, y2):
    rect(x1, y1, x2, y2, L_TOP, RAIL)
    RAIL_RUNS.append((x1, y1, x2, y2))

rail_run(0.80, 10.15,  1.40, 10.45)            # U2's output land
rail_run(1.35, 10.225, 3.30, 10.375)           # ... into FB1's upstream land

FB1 = ("FB1", "C0603", 4.40, 10.30, 0)
instance(*FB1)

rail_run(5.20, 10.15, 7.30, 10.45)             # out of FB1's downstream land, to the transition
rail_run(6.15,  8.45, 6.45, 10.45)             # the stub that ties the regulator's IN3 island on

# ── the supply's long way round the connector cut-out ──────────────────────────────────────────
rect(6.90, 10.20, 7.10, 17.10, L_BOT, RAIL)    # down the left side
rect(6.90, 16.90, 24.10, 17.10, L_BOT, RAIL)   # across the top, 0.20 mm wide
rect(23.90, 4.90, 24.10, 17.10, L_BOT, RAIL)   # down the right side

rail_run(21.00, 14.15, 25.40, 14.45)           # U1's land
rail_run(21.00,  4.85, 25.40,  5.15)           # U3's land

# BOTH PORTS ARE DOWNSTREAM OF FB1, and that is a statement about the board rather than an oversight.
# A port upstream of the ferrite would read a genuinely different curve — that is what a series
# element means — but the node up there carries no decoupling at all, so what it would read is the
# regulator's own output inductance: tens of ohms at the top of the band, against a target written
# for a die.  A monitor point judged against somebody else's requirement is not a finding.
RAIL_VIAS = [(7.00, 10.30), (24.00, 14.30), (24.00, 5.00)]
for x, y in RAIL_VIAS:
    via(x, y, L_TOP)
    via(x, y, L_BOT)

# ── the parts ──────────────────────────────────────────────────────────────────────────────────
# Each row: refdes, footprint cell, centre, rotation, the fan-out stub.
#
# STUB IS THE WHOLE OF Q2'S LESSON, in three tiers: a via in the land (C1-C3, C7-C10), a short
# fan-out (C4-C6), and 0.9 mm of trace out to a via of its own (C11-C13).  C1-C6 and C11-C13 are ONE
# purchased part placed nine times, and they are worth three different amounts entirely because of
# this column.
#
# THE FIELD IS LAID OUT BY TIER, and that is not cosmetic either: the three groups are the three
# rows of the mounting-loop table, so a reader can see which part is which on the board without
# selecting anything.  An earlier draft of this field put two parts' lands 0.15 mm apart: the two
# MERGED on TOP, which put the rail and its reference on one piece of copper, and nothing reported
# it — PdnRailRegions calls extra islands ORDINARY on imported artwork, so the board simply solved as
# a shorted one.  The audit at the foot of this file is what now refuses that.
P402  = "CAP-0402-100N-X7R-16V"
P603  = "CAP-0603-1U0-X5R-10V"
P805  = "CAP-0805-10U-X5R-10V"
PBULK = "CAP-BULK-100U-POLY-10V"

FANOUT_W = 0.20        # the fan-out trace's own width

#        ref    part   cell        cx     cy    rot  stub
PARTS = [("C1",  P402,  "C0402",  26.60, 16.20, 0, 0.00),
         ("C2",  P402,  "C0402",  26.60, 12.60, 0, 0.00),
         ("C3",  P402,  "C0402",  26.60, 10.00, 0, 0.00),
         ("C4",  P402,  "C0402",  26.60,  7.40, 0, 0.35),
         ("C5",  P402,  "C0402",  26.60,  5.00, 0, 0.35),
         ("C6",  P402,  "C0402",  26.60,  2.60, 0, 0.35),
         ("C7",  P603,  "C0603",  21.90, 12.80, 0, 0.00),
         ("C8",  P603,  "C0603",  21.90, 10.60, 0, 0.00),
         ("C9",  P805,  "C0805",  21.90,  7.40, 0, 0.00),
         ("C10", PBULK, "C7343-31", 5.00, 7.00, 180, 0.00),
         ("C11", P402,  "C0402",  18.60, 13.60, 0, 0.90),
         ("C12", P402,  "C0402",  18.60, 10.60, 0, 0.90),
         ("C13", P402,  "C0402",  18.60,  7.60, 0, 0.90)]

pads, power_vias, return_vias = [], [], []
lands = []

def land(ref, pin, cell, cx, cy, rot, net):
    px, py, w, h = placed(cell, cx, cy, rot, pin)
    lands.append((ref, pin, px - w / 2, py - h / 2, px + w / 2, py + h / 2, net))
    pads.append((ref, pin, net, px, py, w, h))
    return px, py, w, h

# The ferrite's own two lands are pads in the netlist like any other part's — they are the two
# terminals the rail is CUT at, and a refdes alone would resolve to both of them at once.
land("FB1", "1", "C0603", 4.40, 10.30, 0, "+3V3")
land("FB1", "2", "C0603", 4.40, 10.30, 0, "+3V3")

for ref, pn, cell, cx, cy, rot, stub in PARTS:
    instance(ref, cell, cx, cy, rot)

    px, py, _, _ = land(ref, "1", cell, cx, cy, rot, "+3V3")
    rx, ry, _, _ = land(ref, "2", cell, cx, cy, rot, "GND")

    sign = -1.0 if px < rx else 1.0
    pvx, rvx = px + sign * stub, rx - sign * stub
    if stub > 0:                                    # the fan-out trace out to a via of its own
        rect(min(pvx, px), py - FANOUT_W / 2, max(pvx, px), py + FANOUT_W / 2, L_TOP)
        rect(min(rvx, rx), ry - FANOUT_W / 2, max(rvx, rx), ry + FANOUT_W / 2, L_TOP)

    via(pvx, py, L_TOP)
    via(rvx, ry, L_TOP)
    power_vias.append((pvx, py))
    return_vias.append((rvx, ry))

# The regulator's output and the two loads' supply pins — see `terminal_cell` above.  Placed LAST,
# so the projected placement table lists them after the parts, which is the order a reader expects.
for ref, cell, tx, ty in [("U2", "TERM-OUT", 1.10, 10.30),
                          ("U1", "TERM-VDD", 24.90, 14.30),
                          ("U3", "TERM-VDD", 24.90, 5.00)]:
    instance(ref, cell, tx, ty)

# ── the rail's plane, on IN3 ───────────────────────────────────────────────────────────────────
# TWO islands, and neither bridges the board.  A single pour spanning both ends would put a second
# path in parallel with the 0.20 mm BOT run and delete the finding this example exists for; each of
# these hangs off the rail at ONE place and carries no through current.
LOAD_POUR = (16.80, 1.00, 28.40, 17.40)
REG_POUR  = (3.60,  5.00,  9.40,  9.20)

via(6.30, 8.60, L_TOP)                              # what ties the regulator island to the rail
power_vias.append((6.30, 8.60))

def inside(box, x, y):
    return box[0] <= x <= box[2] and box[1] <= y <= box[3]

for box in (LOAD_POUR, REG_POUR):
    holes = [octagon(x, y, ANTI) for x, y in return_vias if inside(box, x, y)]
    poly(box[0], box[1], box[2], box[3], L_IN3, holes, RAIL)

# ── the reference, on GND ──────────────────────────────────────────────────────────────────────
# One hole per barrel on the rail — the three transitions, every capacitor's power via, and the
# regulator island's.  A missing one is a short, and it is invisible on the picture.
anti_pad_vias = RAIL_VIAS + power_vias
if BREAK_ANTIPAD:
    anti_pad_vias = anti_pad_vias[:-1]              # one power via left shorting the rail to GND
gnd_holes = [octagon(x, y, ANTI) for x, y in anti_pad_vias]
poly(0, 0, BOARD_W, BOARD_H, L_GND, gnd_holes, GND)

# ── THE AUDIT ──────────────────────────────────────────────────────────────────────────────────
# Every check here is one this board has already failed.  The artwork is the input to a DC solve
# that reports a number either way, so a barrel reaching the wrong layer does not announce itself.
def barrel_reaches(layer, x, y, r=VIA_DRILL / 2):
    pts = [(x, y)] + [(x + r * math.cos(i * math.pi / 8), y + r * math.sin(i * math.pi / 8))
                      for i in range(16)]
    for px, py in pts:
        for s in shapes:
            if s["Layer"]["Layer"] != layer:
                continue
            if s["$type"] == "Rect":
                if s["X1"] <= mm(px) <= s["X2"] and s["Y1"] <= mm(py) <= s["Y2"]:
                    return True
            elif s["$type"] == "Poly":
                ring = [(s["Xy"][i], s["Xy"][i + 1]) for i in range(0, len(s["Xy"]), 2)]
                holes = [[(h[i], h[i + 1]) for i in range(0, len(h), 2)] for h in s["Holes"]]
                if _pip(mm(px), mm(py), ring) and not any(_pip(mm(px), mm(py), h) for h in holes):
                    return True
    return False

def _pip(x, y, ring):
    n, inside_, j = len(ring), False, len(ring) - 1
    for i in range(n):
        xi, yi = ring[i]; xj, yj = ring[j]
        if (yi > y) != (yj > y) and x < (xj - xi) * (y - yi) / (yj - yi) + xi:
            inside_ = not inside_
        j = i
    return inside_

problems = []
for x, y in power_vias:
    if barrel_reaches(L_GND, x, y):
        problems.append(f"power via at ({x}, {y}) reaches GND: its anti-pad is missing or cut away")
    if not barrel_reaches(L_IN3, x, y):
        problems.append(f"power via at ({x}, {y}) reaches no rail plane on IN3")
for x, y in return_vias:
    if not barrel_reaches(L_GND, x, y):
        problems.append(f"return via at ({x}, {y}) reaches no reference copper")
    if barrel_reaches(L_IN3, x, y) or barrel_reaches(L_BOT, x, y):
        problems.append(f"return via at ({x}, {y}) reaches the rail: it shorts the supply")

# THE PAD-UNDER-A-LAND CHECK IS GONE AND IT IS NOT AN OVERSIGHT (brief-authored-board-3 R-ab3-4c).
# It existed because the netlist and the artwork were written independently here.  The netlist is
# now PROJECTED from the lands themselves, so a pad it does not stand on is not a thing that can be
# written — the invariant became structural instead of checked.  What remains below is the half
# that is a real statement about geometry, which no writer could make on its own.

# Two lands of different parts that touch are one piece of copper, whatever the netlist says.
for i in range(len(lands)):
    for j in range(i + 1, len(lands)):
        a, b = lands[i], lands[j]
        if a[0] == b[0]:
            continue
        if a[2] < b[4] and b[2] < a[4] and a[3] < b[5] and b[3] < a[5]:
            problems.append(f"{a[0]}.{a[1]} and {b[0]}.{b[1]} overlap on TOP")

# ── AND A VIA'S OWN PAD IS COPPER TOO ──────────────────────────────────────────────────────────
# The check above compares LANDS, and the re-layout found what it does not see: C13's return via
# landed 0.275 mm from its own land and its 0.55 mm pad reached across onto C9's RAIL land.  Two
# nets on one piece of TOP copper, drawn by two shapes neither of which overlaps the other's land —
# and what it produced was not a refusal anywhere, it was a rail whose every anchor resolved into
# one island because the reference plane had joined it through that pad.  So a via pad is checked
# against every land of the OTHER net, and a return via's pad against the rail's own bare copper.
VIA_HALF = VIA_PAD / 2
for net, group in (("+3V3", power_vias), ("GND", return_vias)):
    for vx, vy in group:
        for ref, pin, x1, y1, x2, y2, land_net in lands:
            if land_net == net:
                continue
            if (vx - VIA_HALF < x2 and x1 < vx + VIA_HALF
                    and vy - VIA_HALF < y2 and y1 < vy + VIA_HALF):
                problems.append(f"the {net} via at ({vx:.3f}, {vy:.3f}) has its pad on "
                                f"{ref}.{pin}, which is on {land_net}")
        if net != "GND":
            continue
        for x1, y1, x2, y2 in RAIL_RUNS:
            if (vx - VIA_HALF < x2 and x1 < vx + VIA_HALF
                    and vy - VIA_HALF < y2 and y1 < vy + VIA_HALF):
                problems.append(f"the GND via at ({vx:.3f}, {vy:.3f}) has its pad on the rail's "
                                f"own copper at ({x1}, {y1})-({x2}, {y2})")

# Two barrels closer than two anti-pads and a barrel: each one's clearance eats the other's landing.
#
# CHECKED PER LAYER, and that is the correction this re-layout forced.  A power via's clearance is
# cut in GND and a return via's in IN3, so the two never interact — which is what lets a modern land
# pattern put a via in each land 0.8 mm apart, a spacing the old all-against-all form called a
# defect.  What still is one is two POWER vias close enough to merge their GND anti-pads, or two
# RETURN vias close enough to merge their IN3 ones.
LIMIT = 2 * ANTI + VIA_DRILL / 2
for name, group in (("GND", power_vias + RAIL_VIAS), ("IN3", return_vias)):
    for i in range(len(group)):
        for j in range(i + 1, len(group)):
            d = math.hypot(group[i][0] - group[j][0], group[i][1] - group[j][1])
            if 0 < d < LIMIT:
                problems.append(f"vias at {group[i]} and {group[j]} are {d:.3f} mm apart: "
                                f"their {name} anti-pads merge")

if problems:
    for p in problems:
        print("AUDIT: " + p)
    raise SystemExit("the artwork is not sound; nothing was written")

clay = {"FormatVersion": 1, "DbuPerMicron": 1000, "DisplayUnit": "Um", "SnapDbu": 0,
        "AngleMode": "AnyAngle", "TechRef": "../../tech/pcb-4layer-1p6mm.ctech",
        "Shapes": shapes, "Instances": instances}

with open(os.path.join(root, "Sensor board/layout/Board.clay"), "w") as f:
    json.dump(clay, f, indent=2)
    f.write("\n")

# ── WHAT THIS FILE NO LONGER WRITES ────────────────────────────────────────────────────────────
# The IPC-D-356 netlist and the placement table used to be written here, by hand, in this file's
# own idea of the two formats.  They are projected from the `.clay` above by circuitRF's own
# writers now — see this file's docstring for the one command, which is what the README records
# and what regenerates the two committed files.

print(f"{len(shapes)} shapes, {len(instances)} instances, {len(pads)} pads, "
      f"{len(gnd_holes)} anti-pads on GND")
