// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: 5703fa697810a07d678d2798a7437e5a9370103d1e061959ddb2871982a84e04
struct U {
    row_major float4x4 vp;
    float4 eye;
    float4 clip_;
    uint hover;
    uint sel;
    uint flags;
    uint pad;
    float4 fphase;
    float4 fmode;
    float4 stops[16];
};

struct VI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
};

struct VO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
};

struct PickOut {
    uint id : SV_Target0;
    float4 world : SV_Target1;
};

struct FVI {
    float3 p : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
};

struct FVO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    float3 re : LOC1;
    float3 im : LOC2;
};

cbuffer u : register(b0) { U u; }

struct VertexOutput_vs {
    float3 world : LOC0;
    nointerpolation uint id_1 : LOC1;
    float4 col : LOC2;
    float4 pos : SV_Position;
};

struct FragmentInput_fs_color {
    float3 world_1 : LOC0;
    nointerpolation uint id_2 : LOC1;
    float4 col_1 : LOC2;
    float4 pos_1 : SV_Position;
    bool front_1 : SV_IsFrontFace;
};

struct FragmentInput_fs_line {
    float3 world_2 : LOC0;
    nointerpolation uint id_3 : LOC1;
    float4 col_2 : LOC2;
    float4 pos_2 : SV_Position;
};

struct FragmentInput_fs_pick {
    float3 world_3 : LOC0;
    nointerpolation uint id_4 : LOC1;
    float4 col_3 : LOC2;
    float4 pos_3 : SV_Position;
};

struct VertexOutput_vs_field {
    float3 world_4 : LOC0;
    float3 re_1 : LOC1;
    float3 im_1 : LOC2;
    float4 pos_4 : SV_Position;
};

struct FragmentInput_fs_field {
    float3 world_5 : LOC0;
    float3 re_2 : LOC1;
    float3 im_2 : LOC2;
    float4 pos_5 : SV_Position;
};

bool clipped(float3 w)
{
    bool local_1 = (bool)0;

    uint _e3 = u.flags;
    if (((_e3 & 1u) != 0u)) {
        float4 _e12 = u.clip_;
        float _e18 = u.clip_.w;
        local_1 = ((dot(_e12.xyz, w) + _e18) > 0.0);
    } else {
        local_1 = false;
    }
    bool _e23 = local_1;
    return _e23;
}

float3 highlight(float3 rgb_1, uint id)
{
    float3 c = (float3)0;
    bool local_2 = (bool)0;
    bool local_3 = (bool)0;

    c = rgb_1;
    if ((id != 0u)) {
        uint _e9 = u.hover;
        local_2 = (id == _e9);
    } else {
        local_2 = false;
    }
    bool _e12 = local_2;
    if (_e12) {
        float3 _e13 = c;
        c = lerp(_e13, float3(0.2, 0.9, 1.0), 0.45);
    }
    if ((id != 0u)) {
        uint _e26 = u.sel;
        local_3 = (id == _e26);
    } else {
        local_3 = false;
    }
    bool _e29 = local_3;
    if (_e29) {
        float3 _e30 = c;
        c = lerp(_e30, float3(1.0, 0.35, 1.0), 0.55);
    }
    float3 _e37 = c;
    return _e37;
}

uint naga_f2u32(float value) {
    return uint(clamp(value, 0.0, 4294967000.0));
}

float field_value(float3 re, float3 im)
{
    float c_1 = u.fphase.x;
    float s = u.fphase.y;
    float _e13 = u.fmode.x;
    uint mode = naga_f2u32((_e13 + 0.5));
    if ((mode == 0u)) {
        return sqrt((dot(re, re) + dot(im, im)));
    }
    if ((mode == 1u)) {
        return length(((re * c_1) - (im * s)));
    }
    if ((mode == 2u)) {
        return re.x;
    }
    if ((mode == 3u)) {
        return ((re.x * c_1) - (im.x * s));
    }
    return sqrt(((re.x * re.x) + (im.x * im.x)));
}

float3 colour_map(float t)
{
    float3 rgb_2 = (float3)0;
    uint k = 1u;
    bool local_4 = (bool)0;

    float _e4 = u.fmode.z;
    uint n = naga_f2u32((_e4 + 0.5));
    float4 _e11 = u.stops[0];
    rgb_2 = _e11.yzw;
    uint2 loop_bound = uint2(4294967295u, 4294967295u);
    bool loop_init = true;
    while(true) {
        if (all(loop_bound == uint2(0u, 0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e55 = k;
            k = (_e55 + 1u);
        }
        loop_init = false;
        uint _e16 = k;
        if ((_e16 < n)) {
        } else {
            break;
        }
        {
            uint _e20 = k;
            float4 a = u.stops[(_e20 - 1u)];
            uint _e27 = k;
            float4 b = u.stops[_e27];
            if (!((t <= b.x))) {
                uint _e35 = k;
                local_4 = (_e35 == (n - 1u));
            } else {
                local_4 = true;
            }
            bool _e40 = local_4;
            if (_e40) {
                float w_1 = clamp(((t - a.x) / max((b.x - a.x), 1e-6)), 0.0, 1.0);
                rgb_2 = lerp(a.yzw, b.yzw, w_1);
                break;
            }
        }
    }
    float3 _e58 = rgb_2;
    return _e58;
}

VertexOutput_vs vs(VI v)
{
    VO o = (VO)0;

    float4x4 _e5 = u.vp;
    o.pos = mul(float4(v.p, 1.0), _e5);
    o.world = v.p;
    o.id = v.id;
    o.col = v.col;
    VO _e16 = o;
    const VO vo = _e16;
    const VertexOutput_vs vo_1 = { vo.world, vo.id, vo.col, vo.pos };
    return vo_1;
}

float4 fs_color(FragmentInput_fs_color fragmentinput_fs_color) : SV_Target0
{
    VO i = { fragmentinput_fs_color.pos_1, fragmentinput_fs_color.world_1, fragmentinput_fs_color.id_2, fragmentinput_fs_color.col_1 };
    bool front = fragmentinput_fs_color.front_1;
    float3 rgb = (float3)0;
    bool local = (bool)0;

    const bool _e3 = clipped(i.world);
    if (_e3) {
        discard;
    }
    float3 _e5 = ddx(i.world);
    float3 _e7 = ddy(i.world);
    float3 n_1 = normalize(cross(_e5, _e7));
    float4 _e12 = u.eye;
    float d = abs(dot(n_1, normalize((_e12.xyz - i.world))));
    rgb = (i.col.xyz * (0.3 + (0.7 * d)));
    if (!(front)) {
        uint _e32 = u.flags;
        local = ((_e32 & 2u) != 0u);
    } else {
        local = false;
    }
    bool _e38 = local;
    if (_e38) {
        rgb = (i.col.xyz * 0.8);
    }
    float3 _e43 = rgb;
    const float3 _e45 = highlight(_e43, i.id);
    return float4(_e45, i.col.w);
}

float4 fs_line(FragmentInput_fs_line fragmentinput_fs_line) : SV_Target0
{
    VO i_1 = { fragmentinput_fs_line.pos_2, fragmentinput_fs_line.world_2, fragmentinput_fs_line.id_3, fragmentinput_fs_line.col_2 };
    return float4(i_1.col.xyz, 1.0);
}

PickOut fs_pick(FragmentInput_fs_pick fragmentinput_fs_pick)
{
    VO i_2 = { fragmentinput_fs_pick.pos_3, fragmentinput_fs_pick.world_3, fragmentinput_fs_pick.id_4, fragmentinput_fs_pick.col_3 };
    PickOut o_1 = (PickOut)0;

    const bool _e2 = clipped(i_2.world);
    if (_e2) {
        discard;
    }
    o_1.id = i_2.id;
    o_1.world = float4(i_2.world, 1.0);
    PickOut _e10 = o_1;
    const PickOut pickout = _e10;
    return pickout;
}

VertexOutput_vs_field vs_field(FVI v_1)
{
    FVO o_2 = (FVO)0;

    float4x4 _e5 = u.vp;
    o_2.pos = mul(float4(v_1.p, 1.0), _e5);
    o_2.world = v_1.p;
    o_2.re = v_1.re;
    o_2.im = v_1.im;
    FVO _e16 = o_2;
    const FVO fvo = _e16;
    const VertexOutput_vs_field fvo_1 = { fvo.world, fvo.re, fvo.im, fvo.pos };
    return fvo_1;
}

float4 fs_field(FragmentInput_fs_field fragmentinput_fs_field) : SV_Target0
{
    FVO i_3 = { fragmentinput_fs_field.pos_5, fragmentinput_fs_field.world_5, fragmentinput_fs_field.re_2, fragmentinput_fs_field.im_2 };
    float v_2 = (float)0;

    const bool _e2 = clipped(i_3.world);
    if (_e2) {
        discard;
    }
    const float _e5 = field_value(i_3.re, i_3.im);
    v_2 = _e5;
    float _e10 = u.fmode.y;
    if ((_e10 > 0.5)) {
        float _e13 = v_2;
        v_2 = (6.0206 * log2(max(abs(_e13), 1e-30)));
    }
    float _e20 = v_2;
    float _e24 = u.fphase.z;
    float _e29 = u.fphase.w;
    float _e33 = u.fphase.z;
    float t_1 = clamp(((_e20 - _e24) / max((_e29 - _e33), 1e-30)), 0.0, 1.0);
    const float3 _e41 = colour_map(t_1);
    return float4(_e41, 1.0);
}
