// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: fe2a2f185b7bc4bef1cb30db2cfd3a682ab0ffca210b26d00ed2e57dfaf96fed
// language: metal2.3
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct U {
    metal::float4x4 vp;
    metal::float4 eye;
    metal::float4 clip;
    uint hover;
    uint sel;
    uint flags;
    uint pad;
};
struct VI {
    metal::packed_float3 p;
    uint id;
    metal::float4 col;
};
struct VO {
    metal::float4 pos;
    metal::packed_float3 world;
    uint id;
    metal::float4 col;
};
struct PickOut {
    uint id;
    char _pad1[12];
    metal::float4 world;
};

bool clipped(
    metal::float3 w,
    constant U& u
) {
    bool local_1 = {};
    uint _e3 = u.flags;
    if ((_e3 & 1u) != 0u) {
        metal::float4 _e12 = u.clip;
        float _e18 = u.clip.w;
        local_1 = (metal::dot(_e12.xyz, w) + _e18) > 0.0;
    } else {
        local_1 = false;
    }
    bool _e23 = local_1;
    return _e23;
}

metal::float3 highlight(
    metal::float3 rgb_1,
    uint id,
    constant U& u
) {
    metal::float3 c = {};
    bool local_2 = {};
    bool local_3 = {};
    c = rgb_1;
    if (id != 0u) {
        uint _e9 = u.hover;
        local_2 = id == _e9;
    } else {
        local_2 = false;
    }
    bool _e12 = local_2;
    if (_e12) {
        metal::float3 _e13 = c;
        c = metal::mix(_e13, metal::float3(0.2, 0.9, 1.0), 0.45);
    }
    if (id != 0u) {
        uint _e26 = u.sel;
        local_3 = id == _e26;
    } else {
        local_3 = false;
    }
    bool _e29 = local_3;
    if (_e29) {
        metal::float3 _e30 = c;
        c = metal::mix(_e30, metal::float3(1.0, 0.35, 1.0), 0.55);
    }
    metal::float3 _e37 = c;
    return _e37;
}

struct vsInput {
    metal::float3 p [[attribute(0)]];
    uint id_1 [[attribute(1)]];
    metal::float4 col [[attribute(2)]];
};
struct vsOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    uint id [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
vertex vsOutput vs(
  vsInput varyings [[stage_in]]
, constant U& u [[buffer(1)]]
) {
    const VI v = { varyings.p, varyings.id_1, varyings.col };
    VO o = {};
    metal::float4x4 _e5 = u.vp;
    o.pos = _e5 * metal::float4(v.p, 1.0);
    o.world = v.p;
    o.id = v.id;
    o.col = v.col;
    VO _e16 = o;
    const auto _tmp = _e16;
    return vsOutput { _tmp.pos, _tmp.world, _tmp.id, _tmp.col };
}


struct fs_colorInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_1 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
struct fs_colorOutput {
    metal::float4 member_1 [[color(0)]];
};
fragment fs_colorOutput fs_color(
  fs_colorInput varyings_1 [[stage_in]]
, metal::float4 pos [[position]]
, bool front [[front_facing]]
, constant U& u [[buffer(1)]]
) {
    const VO i = { pos, varyings_1.world, varyings_1.id_1, varyings_1.col };
    metal::float3 rgb = {};
    bool local = {};
    bool _e3 = clipped(i.world, u);
    if (_e3) {
        metal::discard_fragment();
    }
    metal::float3 _e5 = metal::dfdx(i.world);
    metal::float3 _e7 = metal::dfdy(i.world);
    metal::float3 n = metal::normalize(metal::cross(_e5, _e7));
    metal::float4 _e12 = u.eye;
    float d = metal::abs(metal::dot(n, metal::normalize(_e12.xyz - i.world)));
    rgb = i.col.xyz * (0.3 + (0.7 * d));
    if (!(front)) {
        uint _e32 = u.flags;
        local = (_e32 & 2u) != 0u;
    } else {
        local = false;
    }
    bool _e38 = local;
    if (_e38) {
        rgb = i.col.xyz * 0.8;
    }
    metal::float3 _e43 = rgb;
    metal::float3 _e45 = highlight(_e43, i.id, u);
    return fs_colorOutput { metal::float4(_e45, i.col.w) };
}


struct fs_lineInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_1 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
struct fs_lineOutput {
    metal::float4 member_2 [[color(0)]];
};
fragment fs_lineOutput fs_line(
  fs_lineInput varyings_2 [[stage_in]]
, metal::float4 pos_1 [[position]]
) {
    const VO i_1 = { pos_1, varyings_2.world, varyings_2.id_1, varyings_2.col };
    return fs_lineOutput { metal::float4(i_1.col.xyz, 1.0) };
}


struct fs_pickInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_1 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
struct fs_pickOutput {
    uint id [[color(0)]];
    metal::float4 world [[color(1)]];
};
fragment fs_pickOutput fs_pick(
  fs_pickInput varyings_3 [[stage_in]]
, metal::float4 pos_2 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_2 = { pos_2, varyings_3.world, varyings_3.id_1, varyings_3.col };
    PickOut o_1 = {};
    bool _e2 = clipped(i_2.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    o_1.id = i_2.id;
    o_1.world = metal::float4(i_2.world, 1.0);
    PickOut _e10 = o_1;
    const auto _tmp_1 = _e10;
    return fs_pickOutput { _tmp_1.id, _tmp_1.world };
}
