// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: 5703fa697810a07d678d2798a7437e5a9370103d1e061959ddb2871982a84e04
// language: metal2.3
#include <metal_stdlib>
#include <simd/simd.h>

using metal::uint;

struct type_3 {
    metal::float4 inner[16];
};
struct U {
    metal::float4x4 vp;
    metal::float4 eye;
    metal::float4 clip;
    uint hover;
    uint sel;
    uint flags;
    uint pad;
    metal::float4 fphase;
    metal::float4 fmode;
    type_3 stops;
};
struct VI {
    metal::packed_float3 p;
    uint id;
    metal::float4 col;
};
struct VO {
    metal::float4 pos;
    metal::packed_float3 world;
    uint id;
    metal::float4 col;
};
struct PickOut {
    uint id;
    char _pad1[12];
    metal::float4 world;
};
struct FVI {
    metal::float3 p;
    metal::float3 re;
    metal::float3 im;
};
struct FVO {
    metal::float4 pos;
    metal::float3 world;
    metal::float3 re;
    metal::float3 im;
};

bool clipped(
    metal::float3 w,
    constant U& u
) {
    bool local_1 = {};
    uint _e3 = u.flags;
    if ((_e3 & 1u) != 0u) {
        metal::float4 _e12 = u.clip;
        float _e18 = u.clip.w;
        local_1 = (metal::dot(_e12.xyz, w) + _e18) > 0.0;
    } else {
        local_1 = false;
    }
    bool _e23 = local_1;
    return _e23;
}

metal::float3 highlight(
    metal::float3 rgb_1,
    uint id,
    constant U& u
) {
    metal::float3 c = {};
    bool local_2 = {};
    bool local_3 = {};
    c = rgb_1;
    if (id != 0u) {
        uint _e9 = u.hover;
        local_2 = id == _e9;
    } else {
        local_2 = false;
    }
    bool _e12 = local_2;
    if (_e12) {
        metal::float3 _e13 = c;
        c = metal::mix(_e13, metal::float3(0.2, 0.9, 1.0), 0.45);
    }
    if (id != 0u) {
        uint _e26 = u.sel;
        local_3 = id == _e26;
    } else {
        local_3 = false;
    }
    bool _e29 = local_3;
    if (_e29) {
        metal::float3 _e30 = c;
        c = metal::mix(_e30, metal::float3(1.0, 0.35, 1.0), 0.55);
    }
    metal::float3 _e37 = c;
    return _e37;
}

uint naga_f2u32(float value) {
    return static_cast<uint>(metal::clamp(value, 0.0, 4294967000.0));
}

float field_value(
    metal::float3 re,
    metal::float3 im,
    constant U& u
) {
    float c_1 = u.fphase.x;
    float s = u.fphase.y;
    float _e13 = u.fmode.x;
    uint mode = naga_f2u32(_e13 + 0.5);
    if (mode == 0u) {
        return metal::sqrt(metal::dot(re, re) + metal::dot(im, im));
    }
    if (mode == 1u) {
        return metal::length((re * c_1) - (im * s));
    }
    if (mode == 2u) {
        return re.x;
    }
    if (mode == 3u) {
        return (re.x * c_1) - (im.x * s);
    }
    return metal::sqrt((re.x * re.x) + (im.x * im.x));
}

metal::float3 colour_map(
    float t,
    constant U& u
) {
    metal::float3 rgb_2 = {};
    uint k = 1u;
    bool local_4 = {};
    float _e4 = u.fmode.z;
    uint n = naga_f2u32(_e4 + 0.5);
    metal::float4 _e11 = u.stops.inner[0];
    rgb_2 = _e11.yzw;
    uint2 loop_bound = uint2(4294967295u);
    bool loop_init = true;
    while(true) {
        if (metal::all(loop_bound == uint2(0u))) { break; }
        loop_bound -= uint2(loop_bound.y == 0u, 1u);
        if (!loop_init) {
            uint _e55 = k;
            k = _e55 + 1u;
        }
        loop_init = false;
        uint _e16 = k;
        if (_e16 < n) {
        } else {
            break;
        }
        {
            uint _e20 = k;
            metal::float4 a = u.stops.inner[_e20 - 1u];
            uint _e27 = k;
            metal::float4 b = u.stops.inner[_e27];
            if (!((t <= b.x))) {
                uint _e35 = k;
                local_4 = _e35 == (n - 1u);
            } else {
                local_4 = true;
            }
            bool _e40 = local_4;
            if (_e40) {
                float w_1 = metal::clamp((t - a.x) / metal::max(b.x - a.x, 0.000001), 0.0, 1.0);
                rgb_2 = metal::mix(a.yzw, b.yzw, w_1);
                break;
            }
        }
    }
    metal::float3 _e58 = rgb_2;
    return _e58;
}

struct vsInput {
    metal::float3 p [[attribute(0)]];
    uint id_1 [[attribute(1)]];
    metal::float4 col [[attribute(2)]];
};
struct vsOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    uint id [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
vertex vsOutput vs(
  vsInput varyings [[stage_in]]
, constant U& u [[buffer(1)]]
) {
    const VI v = { varyings.p, varyings.id_1, varyings.col };
    VO o = {};
    metal::float4x4 _e5 = u.vp;
    o.pos = _e5 * metal::float4(v.p, 1.0);
    o.world = v.p;
    o.id = v.id;
    o.col = v.col;
    VO _e16 = o;
    const auto _tmp = _e16;
    return vsOutput { _tmp.pos, _tmp.world, _tmp.id, _tmp.col };
}


struct fs_colorInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_1 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
struct fs_colorOutput {
    metal::float4 member_1 [[color(0)]];
};
fragment fs_colorOutput fs_color(
  fs_colorInput varyings_1 [[stage_in]]
, metal::float4 pos [[position]]
, bool front [[front_facing]]
, constant U& u [[buffer(1)]]
) {
    const VO i = { pos, varyings_1.world, varyings_1.id_1, varyings_1.col };
    metal::float3 rgb = {};
    bool local = {};
    bool _e3 = clipped(i.world, u);
    if (_e3) {
        metal::discard_fragment();
    }
    metal::float3 _e5 = metal::dfdx(i.world);
    metal::float3 _e7 = metal::dfdy(i.world);
    metal::float3 n_1 = metal::normalize(metal::cross(_e5, _e7));
    metal::float4 _e12 = u.eye;
    float d = metal::abs(metal::dot(n_1, metal::normalize(_e12.xyz - i.world)));
    rgb = i.col.xyz * (0.3 + (0.7 * d));
    if (!(front)) {
        uint _e32 = u.flags;
        local = (_e32 & 2u) != 0u;
    } else {
        local = false;
    }
    bool _e38 = local;
    if (_e38) {
        rgb = i.col.xyz * 0.8;
    }
    metal::float3 _e43 = rgb;
    metal::float3 _e45 = highlight(_e43, i.id, u);
    return fs_colorOutput { metal::float4(_e45, i.col.w) };
}


struct fs_lineInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_1 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
struct fs_lineOutput {
    metal::float4 member_2 [[color(0)]];
};
fragment fs_lineOutput fs_line(
  fs_lineInput varyings_2 [[stage_in]]
, metal::float4 pos_1 [[position]]
) {
    const VO i_1 = { pos_1, varyings_2.world, varyings_2.id_1, varyings_2.col };
    return fs_lineOutput { metal::float4(i_1.col.xyz, 1.0) };
}


struct fs_pickInput {
    metal::float3 world [[user(loc0), center_perspective]];
    uint id_1 [[user(loc1), flat]];
    metal::float4 col [[user(loc2), center_perspective]];
};
struct fs_pickOutput {
    uint id [[color(0)]];
    metal::float4 world [[color(1)]];
};
fragment fs_pickOutput fs_pick(
  fs_pickInput varyings_3 [[stage_in]]
, metal::float4 pos_2 [[position]]
, constant U& u [[buffer(1)]]
) {
    const VO i_2 = { pos_2, varyings_3.world, varyings_3.id_1, varyings_3.col };
    PickOut o_1 = {};
    bool _e2 = clipped(i_2.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    o_1.id = i_2.id;
    o_1.world = metal::float4(i_2.world, 1.0);
    PickOut _e10 = o_1;
    const auto _tmp_1 = _e10;
    return fs_pickOutput { _tmp_1.id, _tmp_1.world };
}


struct vs_fieldInput {
    metal::float3 p [[attribute(0)]];
    metal::float3 re_1 [[attribute(1)]];
    metal::float3 im_1 [[attribute(2)]];
};
struct vs_fieldOutput {
    metal::float4 pos [[position]];
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re [[user(loc1), center_perspective]];
    metal::float3 im [[user(loc2), center_perspective]];
};
vertex vs_fieldOutput vs_field(
  vs_fieldInput varyings_4 [[stage_in]]
, constant U& u [[buffer(1)]]
) {
    const FVI v_1 = { varyings_4.p, varyings_4.re_1, varyings_4.im_1 };
    FVO o_2 = {};
    metal::float4x4 _e5 = u.vp;
    o_2.pos = _e5 * metal::float4(v_1.p, 1.0);
    o_2.world = v_1.p;
    o_2.re = v_1.re;
    o_2.im = v_1.im;
    FVO _e16 = o_2;
    const auto _tmp_2 = _e16;
    return vs_fieldOutput { _tmp_2.pos, _tmp_2.world, _tmp_2.re, _tmp_2.im };
}


struct fs_fieldInput {
    metal::float3 world [[user(loc0), center_perspective]];
    metal::float3 re_1 [[user(loc1), center_perspective]];
    metal::float3 im_1 [[user(loc2), center_perspective]];
};
struct fs_fieldOutput {
    metal::float4 member_5 [[color(0)]];
};
fragment fs_fieldOutput fs_field(
  fs_fieldInput varyings_5 [[stage_in]]
, metal::float4 pos_3 [[position]]
, constant U& u [[buffer(1)]]
) {
    const FVO i_3 = { pos_3, varyings_5.world, varyings_5.re_1, varyings_5.im_1 };
    float v_2 = {};
    bool _e2 = clipped(i_3.world, u);
    if (_e2) {
        metal::discard_fragment();
    }
    float _e5 = field_value(i_3.re, i_3.im, u);
    v_2 = _e5;
    float _e10 = u.fmode.y;
    if (_e10 > 0.5) {
        float _e13 = v_2;
        v_2 = 6.0206 * metal::log2(metal::max(metal::abs(_e13), 0.000000000000000000000000000001));
    }
    float _e20 = v_2;
    float _e24 = u.fphase.z;
    float _e29 = u.fphase.w;
    float _e33 = u.fphase.z;
    float t_1 = metal::clamp((_e20 - _e24) / metal::max(_e29 - _e33, 0.000000000000000000000000000001), 0.0, 1.0);
    metal::float3 _e41 = colour_map(t_1, u);
    return fs_fieldOutput { metal::float4(_e41, 1.0) };
}
