// generated by tools/ShaderGen from scene.wgsl — do not edit; wgsl-sha256: fe2a2f185b7bc4bef1cb30db2cfd3a682ab0ffca210b26d00ed2e57dfaf96fed
struct U {
    row_major float4x4 vp;
    float4 eye;
    float4 clip_;
    uint hover;
    uint sel;
    uint flags;
    uint pad;
};

struct VI {
    float3 p : LOC0;
    uint id : LOC1;
    float4 col : LOC2;
};

struct VO {
    float4 pos : SV_Position;
    float3 world : LOC0;
    nointerpolation uint id : LOC1;
    float4 col : LOC2;
};

struct PickOut {
    uint id : SV_Target0;
    float4 world : SV_Target1;
};

cbuffer u : register(b0) { U u; }

struct VertexOutput_vs {
    float3 world : LOC0;
    nointerpolation uint id_1 : LOC1;
    float4 col : LOC2;
    float4 pos : SV_Position;
};

struct FragmentInput_fs_color {
    float3 world_1 : LOC0;
    nointerpolation uint id_2 : LOC1;
    float4 col_1 : LOC2;
    float4 pos_1 : SV_Position;
    bool front_1 : SV_IsFrontFace;
};

struct FragmentInput_fs_line {
    float3 world_2 : LOC0;
    nointerpolation uint id_3 : LOC1;
    float4 col_2 : LOC2;
    float4 pos_2 : SV_Position;
};

struct FragmentInput_fs_pick {
    float3 world_3 : LOC0;
    nointerpolation uint id_4 : LOC1;
    float4 col_3 : LOC2;
    float4 pos_3 : SV_Position;
};

bool clipped(float3 w)
{
    bool local_1 = (bool)0;

    uint _e3 = u.flags;
    if (((_e3 & 1u) != 0u)) {
        float4 _e12 = u.clip_;
        float _e18 = u.clip_.w;
        local_1 = ((dot(_e12.xyz, w) + _e18) > 0.0);
    } else {
        local_1 = false;
    }
    bool _e23 = local_1;
    return _e23;
}

float3 highlight(float3 rgb_1, uint id)
{
    float3 c = (float3)0;
    bool local_2 = (bool)0;
    bool local_3 = (bool)0;

    c = rgb_1;
    if ((id != 0u)) {
        uint _e9 = u.hover;
        local_2 = (id == _e9);
    } else {
        local_2 = false;
    }
    bool _e12 = local_2;
    if (_e12) {
        float3 _e13 = c;
        c = lerp(_e13, float3(0.2, 0.9, 1.0), 0.45);
    }
    if ((id != 0u)) {
        uint _e26 = u.sel;
        local_3 = (id == _e26);
    } else {
        local_3 = false;
    }
    bool _e29 = local_3;
    if (_e29) {
        float3 _e30 = c;
        c = lerp(_e30, float3(1.0, 0.35, 1.0), 0.55);
    }
    float3 _e37 = c;
    return _e37;
}

VertexOutput_vs vs(VI v)
{
    VO o = (VO)0;

    float4x4 _e5 = u.vp;
    o.pos = mul(float4(v.p, 1.0), _e5);
    o.world = v.p;
    o.id = v.id;
    o.col = v.col;
    VO _e16 = o;
    const VO vo = _e16;
    const VertexOutput_vs vo_1 = { vo.world, vo.id, vo.col, vo.pos };
    return vo_1;
}

float4 fs_color(FragmentInput_fs_color fragmentinput_fs_color) : SV_Target0
{
    VO i = { fragmentinput_fs_color.pos_1, fragmentinput_fs_color.world_1, fragmentinput_fs_color.id_2, fragmentinput_fs_color.col_1 };
    bool front = fragmentinput_fs_color.front_1;
    float3 rgb = (float3)0;
    bool local = (bool)0;

    const bool _e3 = clipped(i.world);
    if (_e3) {
        discard;
    }
    float3 _e5 = ddx(i.world);
    float3 _e7 = ddy(i.world);
    float3 n = normalize(cross(_e5, _e7));
    float4 _e12 = u.eye;
    float d = abs(dot(n, normalize((_e12.xyz - i.world))));
    rgb = (i.col.xyz * (0.3 + (0.7 * d)));
    if (!(front)) {
        uint _e32 = u.flags;
        local = ((_e32 & 2u) != 0u);
    } else {
        local = false;
    }
    bool _e38 = local;
    if (_e38) {
        rgb = (i.col.xyz * 0.8);
    }
    float3 _e43 = rgb;
    const float3 _e45 = highlight(_e43, i.id);
    return float4(_e45, i.col.w);
}

float4 fs_line(FragmentInput_fs_line fragmentinput_fs_line) : SV_Target0
{
    VO i_1 = { fragmentinput_fs_line.pos_2, fragmentinput_fs_line.world_2, fragmentinput_fs_line.id_3, fragmentinput_fs_line.col_2 };
    return float4(i_1.col.xyz, 1.0);
}

PickOut fs_pick(FragmentInput_fs_pick fragmentinput_fs_pick)
{
    VO i_2 = { fragmentinput_fs_pick.pos_3, fragmentinput_fs_pick.world_3, fragmentinput_fs_pick.id_4, fragmentinput_fs_pick.col_3 };
    PickOut o_1 = (PickOut)0;

    const bool _e2 = clipped(i_2.world);
    if (_e2) {
        discard;
    }
    o_1.id = i_2.id;
    o_1.world = float4(i_2.world, 1.0);
    PickOut _e10 = o_1;
    const PickOut pickout = _e10;
    return pickout;
}
