<#
  ── circuitRF Windows .msi builder ──────────────────────────────────────────────

    .\packaging\windows\build-msi.ps1                  → dist\circuitRF-<VERSION>-x64.msi
    .\packaging\windows\build-msi.ps1 -Arch arm64      → dist\circuitRF-<VERSION>-arm64.msi
    .\packaging\windows\build-msi.ps1 -Arch x86        → dist\circuitRF-<VERSION>-x86.msi

  <VERSION> is the contents of the repo-root VERSION file; see BUILDING.md.

  Requires: .NET 10 SDK and the WiX v4 CLI —

      dotnet tool install --global wix
      wix extension add --global WixToolset.UI.wixext

  Run it from the repository root, in PowerShell. Everything is derived from -Arch: the runtime
  identifier, the publish directory and the MSI platform.
#>

[CmdletBinding()]
param(
    [ValidateSet('x64', 'arm64', 'x86')]
    [string]$Arch = 'x64',

    # Defaults to the repo-root VERSION file — the one place the version is written. Override only
    # for a one-off build; nothing is written back.
    [string]$Version
)

$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..\..')

# An explicit -Version wins; otherwise version.ps1 reads the repo-root VERSION file. Either way the
# numeric $CrfMsiVersion is derived in one place.
if ($Version) { $CrfVersion = $Version }
. (Join-Path $PSScriptRoot '..\version.ps1')

$rid = "win-$Arch"
$publish = Join-Path $root "publish\$rid"
$dist = Join-Path $root 'dist'
$msi = Join-Path $dist "circuitRF-$CrfVersion-$Arch.msi"

# The icon must exist BEFORE the publish: the .csproj embeds Assets\circuitRFIcon.ico into the
# executable only if it is on disk, and that embedded icon is what Explorer draws for the .exe.
Write-Host '🎨 Building icons...'
dotnet run --project (Join-Path $root 'tools\IconGen') -- circuitrf
if ($LASTEXITCODE -ne 0) { throw 'Icon generation failed.' }

Write-Host "📦 Publishing $rid..."
if (Test-Path $publish) { Remove-Item $publish -Recurse -Force }
dotnet publish (Join-Path $root 'src\Ui\CircuitRF.Ui.csproj') `
    -c Release -r $rid --self-contained true -o $publish
if ($LASTEXITCODE -ne 0) { throw 'Publish failed.' }

# ── Harvest the publish tree ───────────────────────────────────────────────────
#
# Everything except the .exe, which circuitRF.wxs names itself so the shortcuts and file
# associations can point at it. Harvesting rather than listing by hand is what keeps the installer
# correct when the published set changes — the app ships its user documentation as loose files, and
# the native SkiaSharp/HarfBuzz DLLs come and go with the single-file settings.

Write-Host '🔎 Harvesting published files...'
$filesWxs = Join-Path $PSScriptRoot 'Files.wxs'
$dirId = 0
$compId = 0
$sb = [System.Text.StringBuilder]::new()
$components = [System.Text.StringBuilder]::new()

function Add-Directory($path, $parentId) {
    foreach ($file in Get-ChildItem -LiteralPath $path -File | Sort-Object Name) {
        if ($file.Name -eq 'CircuitRF.Ui.exe') { continue }
        $script:compId++
        [void]$script:components.AppendLine(
            "      <Component Id=`"cmp$($script:compId)`" Directory=`"$parentId`">")
        [void]$script:components.AppendLine(
            "        <File Id=`"fil$($script:compId)`" Source=`"$($file.FullName)`" KeyPath=`"yes`" />")
        [void]$script:components.AppendLine('      </Component>')
    }
    foreach ($sub in Get-ChildItem -LiteralPath $path -Directory | Sort-Object Name) {
        $script:dirId++
        $id = "dir$($script:dirId)"
        [void]$script:sb.AppendLine("      <Directory Id=`"$id`" Name=`"$($sub.Name)`">")
        Add-Directory $sub.FullName $id
        [void]$script:sb.AppendLine('      </Directory>')
    }
}

Add-Directory $publish 'INSTALLFOLDER'

@"
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by build-msi.ps1 from the publish output. Do not edit; do not commit. -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <DirectoryRef Id="INSTALLFOLDER">
$($sb.ToString().TrimEnd())
    </DirectoryRef>
    <ComponentGroup Id="PublishedFiles">
$($components.ToString().TrimEnd())
    </ComponentGroup>
  </Fragment>
</Wix>
"@ | Set-Content -LiteralPath $filesWxs -Encoding UTF8

# ── Build the installer ────────────────────────────────────────────────────────

New-Item -ItemType Directory -Force -Path $dist | Out-Null

Write-Host "🗜  Building $msi..."
Push-Location $PSScriptRoot
try {
    # $CrfMsiVersion is the numeric four-field form: "0.9.0-beta.1" is not a valid ProductVersion.
    # No trailing backslash on PublishDir: a native command line eats it as a quote escape. The
    # .wxs supplies the separator itself.
    $icon = Join-Path $root 'src\Ui\Assets\circuitRFIcon.ico'

    wix build circuitRF.wxs Files.wxs `
        -arch $Arch `
        -d "Version=$CrfMsiVersion" `
        -d "PublishDir=$publish" `
        -d "IconFile=$icon" `
        -ext WixToolset.UI.wixext `
        -o $msi
    if ($LASTEXITCODE -ne 0) { throw 'wix build failed.' }
}
finally { Pop-Location }

Write-Host ''
Write-Host "✅ $msi"
Write-Host '   Unsigned: SmartScreen will warn on first run. Sign with signtool for distribution — see BUILDING.md.'
