// circuitRF F0 spike -- case B: microstrip -> plated via -> inverted microstrip, through a ground
// plane with a round antipad. HAND-WRITTEN SPIKE MATERIAL (brief-em3d-1 R-em3d1-2). Not generated by
// circuitRF, and nothing under src/ may read or reuse it. Units: micrometres ("L0": 1.0e-6).
//
// Run:  gmsh case.geo -3 -o case.msh      (writes entities.txt beside it)
//
// Stackup, z up (mirror-symmetric about z = 252.5):
//   bottom copper   z [  0,  35]   the inverted microstrip, x [0, 5000], w 400, pad d 600 at x = 0
//   dielectric 2    z [ 35, 235]   er 3.66, tand 0.004
//   ground plane    z [235, 270]   board-wide, round antipad d 900 at x = 0 (filled with dielectric)
//   dielectric 1    z [270, 470]
//   top copper      z [470, 505]   the microstrip, x [-5000, 0], w 400, pad d 600 at x = 0
//   via barrel      d 300 (the drill), z [0, 505]; plated, so only its outer surface carries current
// Board x [-5000, 5000] y [-2500, 2500]; air to 1500 um beyond it on every side; the outer walls
// are first-order absorbing. Every conductor is a VOID with Palace's finite-conductivity boundary,
// sigma 5.8e7 S/m. Lumped 50-ohm ports: sheets at the line ends from the ground plane to the line.
// Line width 400 um: 50.4 ohm by Hammerstad-Jensen with Wheeler's thickness correction.

SetFactory("OpenCASCADE");
Geometry.OCCBooleanPreserveNumbering = 1;
Geometry.OCCBoundsUseStl = 1;          // tight bounding boxes (OCC boxes are loose on curved faces)

w = 400; rp = 300; rd = 150; ra = 450;
Bx = 5000; By = 2500; m = 1500;
z0 = 0; z1 = 35; z2 = 235; z3 = 270; z4 = 470; z5 = 505;
e = 1e-3;

// ---- conductors (removed from the domain: voids) -------------------------------------------
tt = newv; Box(tt) = {-Bx, -w/2, z4, Bx, w, z5 - z4};
tp = newv; Cylinder(tp) = {0, 0, z4, 0, 0, z5 - z4, rp};
bt = newv; Box(bt) = {0, -w/2, z0, Bx, w, z1 - z0};
bp = newv; Cylinder(bp) = {0, 0, z0, 0, 0, z1 - z0, rp};
br = newv; Cylinder(br) = {0, 0, z0, 0, 0, z5 - z0, rd};
sig[] = BooleanUnion{ Volume{tt}; Delete; }{ Volume{tp, bt, bp, br}; Delete; };
gb = newv; Box(gb) = {-Bx, -By, z2, 2*Bx, 2*By, z3 - z2};
ah = newv; Cylinder(ah) = {0, 0, z2, 0, 0, z3 - z2, ra};
gnd[] = BooleanDifference{ Volume{gb}; Delete; }{ Volume{ah}; Delete; };

// ---- dielectrics, each made disjoint from the conductors BEFORE the fragment ---------------
b1 = newv; Box(b1) = {-Bx, -By, z3, 2*Bx, 2*By, z4 - z3};
d1[] = BooleanDifference{ Volume{b1}; Delete; }{ Volume{sig[]}; };
b2 = newv; Box(b2) = {-Bx, -By, z1, 2*Bx, 2*By, z2 - z1};
d2[] = BooleanDifference{ Volume{b2}; Delete; }{ Volume{sig[]}; };
fa = newv; Cylinder(fa) = {0, 0, z2, 0, 0, z3 - z2, ra};
dA[] = BooleanDifference{ Volume{fa}; Delete; }{ Volume{sig[]}; };

dom = newv; Box(dom) = {-Bx - m, -By - m, z0 - m, 2*(Bx + m), 2*(By + m), z5 - z0 + 2*m};
air[] = BooleanDifference{ Volume{dom}; Delete; }{ Volume{d1[], d2[], dA[], gnd[], sig[]}; };
Recursive Delete { Volume{gnd[], sig[]}; }

// ---- port sheets -----------------------------------------------------------------------------
p1 = news; Rectangle(p1) = {-w/2, z3, 0, w, z4 - z3};   // drawn in xy, turned into the x = -Bx plane
Rotate {{0,1,0}, {0,0,0}, -Pi/2} { Surface{p1}; }
Rotate {{1,0,0}, {0,0,0},  Pi/2} { Surface{p1}; }
Translate {-Bx, 0, 0} { Surface{p1}; }
p2 = news; Rectangle(p2) = {-w/2, z1, 0, w, z2 - z1};
Rotate {{0,1,0}, {0,0,0}, -Pi/2} { Surface{p2}; }
Rotate {{1,0,0}, {0,0,0},  Pi/2} { Surface{p2}; }
Translate { Bx, 0, 0} { Surface{p2}; }

frag[] = BooleanFragments{ Volume{air[], d1[], d2[], dA[]}; Delete; }{ Surface{p1, p2}; Delete; };

// ---- recover every named object by what is known about it ----------------------------------
vD1[] = Volume In BoundingBox{-Bx-e, -By-e, z3-e, Bx+e, By+e, z4+e};
vD2[] = Volume In BoundingBox{-Bx-e, -By-e, z1-e, Bx+e, By+e, z2+e};
vDA[] = Volume In BoundingBox{-ra-e, -ra-e, z2-e, ra+e, ra+e, z3+e};
vAir[] = Volume{:};
vAir[] -= {vD1[], vD2[], vDA[]};

sP1[] = Surface In BoundingBox{-Bx-e, -w/2-e, z3-e, -Bx+e, w/2+e, z4+e};
sP2[] = Surface In BoundingBox{ Bx-e, -w/2-e, z1-e,  Bx+e, w/2+e, z2+e};

X = Bx + m; Y = By + m; Zl = z0 - m; Zh = z5 + m;
sOut[]  = Surface In BoundingBox{-X-e, -Y-e, Zl-e, -X+e, Y+e, Zh+e};
sOut[] += Surface In BoundingBox{ X-e, -Y-e, Zl-e,  X+e, Y+e, Zh+e};
sOut[] += Surface In BoundingBox{-X-e, -Y-e, Zl-e,  X+e, -Y+e, Zh+e};
sOut[] += Surface In BoundingBox{-X-e,  Y-e, Zl-e,  X+e,  Y+e, Zh+e};
sOut[] += Surface In BoundingBox{-X-e, -Y-e, Zl-e,  X+e,  Y+e, Zl+e};
sOut[] += Surface In BoundingBox{-X-e, -Y-e, Zh-e,  X+e,  Y+e, Zh+e};

// Signal conductor: everything inside the narrow box the lines, pads and barrel occupy.
sSig[] = Surface In BoundingBox{-Bx-e, -rp-e, z0-e, Bx+e, rp+e, z5+e};
sSig[] -= {sP1[], sP2[]};
// Ground plane: everything in its slab, except the dielectric fill's two annular faces (which
// share the antipad wall's x-y extent and differ from it only in z-extent) and the barrel.
sGndAll[] = Surface In BoundingBox{-Bx-e, -By-e, z2-e, Bx+e, By+e, z3+e};
sAnn[]  = Surface In BoundingBox{-ra-e, -ra-e, z2-e, ra+e, ra+e, z2+e};
sAnn[] += Surface In BoundingBox{-ra-e, -ra-e, z3-e, ra+e, ra+e, z3+e};
sGnd[] = sGndAll[];
sGnd[] -= {sAnn[], sSig[]};

Physical Volume("air", 1)          = {vAir[]};
Physical Volume("dielectric", 2)   = {vD1[], vD2[], vDA[]};
Physical Surface("outer_abc", 3)   = {sOut[]};
Physical Surface("signal", 4)      = {sSig[]};
Physical Surface("ground", 5)      = {sGnd[]};
Physical Surface("port1", 6)       = {sP1[]};
Physical Surface("port2", 7)       = {sP2[]};

allS[] = Surface{:};
Printf("# name count") > "entities.txt";
Printf("air %g", #vAir[]) >> "entities.txt";
Printf("dielectric1 %g", #vD1[]) >> "entities.txt";
Printf("dielectric2 %g", #vD2[]) >> "entities.txt";
Printf("antipad_fill %g", #vDA[]) >> "entities.txt";
Printf("outer_abc %g", #sOut[]) >> "entities.txt";
Printf("signal %g", #sSig[]) >> "entities.txt";
Printf("ground %g", #sGnd[]) >> "entities.txt";
Printf("port1 %g", #sP1[]) >> "entities.txt";
Printf("port2 %g", #sP2[]) >> "entities.txt";
Printf("annuli %g", #sAnn[]) >> "entities.txt";
Printf("all_surfaces %g", #allS[]) >> "entities.txt";
Printf("tag_d1 before %g after %g", d1[0], vD1[0]) >> "entities.txt";
Printf("tag_d2 before %g after %g", d2[0], vD2[0]) >> "entities.txt";
Printf("tag_fill before %g after %g", dA[0], vDA[0]) >> "entities.txt";
Printf("tag_air before %g after %g", air[0], vAir[0]) >> "entities.txt";
Printf("fragment_returned %g entities", #frag[]) >> "entities.txt";

// ---- mesh ----------------------------------------------------------------------------------
Mesh.MeshSizeMax = 800;
Mesh.MeshSizeMin = 10;
Mesh.MeshSizeFromPoints = 0;
Mesh.MeshSizeExtendFromBoundary = 0;
Field[1] = Distance; Field[1].SurfacesList = {sSig[]}; Field[1].Sampling = 60;
Field[2] = Threshold; Field[2].InField = 1;
Field[2].SizeMin = 60; Field[2].SizeMax = 800; Field[2].DistMin = 30; Field[2].DistMax = 2500;
Field[3] = Box; Field[3].VIn = 250; Field[3].VOut = 800;
Field[3].XMin = -Bx; Field[3].XMax = Bx; Field[3].YMin = -By; Field[3].YMax = By;
Field[3].ZMin = z0; Field[3].ZMax = z5;
Field[4] = Min; Field[4].FieldsList = {2, 3};
Background Field = 4;
Mesh.ElementOrder = 2;
Mesh.HighOrderOptimize = 2;
Mesh.MshFileVersion = 2.2;
Mesh.Binary = 1;
