using CircuitRF.Ui.Layout.PCells;

namespace CircuitRF.Ui.Layout;

/// <summary>
/// R-pc-13: a PCell's generated layout is read-only in the editor; to modify it, detach it from
/// its generator (the escape hatch — see this file's own note on why that is NOT literally L3c's
/// Flatten Hierarchy for this phase's SymbolKind-registered built-ins). Regeneration (R-pc-9's
/// invalidation, triggered on a parameter/technology change) re-invokes the same
/// <see cref="PCellGenerator"/> and replaces <see cref="LayoutView.Shapes"/> in place.
///
/// <b>Why this is a plain mutation, not L3b's cross-document <c>CellLayoutResolver.SetLive</c> +
/// <c>LayoutRenderer.InvalidateCompiledGeometry</c> seam:</b> that seam exists to notify OTHER
/// open documents holding an INSTANCE that references this cell's file by path. L5a's four
/// built-ins are SymbolKind-registered (like TLIN/R/L/C), not on-disk cell folders with instances
/// pointing at them — there is no cross-document reference to invalidate yet. The generated shapes
/// already live directly in <see cref="LayoutView.Shapes"/> (no wrapping instance to flatten
/// either), so <see cref="LayoutView.NotifyChanged"/> — the same mechanism any ordinary shape edit
/// already uses — is the complete, correct invalidation path for this phase. Once L5 wires PCells
/// into real file-backed cells with placed instances, that seam is exactly where cross-document
/// live regeneration would hook in; nothing here forecloses it.
/// </summary>
public sealed partial class LayoutEditorViewModel
{
    /// <summary>True when <see cref="Model"/>'s shapes were produced by a PCell generator — the
    /// editor's own read-only gate.</summary>
    public bool IsPCellReadOnly => Model.PCellOrigin is not null;

    /// <summary>R13a: the stated reason, shown by the view wherever an editing command would
    /// otherwise be offered.</summary>
    public const string PCellReadOnlyReason =
        "This layout is generated by a PCell. Detach it from its generator to edit the geometry directly.";

    /// <summary>
    /// R-pc-13's escape hatch: gives up parametric tracking so the already-generated shapes become
    /// ordinary, freely editable geometry. One-way — there is no "re-attach." Deliberately not
    /// pushed onto the undo stack in this phase (a stated simplification: PCellOrigin is document
    /// metadata, not a <see cref="LayoutShape"/>, and no command type exists for it yet).
    /// </summary>
    public void DetachFromPCell()
    {
        if (Model.PCellOrigin is null) return;
        Model.PCellOrigin = null;
        IsDirty = true;
        Model.NotifyChanged();
        _messageSink?.Info("Detached from its PCell generator — the geometry is now freely editable and will no longer track parameter changes.");
    }

    /// <summary>
    /// R-pc-9's regeneration trigger: re-invokes the ORIGINAL generator with
    /// <paramref name="newParameters"/> (falling back to the existing snapshot for any name not
    /// supplied) and the given technology/layer selection, replaces every shape in
    /// <see cref="LayoutView.Shapes"/> with the fresh result, and updates the stored parameter
    /// snapshot. No-ops (reporting why) when <see cref="Model"/> is not PCell-backed, or the
    /// generator id is unknown (should not happen for a well-formed <see cref="PCellOrigin"/>).
    /// </summary>
    public bool RegeneratePCell(IReadOnlyDictionary<string, double>? newParameters = null,
        PCellLayerSelection? layerSelection = null)
    {
        var origin = Model.PCellOrigin;
        if (origin is null)
        {
            _messageSink?.Warning("Regenerate: this layout has no PCell origin — nothing to regenerate.");
            return false;
        }
        if (!PCellRegistry.TryGet(origin.GeneratorId, out var generator))
        {
            _messageSink?.Error($"Regenerate: unknown PCell generator '{origin.GeneratorId}'.");
            return false;
        }

        var merged = new Dictionary<string, double>(origin.Parameters);
        if (newParameters is not null)
            foreach (var kv in newParameters) merged[kv.Key] = kv.Value;

        var result = generator(merged, Technology, layerSelection ?? PCellLayerSelection.Default);

        Model.Shapes.Clear();
        Model.Shapes.AddRange(result.Shapes);
        Model.PCellOrigin = origin with { Parameters = merged };
        IsDirty = true;
        Model.NotifyChanged();
        return true;
    }
}
