using CircuitRF.Ui.Layout.PCells;

namespace CircuitRF.Ui.Layout;

/// <summary>
/// R-pc-13: a PCell's generated layout is read-only in the editor; to modify it, detach it from
/// its generator (the escape hatch — see this file's own note on why that is NOT literally L3c's
/// Flatten Hierarchy for this phase's SymbolKind-registered built-ins). Regeneration (R-pc-9's
/// invalidation, triggered on a parameter/technology change) re-invokes the same
/// <see cref="PCellGenerator"/> and replaces <see cref="LayoutView.Shapes"/> in place.
///
/// <b>Why this is a plain mutation, not L3b's cross-document <c>CellLayoutResolver.SetLive</c> +
/// <c>LayoutRenderer.InvalidateCompiledGeometry</c> seam:</b> that seam exists to notify OTHER
/// open documents holding an INSTANCE that references this cell's file by path. L5a's four
/// built-ins are SymbolKind-registered (like TLIN/R/L/C), not on-disk cell folders with instances
/// pointing at them — there is no cross-document reference to invalidate yet. The generated shapes
/// already live directly in <see cref="LayoutView.Shapes"/> (no wrapping instance to flatten
/// either), so <see cref="LayoutView.NotifyChanged"/> — the same mechanism any ordinary shape edit
/// already uses — is the complete, correct invalidation path for this phase. Once L5 wires PCells
/// into real file-backed cells with placed instances, that seam is exactly where cross-document
/// live regeneration would hook in; nothing here forecloses it.
/// </summary>
public sealed partial class LayoutEditorViewModel
{
    /// <summary>True when <see cref="Model"/>'s shapes were produced by a PCell generator — the
    /// editor's own read-only gate.</summary>
    public bool IsPCellReadOnly => Model.PCellOrigin is not null;

    /// <summary>R13a: the stated reason, shown by the view wherever an editing command would
    /// otherwise be offered.</summary>
    public const string PCellReadOnlyReason =
        "This layout is generated by a PCell. Detach it from its generator to edit the geometry directly.";

    /// <summary>
    /// R-pc-13's escape hatch: gives up parametric tracking so the already-generated shapes become
    /// ordinary, freely editable geometry. One-way — there is no "re-attach." Deliberately not
    /// pushed onto the undo stack in this phase (a stated simplification: PCellOrigin is document
    /// metadata, not a <see cref="LayoutShape"/>, and no command type exists for it yet).
    /// </summary>
    public void DetachFromPCell()
    {
        if (Model.PCellOrigin is null) return;
        Model.PCellOrigin = null;
        IsDirty = true;
        Model.NotifyChanged();
        _messageSink?.Info("Detached from its PCell generator — the geometry is now freely editable and will no longer track parameter changes.");
    }

    /// <summary>
    /// R-pc-9's regeneration trigger: re-invokes the ORIGINAL generator with
    /// <paramref name="newParameters"/> (falling back to the existing snapshot for any name not
    /// supplied) and the given technology/layer selection, replaces every shape in
    /// <see cref="LayoutView.Shapes"/> with the fresh result, and updates the stored parameter
    /// snapshot. No-ops (reporting why) when <see cref="Model"/> is not PCell-backed, or the
    /// generator id is unknown (should not happen for a well-formed <see cref="PCellOrigin"/>).
    /// </summary>
    public bool RegeneratePCell(IReadOnlyDictionary<string, PCellValue>? newParameters = null,
        PCellLayerSelection? layerSelection = null)
    {
        var origin = Model.PCellOrigin;
        if (origin is null)
        {
            _messageSink?.Warning("Regenerate: this layout has no PCell origin — nothing to regenerate.");
            return false;
        }
        if (!PCellRegistry.TryGet(origin.GeneratorId, out var generator))
        {
            _messageSink?.Error($"Regenerate: unknown PCell generator '{origin.GeneratorId}'.");
            return false;
        }

        var merged = new Dictionary<string, PCellValue>(origin.Parameters);
        if (newParameters is not null)
            foreach (var kv in newParameters) merged[kv.Key] = kv.Value;

        var result = generator(merged, Technology, layerSelection ?? PCellLayerSelection.Default);
        if (result.Diagnostics is { Count: > 0 })
            foreach (var d in result.Diagnostics) _messageSink?.Warning(d);

        // Under RenderLock — this replaces the WHOLE shape list, so a frame catching it mid-swap
        // would be looking at an empty document (see LayoutView.RenderLock and DeleteShapesCommand).
        lock (Model.RenderLock)
        {
            Model.Shapes.Clear();
            Model.Shapes.AddRange(result.Shapes);
            Model.PCellOrigin = origin with { Parameters = merged };
            Model.NotifyChanged();
        }
        IsDirty = true;
        return true;
    }

    // ── L5 R-L5-2: editing a PLACED PCell instance's parameters is copy-on-write ────────────────────
    // Distinct from RegeneratePCell above (which mutates THIS document's own top-level PCellOrigin in
    // place — correct only when Model itself IS the generated layout). An instance elsewhere in a
    // parent layout points at a cell folder under GeneratedCellStore.ReservedFolderName that may be
    // shared by other instances (R-L5-1's whole point); mutating that cell's shapes in place would
    // silently change every sibling too. GeneratedCellStore is content-addressed on the parameter
    // values themselves, so "edit the parameters" is simply "repoint CellRef at whatever cell those
    // new values hash to" — the existing cell (and any other instance referencing it) is never
    // touched, and if the new value set already has a generated cell (e.g. the user dialed back to a
    // value some OTHER instance already uses), it is reused rather than duplicated, automatically.

    /// <summary>
    /// Edits <see cref="LayoutView.Instances"/>[<paramref name="instanceIndex"/>]'s PCell parameters —
    /// no-op (with a reason) when that instance's resolved cell has no <see cref="PCellOrigin"/>, or
    /// when no workspace is open (generated cells need a stable workspace-root location to live in).
    /// One <see cref="Commands.Layout.ReplaceInstanceCommand"/>, so it undoes like any other instance
    /// edit. Unspecified parameter names in <paramref name="newParameters"/> keep the resolved cell's
    /// current value, mirroring <see cref="RegeneratePCell"/>'s own merge behavior.
    /// </summary>
    public bool EditInstancePCellParameters(int instanceIndex, IReadOnlyDictionary<string, PCellValue> newParameters,
        long translateDx = 0, long translateDy = 0)
    {
        if ((uint)instanceIndex >= (uint)Model.Instances.Count) return false;
        var inst = Model.Instances[instanceIndex];

        var res = CellLayoutResolver.Resolve(inst.CellRef, InstanceBaseDir);
        if (res.State != CellLayoutState.Resolved || res.View!.PCellOrigin is not { } origin)
        {
            _messageSink?.Warning("Edit PCell Parameters: this instance's cell is not PCell-generated.");
            return false;
        }
        if (WorkspaceRootDir is not { Length: > 0 } workspaceRoot)
        {
            _messageSink?.Error("Edit PCell Parameters: no workspace is open — generated cells need a workspace to live in.");
            return false;
        }

        var merged = new Dictionary<string, PCellValue>(origin.Parameters);
        foreach (var kv in newParameters) merged[kv.Key] = kv.Value;

        string newCellDir;
        IReadOnlyList<string>? editDiagnostics;
        try
        {
            newCellDir = PCells.GeneratedCellStore.GetOrCreate(
                workspaceRoot, origin.GeneratorId, merged, Technology, ResolvedTechPath, PCells.PCellLayerSelection.Default, out editDiagnostics);
        }
        catch (Exception ex)
        {
            // The instance keeps the parameters it had — a failed regeneration must leave the design
            // exactly as it was, never half-edited onto a cell that was never written.
            _messageSink?.Error($"'{origin.GeneratorId}' could not generate artwork for these parameters, " +
                                $"so the instance is unchanged. {ex.Message}");
            return false;
        }

        PCells.GeneratedCellStore.RecordSnapshot(
            Model, newCellDir, origin.GeneratorId, merged, ResolvedTechPath, PCells.PCellLayerSelection.Default);
        if (editDiagnostics is { Count: > 0 })
            foreach (var d in editDiagnostics) _messageSink?.Warning(d);

        string newCellRef;
        try { newCellRef = Path.GetRelativePath(InstanceBaseDir, newCellDir); }
        catch { newCellRef = newCellDir; }

        if (string.Equals(newCellRef, inst.CellRef, StringComparison.OrdinalIgnoreCase))
            return true; // resolved to the SAME cell (params round-tripped to their existing value) — nothing to do.

        if (!CheckNotCyclic(newCellRef)) return false;

        var after = LayoutGeometry.Clone(inst);
        after.CellRef = newCellRef;
        // pcell-parameter-handles.md R-pch-4b: a parameter-handle drag with a pinned anchor also
        // needs the instance to move, so that the edge the user did NOT grab holds its world
        // position. It rides in the SAME ReplaceInstanceCommand — one undo entry, and no window in
        // which the geometry has changed but the placement has not.
        if (translateDx != 0 || translateDy != 0) LayoutGeometry.TranslateBy(after, translateDx, translateDy);
        Execute(new Commands.Layout.ReplaceInstanceCommand(Model, instanceIndex, inst, after));
        IsDirty = true;
        return true;
    }
}
