using System.Text.Json;

namespace CircuitRF.Ui.Layout.PCells.Wire;

/// <summary>
/// One out-of-process generator script, presented to the rest of circuitRF as ordinary
/// <see cref="PCellGenerator"/> delegates.
///
/// <para><b>That is the whole design.</b> Above this class nothing knows a cell is generated by a
/// script: the geometry cache, the content-addressed cell store, copy-on-write parameter editing,
/// the snapshot table and the schematic↔layout generators all take a <see cref="PCellGenerator"/>
/// and keep working unchanged. It is the same rule <c>IExternalDeviceProvider</c> already states for
/// devices — in-process or out, circuitRF cannot tell — and it is what keeps an embedded interpreter
/// a swap of this class rather than a redesign.</para>
///
/// <para><b>One request at a time, enforced.</b> Two threads writing frames into one pipe interleave
/// them and the script then reads a header out of the middle of somebody else's JSON. The result is
/// a desynchronised stream that surfaces as corrupt geometry much later, so the lock is a
/// correctness requirement rather than a convenience.</para>
/// </summary>
public sealed class PCellWorkerProvider : IDisposable
{
    private readonly IPCellWorkerTransport _transport;
    private readonly Lock _gate = new();
    private readonly int _dbuPerMicron;

    private Dictionary<string, PCellWireGeneratorDecl>? _generators;
    private bool _disposed;

    public PCellWorkerProvider(IPCellWorkerTransport transport,
                               int dbuPerMicron = LayoutUnits.DefaultDbuPerMicron)
    {
        _transport = transport ?? throw new ArgumentNullException(nameof(transport));
        _dbuPerMicron = dbuPerMicron;
    }

    /// <summary>Where this generator is, for diagnostics.</summary>
    public string Origin => _transport.Origin;

    /// <summary>
    /// The generator ids this script offers, from its own <c>describe</c> — asked once and cached
    /// for the provider's lifetime.
    ///
    /// <para>This is the only source of the list. A manifest could have carried one and deliberately
    /// does not: a declaration that can disagree with the script is a cache with no invalidation,
    /// and the failure is a palette offering a cell the script cannot build.</para>
    /// </summary>
    public IReadOnlyCollection<string> GeneratorIds => EnsureDescribed().Keys;

    /// <summary>
    /// What this script says its generator's parameters are when nobody has said otherwise (wire
    /// version 4), or null for an id it does not offer.
    ///
    /// <para>Only parameters the generator actually DECLARED a default for appear — a parameter with
    /// none is absent rather than invented, so a placed cell never carries a value its generator
    /// never sanctioned.</para>
    /// </summary>
    public IReadOnlyDictionary<string, PCellValue>? DeclaredDefaults(string generatorId)
    {
        if (!EnsureDescribed().TryGetValue(generatorId, out var decl)) return null;

        var defaults = new Dictionary<string, PCellValue>(StringComparer.Ordinal);
        foreach (var p in decl.Parameters)
            if (p.Default is { } value && p.Name is { Length: > 0 })
                defaults[p.Name] = value;
        return defaults;
    }

    public bool TryGetGenerator(string generatorId, out PCellGenerator generator)
    {
        var declared = EnsureDescribed();
        if (!declared.TryGetValue(generatorId, out var decl))
        {
            generator = null!;
            return false;
        }

        generator = (parameters, technology, layerSelection)
            => Generate(decl, parameters, technology, layerSelection);
        return true;
    }

    // ── describe ──────────────────────────────────────────────────────────────

    private Dictionary<string, PCellWireGeneratorDecl> EnsureDescribed()
    {
        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            if (_generators is not null) return _generators;

            var frame = ExchangeLocked(PCellWireCodec.EncodeDescribe());

            PCellWireDescribeReply? reply;
            try { reply = JsonSerializer.Deserialize<PCellWireDescribeReply>(frame.Json, DescribeJson); }
            catch (JsonException ex) { throw Failed($"its description was not valid JSON: {ex.Message}", ex); }

            if (reply is null) throw Failed("it sent an empty description");
            if (!reply.Ok) throw Failed(reply.Error is { Length: > 0 } e ? e : "it refused to describe itself");

            if (reply.WireVersion != PCellWireVersion.Current)
                // Refused with both numbers named, never negotiated — negotiation means several code
                // paths of which the rare ones are wrong, and the message here says what to update.
                throw Failed(
                    $"it speaks PCell wire version {reply.WireVersion}; this build of circuitRF speaks " +
                    $"{PCellWireVersion.Current}. One of the two needs updating.");

            var map = new Dictionary<string, PCellWireGeneratorDecl>(StringComparer.Ordinal);
            foreach (var g in reply.Generators)
            {
                if (string.IsNullOrWhiteSpace(g.Id)) continue;
                // A second declaration under one id is not a preference the host can resolve, and
                // silently keeping either one would make which cell you get depend on file order.
                if (!map.TryAdd(g.Id, g))
                    throw Failed($"it declares '{g.Id}' twice.");
            }

            return _generators = map;
        }
    }

    // ── generate ──────────────────────────────────────────────────────────────

    private PCellResult Generate(
        PCellWireGeneratorDecl decl,
        IReadOnlyDictionary<string, PCellValue> parameters,
        Technology? technology,
        PCellLayerSelection layerSelection)
    {
        var request = PCellWireCodec.EncodeGenerate(
            decl.Id, parameters, decl.Parameters, technology, layerSelection, _dbuPerMicron);

        lock (_gate)
        {
            ObjectDisposedException.ThrowIf(_disposed, this);
            var frame = ExchangeLocked(request);
            try { return PCellWireCodec.DecodeGenerateReply(frame); }
            catch (PCellWireException ex)
            {
                // The generator id is named here because this layer knows it and the layer that
                // catches this does not always. Which INSTANCE failed is added higher up — a script
                // can only say what went wrong, and the host is the only side that knows which
                // placement asked.
                throw Failed($"'{decl.Id}' failed: {Strip(ex.Message)}", ex);
            }
        }
    }

    /// <summary>
    /// Writes one frame and reads its reply, serving whatever the script asks for along the way.
    /// Caller holds <see cref="_gate"/>.
    ///
    /// <para><b>Why serving happens here, inside the lock, rather than on another thread.</b> A
    /// service request arrives on the same pipe as the reply and must be answered before the reply
    /// can be read — so this is not a second conversation to be run concurrently, it is the middle of
    /// this one. Handing it to another thread would mean a second writer on <c>Requests</c>, which is
    /// exactly the interleaving <see cref="_gate"/> exists to prevent. Recursion is not a hazard
    /// either: servicing never re-enters this class, so the lock is never taken twice.</para>
    ///
    /// <para>The bound is a runaway guard, not a capacity limit — see
    /// <see cref="PCellWireHostServices.MaxServiceCallsPerExchange"/>.</para>
    /// </summary>
    private PCellWireFrame ExchangeLocked(in PCellWireFrame request)
    {
        try
        {
            PCellWireProtocol.WriteFrame(_transport.Requests, request);

            for (int served = 0; ; served++)
            {
                var frame = PCellWireProtocol.ReadFrame(_transport.Replies);

                if (!PCellWireHostServices.IsServiceRequest(frame, out string op))
                    return frame;

                if (served >= PCellWireHostServices.MaxServiceCallsPerExchange)
                    // Thrown bare rather than through Failed: the catch below adds this class's own
                    // framing exactly once, and going through Failed here would attach the script's
                    // error output twice.
                    throw new PCellWireException(
                        $"it asked circuitRF to perform more than {PCellWireHostServices.MaxServiceCallsPerExchange} " +
                        "operations while building one cell, which is beyond any plausible generator. " +
                        "It is most likely looping.");

                PCellWireProtocol.WriteFrame(_transport.Requests, PCellWireHostServices.Serve(frame, op));
            }
        }
        catch (PCellWireException ex) { throw Failed(Strip(ex.Message), ex); }
        catch (Exception ex) { throw Failed($"the connection failed: {ex.Message}", ex); }
    }

    /// <summary>
    /// One failure shape, with the script's own error output attached.
    ///
    /// <para>That attachment is the point rather than decoration: a script's traceback is very often
    /// the only description of what went wrong, and a user will not think to open a log for it.</para>
    /// </summary>
    private PCellWireException Failed(string what, Exception? inner = null)
    {
        string tail = _transport.RecentErrorOutput;
        string message = $"The PCell generator '{_transport.Origin}': {what}"
                       + (tail.Length > 0 ? $"{Environment.NewLine}--- generator output ---{Environment.NewLine}{tail}" : "");
        return inner is null ? new PCellWireException(message) : new PCellWireException(message, inner);
    }

    /// <summary>Drops the codec's own "The PCell generator …:" preamble so a wrapped message does
    /// not say it twice.</summary>
    private static string Strip(string message)
    {
        const string Prefix = "The PCell generator ";
        if (!message.StartsWith(Prefix, StringComparison.Ordinal)) return message;
        int colon = message.IndexOf(": ", Prefix.Length, StringComparison.Ordinal);
        return colon > 0 ? message[(colon + 2)..] : message;
    }

    public void Dispose()
    {
        lock (_gate)
        {
            if (_disposed) return;
            _disposed = true;
        }

        // Asked to shut down before being torn down: a script gets to close its own files rather
        // than being killed mid-write. Failure here is expected when it has already gone.
        try { PCellWireProtocol.WriteFrame(_transport.Requests, PCellWireCodec.EncodeShutdown()); }
        catch { /* already gone, or wedged — Dispose below handles both */ }

        _transport.Dispose();
    }

    private static readonly JsonSerializerOptions DescribeJson = new()
    {
        PropertyNamingPolicy        = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
        Converters                  =
        {
            new System.Text.Json.Serialization.JsonStringEnumConverter(JsonNamingPolicy.CamelCase),
            // Wire version 4: a parameter declaration carries a DEFAULT, which is a PCellValue and so
            // needs the same encoding every other value uses (schema §3). Without this the reply's
            // own converter list silently disagrees with the one that encodes values elsewhere.
            new PCellValueJsonConverter(),
        },
    };
}
