// Generated by circuitRF for Palace (brief-em3d-7). Do not edit: circuitRF rewrites this file from
// the setup, and an unchanged file reuses the mesh beside it. Units: micrometres (Palace L0 = 1e-6).
// Run by circuitRF as:  gmsh model.geo -3 -o model.msh    (writes entities.txt beside it)

SetFactory("OpenCASCADE");
Geometry.OCCBooleanPreserveNumbering = 1;
Geometry.OCCBoundsUseStl = 1;
e = 0.001;

// ---- solids, in construction order -------------------------------------------------------
// RO4350: Dielectric, RO4350, order 1
v = newv; Box(v) = {-37474.05725, -38024.05725, 35, 84948.1145, 76048.1145, 508};
s0[] = {v};
// air: Air, Air, order 2
v = newv; Box(v) = {-37474.05725, -38024.05725, 543, 84948.1145, 76048.1145, 37509.05725};
s1[] = {v};
// Top Copper (1 oz)/1: Conductor, Top Copper (1 oz), order 3
cl[] = {};
p = newp;
Point(p + 0) = {0, -550, 543};
Point(p + 1) = {10000, -550, 543};
Point(p + 2) = {10000, 550, 543};
Point(p + 3) = {0, 550, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
cl[] += {c};
s = news; Plane Surface(s) = {cl[]};
bs[] = {s};
ex[] = Extrude {0, 0, 35} { Surface{bs[]}; };
s2[] = {ex[1]};

// ---- disjoint by construction order: each solid loses what a higher-order solid takes -----
s1[] = BooleanDifference{ Volume{s1[]}; Delete; }{ Volume{s2[]}; };

// ---- the air box, and the background: what no solid claims inside it --------------------
bx = newv; Box(bx) = {-37474.05725, -38024.05725, 35, 84948.1145, 76048.1145, 38017.05725};
bg[] = BooleanDifference{ Volume{bx}; Delete; }{ Volume{s0[], s1[], s2[]}; };
// Conductors are voids: their surfaces carry Palace's conductivity boundary.
Recursive Delete { Volume{s2[]}; }

// ---- sheets and port sheets --------------------------------------------------------------
// port/1: from airbox/zmin to Top Copper (1 oz)/1
p = newp;
Point(p + 0) = {0, -550, 35};
Point(p + 1) = {0, 550, 35};
Point(p + 2) = {0, 550, 543};
Point(p + 3) = {0, -550, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
s = news; Plane Surface(s) = {c}; p0[] = {s};
// port/2: from airbox/zmin to Top Copper (1 oz)/1
p = newp;
Point(p + 0) = {10000, -550, 35};
Point(p + 1) = {10000, 550, 35};
Point(p + 2) = {10000, 550, 543};
Point(p + 3) = {10000, -550, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
s = news; Plane Surface(s) = {c}; p1[] = {s};

// ---- one fragment: imprints the shared faces and the sheets, splits no volume -------------
frag[] = BooleanFragments{ Volume{s0[], s1[], bg[]}; Delete; }{ Surface{p0[], p1[]}; Delete; };
allV[] = Volume{:};
allS[] = Surface{:};
single[] = CombinedBoundary{ Volume{allV[]}; };
For k In {0:#single[]-1}
  single[k] = Abs(single[k]);
EndFor
claimed[] = {};

// ---- surfaces, recovered by what circuitRF placed; each face claimed once ------------------
// air box xmin
f0[] = Surface In BoundingBox{-37474.05725 - e, -38024.05725 - e, 35 - e, -37474.05725 + e, 38024.05725 + e, 38052.05725 + e};
f0[] -= claimed[];
claimed[] += f0[];
// air box xmax
f1[] = Surface In BoundingBox{47474.05725 - e, -38024.05725 - e, 35 - e, 47474.05725 + e, 38024.05725 + e, 38052.05725 + e};
f1[] -= claimed[];
claimed[] += f1[];
// air box ymin
f2[] = Surface In BoundingBox{-37474.05725 - e, -38024.05725 - e, 35 - e, 47474.05725 + e, -38024.05725 + e, 38052.05725 + e};
f2[] -= claimed[];
claimed[] += f2[];
// air box ymax
f3[] = Surface In BoundingBox{-37474.05725 - e, 38024.05725 - e, 35 - e, 47474.05725 + e, 38024.05725 + e, 38052.05725 + e};
f3[] -= claimed[];
claimed[] += f3[];
// air box zmin
f4[] = Surface In BoundingBox{-37474.05725 - e, -38024.05725 - e, 35 - e, 47474.05725 + e, 38024.05725 + e, 35 + e};
f4[] -= claimed[];
claimed[] += f4[];
// air box zmax
f5[] = Surface In BoundingBox{-37474.05725 - e, -38024.05725 - e, 38052.05725 - e, 47474.05725 + e, 38024.05725 + e, 38052.05725 + e};
f5[] -= claimed[];
claimed[] += f5[];
// port/1
q0[] = Surface In BoundingBox{0 - e, -550 - e, 35 - e, 0 + e, 550 + e, 543 + e};
q0[] -= claimed[];
claimed[] += q0[];
// port/2
q1[] = Surface In BoundingBox{10000 - e, -550 - e, 35 - e, 10000 + e, 550 + e, 543 + e};
q1[] -= claimed[];
claimed[] += q1[];
voids[] = single[];
voids[] -= claimed[];
// conductor Top Copper (1 oz)/1
c2[] = Surface In BoundingBox{0 - e, -550 - e, 543 - e, 10000 + e, 550 + e, 578 + e};
x[] = c2[];
x[] -= voids[];
c2[] -= x[];
c2[] -= claimed[];
claimed[] += c2[];
rest[] = single[];
rest[] -= claimed[];

// ---- physical groups: attributes are circuitRF's (groups.json) --------------------------
Physical Volume("RO4350", 1) = {s0[]};
Physical Volume("air", 2) = {s1[]};
Physical Surface("Top Copper (1 oz)/1", 3) = {c2[]};
Physical Volume("background", 4) = {bg[]};
Physical Surface("port/1", 5) = {q0[]};
Physical Surface("port/2", 6) = {q1[]};
Physical Surface("airbox/xmin", 7) = {f0[]};
Physical Surface("airbox/xmax", 8) = {f1[]};
Physical Surface("airbox/ymin", 9) = {f2[]};
Physical Surface("airbox/ymax", 10) = {f3[]};
Physical Surface("airbox/zmin", 11) = {f4[]};
Physical Surface("airbox/zmax", 12) = {f5[]};

// ---- the entity table circuitRF checks before it believes this mesh (R-em3d7-3b) ---------
Printf("# circuitRF entity table: group <attribute> <count> <volume tags lost in the fragment>") > "entities.txt";
lost[] = s0[];
lost[] -= allV[];
Printf("group 1 %g %g", #s0[], #lost[]) >> "entities.txt";
lost[] = s1[];
lost[] -= allV[];
Printf("group 2 %g %g", #s1[], #lost[]) >> "entities.txt";
Printf("group 3 %g 0", #c2[]) >> "entities.txt";
lost[] = bg[];
lost[] -= allV[];
Printf("group 4 %g %g", #bg[], #lost[]) >> "entities.txt";
Printf("group 5 %g 0", #q0[]) >> "entities.txt";
Printf("group 6 %g 0", #q1[]) >> "entities.txt";
Printf("group 7 %g 0", #f0[]) >> "entities.txt";
Printf("group 8 %g 0", #f1[]) >> "entities.txt";
Printf("group 9 %g 0", #f2[]) >> "entities.txt";
Printf("group 10 %g 0", #f3[]) >> "entities.txt";
Printf("group 11 %g 0", #f4[]) >> "entities.txt";
Printf("group 12 %g 0", #f5[]) >> "entities.txt";
Printf("all_volumes %g", #allV[]) >> "entities.txt";
Printf("classified_volumes %g", #s0[] + #s1[] + #bg[]) >> "entities.txt";
Printf("all_surfaces %g", #allS[]) >> "entities.txt";
Printf("single_sided %g", #single[]) >> "entities.txt";
Printf("unclassified_single_sided %g", #rest[]) >> "entities.txt";

// ---- the initial mesh: Palace's adaptive refinement converges the answer ------------------
// Largest element per material: 0.1 of its wavelength at 10 GHz;
// 0.2 of the smallest at conductors and sheets; at most 1/4 of each port
// sheet's smaller side at the ports; growing by 1.3.
Mesh.MeshSizeMax = 2997.92458;
Mesh.MeshSizeFromPoints = 0;
Mesh.MeshSizeExtendFromBoundary = 0;
Mesh.MeshSizeFromCurvature = 12;
Field[1] = Constant; Field[1].VIn = 1567.040281055; Field[1].VolumesList = {s0[]};
Field[2] = Constant; Field[2].VIn = 2997.92458; Field[2].VolumesList = {s1[]};
Field[3] = Constant; Field[3].VIn = 2997.92458; Field[3].VolumesList = {bg[]};
Field[4] = Distance; Field[4].SurfacesList = {c2[]}; Field[4].Sampling = 50;
Field[5] = Threshold; Field[5].InField = 4; Field[5].SizeMin = 313.408056211; Field[5].SizeMax = 2997.92458; Field[5].DistMin = 313.408056211; Field[5].DistMax = 9261.796468841;
Field[6] = Distance; Field[6].SurfacesList = {q0[], q1[]}; Field[6].Sampling = 50;
Field[7] = Threshold; Field[7].InField = 6; Field[7].SizeMin = 127; Field[7].SizeMax = 2997.92458; Field[7].DistMin = 127; Field[7].DistMax = 9696.7486;
Field[8] = Min; Field[8].FieldsList = {1, 2, 3, 5, 7};
Background Field = 8;
Mesh.ElementOrder = 2;
Mesh.HighOrderOptimize = 2;
Mesh.MshFileVersion = 2.2;
Mesh.Binary = 1;
