//! shadergen — brief-em3d-28 R-em3d28-1c: ONE WGSL source, cross-compiled offline by naga's LIBRARY
//! into the three shader languages route A's backends load (Metal, D3D11, Vulkan).
//!
//!   shadergen <in.wgsl> <out-dir>           write <stem>.metal, <stem>.hlsl, <stem>.spv
//!   shadergen --check <in.wgsl> <out-dir>   exit 1 unless every output records the WGSL's hash
//!
//! Every output RECORDS the SHA-256 of the WGSL's exact bytes, so a test can fail when someone edits
//! the WGSL without regenerating (gate 1b):
//!   - .metal / .hlsl: the first line is
//!     `// generated by tools/ShaderGen from <file>.wgsl — do not edit; wgsl-sha256: <hex>`
//!   - .spv: an `OpSourceExtension "wgsl-sha256:<hex>"` instruction (opcode 4), at the end of the
//!     debug section's first group (after OpString/OpSource, before OpName). Not OpModuleProcessed, the
//!     semantically closer instruction: that one needs SPIR-V 1.1, and spirv-val rejects it in the 1.0
//!     module a Vulkan 1.0 driver requires (checked, spirv-tools 2024).
//!
//! The bindings are STATED here rather than left to naga's defaults, which is why no fix-up is needed
//! (the naga CLI has no MSL binding map and emits `[[user(fake0)]]` — findings §5.4):
//!   - uniform block @group(0) @binding(0): MSL `[[buffer(1)]]` in every entry point (the vertex
//!     buffer is stage_in from buffer 0 through the pipeline's vertex descriptor); HLSL `register(b0)`;
//!     SPIR-V descriptor set 0, binding 0.
//!
//! Deterministic: every option is set explicitly (naga's SPIR-V default flips a DEBUG flag with the
//! build profile, which would make a debug-built tool emit different words).

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use naga::back::{hlsl, msl, spv};
use naga::valid::{Capabilities, ValidationFlags, Validator};
use sha2::{Digest, Sha256};

/// Uniform block binding in the WGSL: @group(0) @binding(0).
const UNIFORM: naga::ResourceBinding = naga::ResourceBinding { group: 0, binding: 0 };
/// MSL argument-table slot of the uniform block (slot 0 is the vertex buffer).
const MSL_UNIFORM_BUFFER: u8 = 1;
/// MSL 2.3: macOS 11+.
const MSL_VERSION: (u8, u8) = (2, 3);
/// SPIR-V 1.0: every Vulkan 1.0 driver.
const SPV_VERSION: (u8, u8) = (1, 0);

/// OpSourceExtension: "a string describing ... the source" — legal in every SPIR-V version, and ignored
/// by every consumer. Carries `wgsl-sha256:<hex>`.
const OP_SOURCE_EXTENSION: u32 = 4;

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let result = match args.as_slice() {
        [flag, wgsl, out] if flag == "--check" => check(Path::new(wgsl), Path::new(out)),
        [wgsl, out] => generate(Path::new(wgsl), Path::new(out)).map(|_| true),
        _ => {
            eprintln!("usage: shadergen <in.wgsl> <out-dir> | shadergen --check <in.wgsl> <out-dir>");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::from(1),
        Err(e) => {
            eprintln!("shadergen: {e}");
            ExitCode::from(2)
        }
    }
}

fn hex_sha256(bytes: &[u8]) -> String {
    Sha256::digest(bytes).iter().map(|b| format!("{b:02x}")).collect()
}

fn outputs(wgsl: &Path, out: &Path) -> Result<(String, PathBuf, PathBuf, PathBuf), String> {
    let stem = wgsl.file_stem().and_then(|s| s.to_str()).ok_or("the WGSL path has no file stem")?;
    let file = wgsl.file_name().and_then(|s| s.to_str()).ok_or("the WGSL path has no file name")?;
    Ok((
        file.to_string(),
        out.join(format!("{stem}.metal")),
        out.join(format!("{stem}.hlsl")),
        out.join(format!("{stem}.spv")),
    ))
}

fn header(file: &str, hash: &str) -> String {
    format!("// generated by tools/ShaderGen from {file} — do not edit; wgsl-sha256: {hash}\n")
}

fn generate(wgsl_path: &Path, out: &Path) -> Result<(), String> {
    let bytes = std::fs::read(wgsl_path).map_err(|e| format!("{}: {e}", wgsl_path.display()))?;
    let text = std::str::from_utf8(&bytes).map_err(|e| format!("{}: not UTF-8: {e}", wgsl_path.display()))?;
    let hash = hex_sha256(&bytes);
    let (file, metal_path, hlsl_path, spv_path) = outputs(wgsl_path, out)?;

    let module = naga::front::wgsl::parse_str(text).map_err(|e| e.emit_to_string(text))?;
    let info = Validator::new(ValidationFlags::all(), Capabilities::empty())
        .validate(&module)
        .map_err(|e| e.emit_to_string(text))?;

    // ---- MSL ----
    let mut resources = msl::EntryPointResources::default();
    resources.resources.insert(
        UNIFORM,
        msl::BindTarget { buffer: Some(MSL_UNIFORM_BUFFER), ..Default::default() },
    );
    let mut msl_opts = msl::Options {
        lang_version: MSL_VERSION,
        fake_missing_bindings: false,
        ..Default::default()
    };
    for ep in &module.entry_points {
        msl_opts.per_entry_point_map.insert(ep.name.clone(), resources.clone());
    }
    let msl_pipe = msl::PipelineOptions::default(); // stage_in (vertex_pulling_transform = false)
    let (msl_src, _) = msl::write_string(&module, &info, &msl_opts, &msl_pipe).map_err(|e| format!("MSL: {e}"))?;

    // ---- HLSL ----
    let mut hlsl_opts = hlsl::Options {
        shader_model: hlsl::ShaderModel::V5_0,
        fake_missing_bindings: false,
        ..Default::default()
    };
    hlsl_opts.binding_map.insert(UNIFORM, hlsl::BindTarget { space: 0, register: 0, ..Default::default() });
    let mut hlsl_src = String::new();
    let hlsl_pipe = hlsl::PipelineOptions::default();
    hlsl::Writer::new(&mut hlsl_src, &hlsl_opts, &hlsl_pipe)
        .write(&module, &info, None)
        .map_err(|e| format!("HLSL: {e}"))?;

    // ---- SPIR-V ----
    let mut spv_opts = spv::Options {
        lang_version: SPV_VERSION,
        flags: spv::WriterFlags::ADJUST_COORDINATE_SPACE | spv::WriterFlags::LABEL_VARYINGS | spv::WriterFlags::CLAMP_FRAG_DEPTH,
        fake_missing_bindings: false,
        ..Default::default()
    };
    spv_opts.binding_map.insert(UNIFORM, spv::BindingInfo { descriptor_set: 0, binding: 0, binding_array_size: None });
    let words = spv::write_vec(&module, &info, &spv_opts, None).map_err(|e| format!("SPIR-V: {e}"))?;
    let words = insert_hash_string(&words, &format!("wgsl-sha256:{hash}"))?;

    // The SPIR-V we wrote must still be a module naga itself accepts and validates.
    let spv_bytes: Vec<u8> = words.iter().flat_map(|w| w.to_le_bytes()).collect();
    let reread = naga::front::spv::parse_u8_slice(&spv_bytes, &naga::front::spv::Options::default())
        .map_err(|e| format!("SPIR-V re-read failed after inserting the hash: {e}"))?;
    Validator::new(ValidationFlags::all(), Capabilities::all())
        .validate(&reread)
        .map_err(|e| format!("SPIR-V re-validation failed: {e:?}"))?;
    if recorded_spv_hash(&spv_bytes).as_deref() != Some(hash.as_str()) {
        return Err("SPIR-V: the recorded hash does not read back".into());
    }

    std::fs::create_dir_all(out).map_err(|e| format!("{}: {e}", out.display()))?;
    let head = header(&file, &hash);
    write(&metal_path, format!("{head}{msl_src}").as_bytes())?;
    write(&hlsl_path, format!("{head}{hlsl_src}").as_bytes())?;
    write(&spv_path, &spv_bytes)?;
    println!("wgsl-sha256 {hash}");
    for p in [&metal_path, &hlsl_path, &spv_path] {
        println!("  wrote {}", p.display());
    }
    Ok(())
}

fn write(p: &Path, b: &[u8]) -> Result<(), String> {
    std::fs::write(p, b).map_err(|e| format!("{}: {e}", p.display()))
}

/// Opcodes that may precede the end of the debug section's first group (logical layout §2.4:
/// capabilities, extensions, imports, memory model, entry points, execution modes, then debug 7a).
fn is_preamble_or_source_debug(op: u32) -> bool {
    // Capability 17, Extension 10, ExtInstImport 11, MemoryModel 14, EntryPoint 15, ExecutionMode 16,
    // ExecutionModeId 331; String 7, Source 3, SourceExtension 4, SourceContinued 2.
    matches!(op, 17 | 10 | 11 | 14 | 15 | 16 | 331 | 7 | 3 | 4 | 2)
}

/// Inserts `OpSourceExtension "<text>"` after the last 7a debug instruction and before the first
/// OpName (7b) — or the first annotation or type when there is no name — the place the layout allows it.
fn insert_hash_string(words: &[u32], text: &str) -> Result<Vec<u32>, String> {
    if words.len() < 5 || words[0] != 0x0723_0203 {
        return Err("SPIR-V: bad magic".into());
    }
    let mut i = 5;
    let mut at = None;
    while i < words.len() {
        let (count, op) = ((words[i] >> 16) as usize, words[i] & 0xffff);
        if count == 0 {
            return Err("SPIR-V: zero-length instruction".into());
        }
        if !is_preamble_or_source_debug(op) {
            at = Some(i);
            break;
        }
        i += count;
    }
    let at = at.ok_or("SPIR-V: no name, annotation or type section")?;
    let lit = string_words(text);
    let mut ins = vec![(((1 + lit.len()) as u32) << 16) | OP_SOURCE_EXTENSION];
    ins.extend(lit);
    let mut out = Vec::with_capacity(words.len() + ins.len());
    out.extend_from_slice(&words[..at]);
    out.extend(ins);
    out.extend_from_slice(&words[at..]);
    Ok(out)
}

/// A SPIR-V literal string: UTF-8, NUL-terminated, zero-padded to a word, little-endian in each word.
fn string_words(s: &str) -> Vec<u32> {
    let mut b = s.as_bytes().to_vec();
    b.push(0);
    while b.len() % 4 != 0 {
        b.push(0);
    }
    b.chunks(4).map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect()
}

/// The hash an `.spv` records, from its OpSourceExtension "wgsl-sha256:…" instruction.
fn recorded_spv_hash(bytes: &[u8]) -> Option<String> {
    if bytes.len() % 4 != 0 {
        return None;
    }
    let words: Vec<u32> = bytes.chunks(4).map(|c| u32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect();
    let mut i = 5;
    while i < words.len() {
        let (count, op) = ((words[i] >> 16) as usize, words[i] & 0xffff);
        if count == 0 {
            return None;
        }
        if op == OP_SOURCE_EXTENSION {
            let lit: Vec<u8> = words[i + 1..i + count].iter().flat_map(|w| w.to_le_bytes()).collect();
            let s = String::from_utf8_lossy(&lit[..lit.iter().position(|&c| c == 0).unwrap_or(lit.len())]).to_string();
            if let Some(h) = s.strip_prefix("wgsl-sha256:") {
                return Some(h.to_string());
            }
        }
        i += count;
    }
    None
}

fn recorded_text_hash(text: &str) -> Option<String> {
    let first = text.lines().next()?;
    first.split("wgsl-sha256: ").nth(1).map(|h| h.trim().to_string())
}

fn check(wgsl_path: &Path, out: &Path) -> Result<bool, String> {
    let bytes = std::fs::read(wgsl_path).map_err(|e| format!("{}: {e}", wgsl_path.display()))?;
    let hash = hex_sha256(&bytes);
    let (_, metal, hlsl, spv) = outputs(wgsl_path, out)?;
    let mut ok = true;
    for p in [&metal, &hlsl, &spv] {
        let recorded = match std::fs::read(p) {
            Err(e) => {
                println!("MISSING  {} ({e})", p.display());
                ok = false;
                continue;
            }
            Ok(b) if p.extension().is_some_and(|e| e == "spv") => recorded_spv_hash(&b),
            Ok(b) => recorded_text_hash(&String::from_utf8_lossy(&b)),
        };
        match recorded {
            Some(h) if h == hash => println!("current  {}", p.display()),
            Some(h) => {
                println!("STALE    {} records {h}, the WGSL is {hash}", p.display());
                ok = false;
            }
            None => {
                println!("NO HASH  {}", p.display());
                ok = false;
            }
        }
    }
    Ok(ok)
}
