using System;
using System.Collections.Generic;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;
using CircuitRF.Core.Design;
using CircuitRF.Ui.Schematic;

namespace CircuitRF.Ui.ViewModels;

/// <summary>
/// Staging VM for the Add/Edit Analysis dialog (analysis-authoring.md §4.2).
///
/// Holds the type selector (DC / S-Parameter / Harmonic Balance), name, enabled flag, and
/// per-type body VMs. Call <see cref="BuildAnalysis"/> on OK to commit; returns null when
/// validation fails. The static constructors handle both "Add new" and "Edit existing".
///
/// Expression preview is available via <see cref="ComputePreview"/> — it reuses the
/// DesignScope.Build + Evaluator pattern from ParameterRowViewModel with no fork (§4.3).
/// </summary>
public sealed partial class AnalysisEditorViewModel : ObservableObject
{
    public enum AnalysisKind { DC, SP, HB, LP, LPP }

    private readonly SchematicEditModel _model;
    private readonly List<string>       _existingNames;
    private readonly string?            _editingName;

    // ── Type selection ────────────────────────────────────────────────────────

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsDc), nameof(IsSp), nameof(IsHb), nameof(IsLp), nameof(IsLpp))]
    private AnalysisKind _type = AnalysisKind.DC;

    public bool IsDc  => Type == AnalysisKind.DC;
    public bool IsSp  => Type == AnalysisKind.SP;
    public bool IsHb  => Type == AnalysisKind.HB;
    public bool IsLp  => Type == AnalysisKind.LP;
    public bool IsLpp => Type == AnalysisKind.LPP;

    // ── Name + Enabled ────────────────────────────────────────────────────────

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(NameError), nameof(CanCommit))]
    private string _name = "";

    [ObservableProperty] private bool _enabled = true;

    /// <summary>Non-null when the current Name is invalid or conflicts with an existing analysis.</summary>
    public string? NameError { get; private set; }

    /// <summary>True when Name is valid and the dialog OK button may be enabled.</summary>
    public bool CanCommit => NameError is null && Name.Trim().Length > 0;

    // ── Per-type body VMs ─────────────────────────────────────────────────────

    /// <summary>S-Parameter body (Layer 2 enriches this stub with segment editing).</summary>
    public SpBodyViewModel SpBody { get; }

    /// <summary>HB body (Layer 3 enriches this stub with all field editing).</summary>
    public HbBodyViewModel HbBody { get; }

    // ── Constructor: Add new ──────────────────────────────────────────────────

    public AnalysisEditorViewModel(SchematicEditModel model, AnalysisKind initialType = AnalysisKind.DC)
    {
        _model         = model;
        _existingNames = model.Analyses.Select(a => a.Name).ToList();
        _editingName   = null;
        _type          = initialType;
        _name          = NextFreeName(initialType, _existingNames);
        SpBody         = new SpBodyViewModel(model);
        HbBody         = new HbBodyViewModel(model);
        ValidateName();
    }

    // ── Constructor: Edit existing ────────────────────────────────────────────

    public AnalysisEditorViewModel(SchematicEditModel model, Analysis existing)
    {
        _model         = model;
        _existingNames = model.Analyses.Select(a => a.Name).ToList();
        _editingName   = existing.Name;
        _name          = existing.Name;
        _enabled       = existing.Enabled;

        switch (existing)
        {
            case SParameterAnalysis sp:
                _type  = AnalysisKind.SP;
                SpBody = SpBodyViewModel.FromAnalysis(sp, model);
                HbBody = new HbBodyViewModel(model);
                break;
            case HarmonicBalanceAnalysis hb:
                _type  = AnalysisKind.HB;
                SpBody = new SpBodyViewModel(model);
                HbBody = HbBodyViewModel.FromAnalysis(hb, model);
                break;
            default: // DcAnalysis or unknown
                _type  = AnalysisKind.DC;
                SpBody = new SpBodyViewModel(model);
                HbBody = new HbBodyViewModel(model);
                break;
        }
        ValidateName();
    }

    // ── Validation ────────────────────────────────────────────────────────────

    partial void OnNameChanged(string value) => ValidateName();

    // When the type changes, refresh the Name to the next free name for the new type —
    // but only if the current name still looks auto-generated (letters-only prefix + digits suffix).
    // A custom name the user typed (e.g. "MyAmplifierSP") is left alone.
    partial void OnTypeChanged(AnalysisKind value)
    {
        if (IsAutoGeneratedName(Name))
            Name = NextFreeName(value, _existingNames, _editingName);
    }

    private static bool IsAutoGeneratedName(string name)
    {
        var n = name.Trim();
        if (n.Length == 0) return true;
        int i = 0;
        while (i < n.Length && char.IsLetter(n[i])) i++;
        // Must have ≥1 letter prefix AND ≥1 digit suffix (all digits after the prefix).
        return i > 0 && i < n.Length && n[i..].All(char.IsDigit);
    }

    private void ValidateName()
    {
        string name = Name.Trim();
        if (name.Length == 0)
        {
            NameError = "Name is required.";
        }
        else if (!IsValidName(name))
        {
            NameError = "Name must start with a letter and contain only letters, digits, and underscores.";
        }
        else if (_existingNames.Contains(name, StringComparer.OrdinalIgnoreCase)
              && !string.Equals(name, _editingName, StringComparison.OrdinalIgnoreCase))
        {
            NameError = $"An analysis named '{name}' already exists.";
        }
        else
        {
            NameError = null;
        }
        OnPropertyChanged(nameof(NameError));
        OnPropertyChanged(nameof(CanCommit));
    }

    private static bool IsValidName(string s)
        => s.Length > 0 && char.IsLetter(s[0])
           && s.All(c => char.IsLetterOrDigit(c) || c == '_');

    // ── Name helper ───────────────────────────────────────────────────────────

    /// <summary>
    /// Returns the lowest free typed name ("DC1"/"SP1"/"HB1"/"LP1"/"LPP1") not already in
    /// <paramref name="existing"/>, optionally excluding <paramref name="excluding"/> (the name being edited).
    /// </summary>
    public static string NextFreeName(AnalysisKind kind, IList<string> existing, string? excluding = null)
    {
        string prefix = kind switch
        {
            AnalysisKind.DC  => "DC",
            AnalysisKind.SP  => "SP",
            AnalysisKind.HB  => "HB",
            AnalysisKind.LP  => "LP",
            AnalysisKind.LPP => "LPP",
            _                => "DC",
        };
        for (int n = 1; n <= 999; n++)
        {
            string candidate = $"{prefix}{n}";
            if (!existing.Contains(candidate, StringComparer.OrdinalIgnoreCase)
                || string.Equals(candidate, excluding, StringComparison.OrdinalIgnoreCase))
                return candidate;
        }
        return prefix + "1";
    }

    // ── Expression preview ────────────────────────────────────────────────────

    /// <summary>
    /// Evaluates <paramref name="expression"/> against the schematic's current VARs and returns
    /// "≈ value", or "" for blank / bare-number / unresolvable. Same evaluator as
    /// <see cref="ParameterRowViewModel"/> — no fork (§4.3).
    /// </summary>
    public string ComputePreview(string expression)
        => AnalysisPreviewHelper.ComputePreview(expression, _model);

    // ── Build ─────────────────────────────────────────────────────────────────

    /// <summary>
    /// Returns the staged <see cref="Analysis"/> when validation passes, or null.
    /// Called by the dialog code-behind on OK.
    /// </summary>
    public Analysis? BuildAnalysis()
    {
        if (!CanCommit) return null;
        string name = Name.Trim();

        switch (Type)
        {
            case AnalysisKind.DC:
                return new DcAnalysis(name) { Enabled = Enabled };

            case AnalysisKind.SP:
                var sp = new SParameterAnalysis(name, SpBody.BuildSweeps());
                sp.Enabled = Enabled;
                return sp;

            case AnalysisKind.HB:
                return HbBody.BuildAnalysis(name, Enabled);

            default:
                return null;
        }
    }
}
