// circuitRF F0 spike -- case A: one 1 mil gold bond wire over ground.
// HAND-WRITTEN SPIKE MATERIAL (brief-em3d-1 R-em3d1-2). Not generated by circuitRF, and nothing
// under src/ may read or reuse it. Units: micrometres (Palace config: "L0": 1.0e-6).
//
// Run:  gmsh case.geo -3 -o case.msh      (writes entities.txt beside it)
//
// Geometry (all variants):
//   PEC box x[-1500,1500] y[-1000,1000] z[0,1100]; its floor z=0 is the ground plane.
//   Substrate z[0,100], er 9.8, tand 0, full footprint.  Air above.
//   Two 100x100 um PEC pads (zero-thickness sheets) on the substrate at x = -500 and +500 (centres).
//   A lumped port sheet from each pad's outer edge (x = -550, +550) down to the ground, 100 um wide.
//   The wire is a VOID in the air; its surface carries Palace's finite-conductivity boundary.
//   Wire axis polyline, y = 0: (-475, a) (-325, a+150) (325, a+150) (475, a), z measured from
//   the substrate top, a = half the cross-section height -> wBond loop height 150 um exactly
//   (max z - min z of the axis, wbond.md 3.1a).
//   Without a foot, the end segments are extended below the pad plane and the wire is cut at
//   z = 100: the wire lands on the pad on a flat face (a real contact area, not a line).
//   With a foot (FOOT = 1), a horizontal run of length 2d lies flat on each pad, outward
//   from the end point, bottom face on the pad (em-3d.md 6.6).

SetFactory("OpenCASCADE");
Geometry.OCCBooleanPreserveNumbering = 1;
Geometry.OCCBoundsUseStl = 1;          // tight bounding boxes (OCC boxes are loose on curved faces)

// ---- variant -------------------------------------------------------------------------------
DefineConstant[ SHAPE = 0 ];   // 0 = round, 1 = perimeter-matched hexagon (side pi d / 6, flat bottom)
DefineConstant[ FOOT  = 0 ];   // 1 = wedge foot of 2d at each end (hexagon only)

// ---- dimensions ----------------------------------------------------------------------------
d   = 25.4;                    // wire diameter, 1 mil
Lx  = 3000; Ly = 2000; H = 1100; hs = 100;
loop = 150;
e   = 1e-3;                    // bounding-box slack
s   = Pi * d / 6;              // hexagon side
hh  = Sqrt(3) * s;             // hexagon height, flat to flat
If (SHAPE == 0)
  a = d / 2;
Else
  a = hh / 2;
EndIf
z0 = hs + a;

// Axis nodes (x, z).  Ends extended below the pad plane unless a foot is drawn.
If (FOOT == 1)
  nx[] = {-475 - 2*d, -475, -325, 325, 475, 475 + 2*d};
  nz[] = {z0, z0, z0 + loop, z0 + loop, z0, z0};
Else
  ext = 3 * a;                 // along the end segment, outward; puts the whole end face below z = hs
  c45 = Sqrt(0.5);
  nx[] = {-475 - ext*c45, -325, 325, 475 + ext*c45};
  nz[] = {z0 - ext*c45, z0 + loop, z0 + loop, z0 - ext*c45};
EndIf
N = #nx[];

// ---- the wire solid ------------------------------------------------------------------------
If (SHAPE == 0)
  // Round: one cylinder per segment, extended past each interior node and cut on the bisector
  // plane there, so neighbouring segments meet face to face (a mitre). Spheres at the joints were
  // tried first: a sphere of the wire's own radius is TANGENT to both cylinders and OpenCASCADE's
  // union fails on it (BOPAlgo_AlertIntersectionOfPairOfShapesFailed).
  BIG = 1e4;
  parts[] = {};
  For i In {0:N-2}
    tx = nx[i+1]-nx[i]; tz = nz[i+1]-nz[i]; L = Sqrt(tx*tx+tz*tz); tx /= L; tz /= L;
    xa = nx[i]; za = nz[i]; xb = nx[i+1]; zb = nz[i+1];
    If (i > 0)   xa -= 2*d*tx; za -= 2*d*tz; EndIf
    If (i < N-2) xb += 2*d*tx; zb += 2*d*tz; EndIf
    c = newv; Cylinder(c) = {xa, 0, za, xb-xa, 0, zb-za, d/2};
    For j In {0:1}
      k = i + j;
      If (k > 0 && k < N-1)
        ax = nx[k]-nx[k-1]; az = nz[k]-nz[k-1]; La = Sqrt(ax*ax+az*az);
        bx = nx[k+1]-nx[k]; bz = nz[k+1]-nz[k]; Lb = Sqrt(bx*bx+bz*bz);
        bnx = ax/La + bx/Lb; bnz = az/La + bz/Lb; Lbn = Sqrt(bnx*bnx+bnz*bnz); bnx /= Lbn; bnz /= Lbn;
        th = Atan2(-bnz, bnx);            // rotation about +y taking +x to the bisector normal
        hb = newv;
        If (j == 1) Box(hb) = {nx[k] - BIG, -BIG, nz[k] - BIG, BIG, 2*BIG, 2*BIG}; EndIf
        If (j == 0) Box(hb) = {nx[k], -BIG, nz[k] - BIG, BIG, 2*BIG, 2*BIG}; EndIf
        Rotate {{0,1,0}, {nx[k], 0, nz[k]}, th} { Volume{hb}; }
        c2[] = BooleanIntersection{ Volume{c}; Delete; }{ Volume{hb}; Delete; };
        c = c2[0];
      EndIf
    EndFor
    parts[] += c;
  EndFor
  wire[] = BooleanUnion{ Volume{parts[0]}; Delete; }{ Volume{parts[{1:N-2}]}; Delete; };
Else
  // Hexagon swept with "up" held fixed: each cross-section vertex (u along y, v along the
  // segment's in-plane normal). Interior nodes are mitred: offset v along m = (n1+n2)/(1+n1.n2).
  hu[] = { s/2,  s,  s/2, -s/2, -s, -s/2};
  hv[] = { hh/2, 0, -hh/2, -hh/2, 0,  hh/2};
  For i In {0:N-1}
    If (i == 0)
      tx = nx[1]-nx[0]; tz = nz[1]-nz[0]; L = Sqrt(tx*tx+tz*tz); mx = -tz/L; mz = tx/L;
    ElseIf (i == N-1)
      tx = nx[i]-nx[i-1]; tz = nz[i]-nz[i-1]; L = Sqrt(tx*tx+tz*tz); mx = -tz/L; mz = tx/L;
    Else
      ax = nx[i]-nx[i-1]; az = nz[i]-nz[i-1]; La = Sqrt(ax*ax+az*az);
      bx = nx[i+1]-nx[i]; bz = nz[i+1]-nz[i]; Lb = Sqrt(bx*bx+bz*bz);
      n1x = -az/La; n1z = ax/La; n2x = -bz/Lb; n2z = bx/Lb;
      dn = 1 + n1x*n2x + n1z*n2z;
      mx = (n1x+n2x)/dn; mz = (n1z+n2z)/dn;
    EndIf
    For k In {0:5}
      pt[i*6+k] = newp;
      Point(pt[i*6+k]) = {nx[i] + hv[k]*mx, hu[k], nz[i] + hv[k]*mz};
    EndFor
  EndFor
  // Ring edges at every node, longitudinal edges between nodes.
  For i In {0:N-1}
    For k In {0:5}
      ring[i*6+k] = newc; Line(ring[i*6+k]) = {pt[i*6+k], pt[i*6+(k+1)%6]};
    EndFor
  EndFor
  For i In {0:N-2}
    For k In {0:5}
      lon[i*6+k] = newc; Line(lon[i*6+k]) = {pt[i*6+k], pt[(i+1)*6+k]};
    EndFor
  EndFor
  faces[] = {};
  cl = newcl; Curve Loop(cl) = {ring[{0:5}]};             f = news; Plane Surface(f) = {cl}; faces[] += f;
  cl = newcl; Curve Loop(cl) = {ring[{(N-1)*6:(N-1)*6+5}]}; f = news; Plane Surface(f) = {cl}; faces[] += f;
  For i In {0:N-2}
    For k In {0:5}
      cl = newcl; Curve Loop(cl) = {ring[i*6+k], lon[i*6+(k+1)%6], -ring[(i+1)*6+k], -lon[i*6+k]};
      f = news; Plane Surface(f) = {cl}; faces[] += f;
    EndFor
  EndFor
  sl = newsl; Surface Loop(sl) = {faces[]};
  wire[] = {newv}; Volume(wire[0]) = {sl};
EndIf

If (FOOT == 0)
  below = newv; Box(below) = {-Lx, -Ly, -H, 2*Lx, 2*Ly, H + hs};
  wire[] = BooleanDifference{ Volume{wire[]}; Delete; }{ Volume{below}; Delete; };
EndIf

// ---- domain --------------------------------------------------------------------------------
sub = newv; Box(sub) = {-Lx/2, -Ly/2, 0,  Lx, Ly, hs};
air = newv; Box(air) = {-Lx/2, -Ly/2, hs, Lx, Ly, H - hs};
// Q6 variant: the wire is MESHED as a gold volume instead of being a void with a boundary condition.
air2[] = BooleanDifference{ Volume{air}; Delete; }{ Volume{wire[]}; };

pad1 = news; Rectangle(pad1) = {-550, -50, hs, 100, 100};
pad2 = news; Rectangle(pad2) = { 450, -50, hs, 100, 100};
// Port sheets in the plane x = -550 and x = +550, y[-50,50], z[0,hs].
For side In {0:1}
  xp = (side == 0) ? -550 : 550;
  q1 = newp; Point(q1) = {xp, -50, 0};  q2 = newp; Point(q2) = {xp, 50, 0};
  q3 = newp; Point(q3) = {xp, 50, hs};  q4 = newp; Point(q4) = {xp, -50, hs};
  c1 = newc; Line(c1) = {q1, q2}; c2 = newc; Line(c2) = {q2, q3};
  c3 = newc; Line(c3) = {q3, q4}; c4 = newc; Line(c4) = {q4, q1};
  cl = newcl; Curve Loop(cl) = {c1, c2, c3, c4};
  port[side] = news; Plane Surface(port[side]) = {cl};
EndFor

frag[] = BooleanFragments{ Volume{air2[], sub, wire[]}; Delete; }{ Surface{pad1, pad2, port[0], port[1]}; Delete; };

// ---- recover every named object by what is known about it (no stored indices) -------------
vWire[] = Volume In BoundingBox{-600, -30, hs-e, 600, 30, H/2};
vAir[] = Volume In BoundingBox{-Lx/2-e, -Ly/2-e, hs-e, Lx/2+e, Ly/2+e, H+e};
vAir[] -= vWire[];
vSub[] = Volume In BoundingBox{-Lx/2-e, -Ly/2-e, -e,   Lx/2+e, Ly/2+e, hs+e};
sP1[]  = Surface In BoundingBox{-550-e, -50-e, -e, -550+e, 50+e, hs+e};
sP2[]  = Surface In BoundingBox{ 550-e, -50-e, -e,  550+e, 50+e, hs+e};
sPad[] = Surface In BoundingBox{-550-e, -50-e, hs-e, -450+e, 50+e, hs+e};
sPad[] += Surface In BoundingBox{ 450-e, -50-e, hs-e,  550+e, 50+e, hs+e};
sWireAll[] = Surface In BoundingBox{-600, -30, hs-e, 600, 30, H/2};
sContact[] = Surface In BoundingBox{-600, -30, hs-e, 600, 30, hs+e};
sWire[] = sWireAll[];
sWire[] -= sContact[];
sOuter[] = Surface In BoundingBox{-Lx/2-e, -Ly/2-e, -e, -Lx/2+e, Ly/2+e, H+e};
sOuter[] += Surface In BoundingBox{ Lx/2-e, -Ly/2-e, -e,  Lx/2+e, Ly/2+e, H+e};
sOuter[] += Surface In BoundingBox{-Lx/2-e, -Ly/2-e, -e,  Lx/2+e, -Ly/2+e, H+e};
sOuter[] += Surface In BoundingBox{-Lx/2-e,  Ly/2-e, -e,  Lx/2+e,  Ly/2+e, H+e};
sOuter[] += Surface In BoundingBox{-Lx/2-e, -Ly/2-e, -e,  Lx/2+e,  Ly/2+e, e};
sOuter[] += Surface In BoundingBox{-Lx/2-e, -Ly/2-e, H-e, Lx/2+e,  Ly/2+e, H+e};

Physical Volume("air", 1)        = {vAir[]};
Physical Volume("substrate", 2)  = {vSub[]};
Physical Surface("outer_pec", 3) = {sOuter[]};
Physical Surface("pads", 4)      = {sPad[]};
Physical Surface("port1", 5)     = {sP1[]};
Physical Surface("port2", 6)     = {sP2[]};
Physical Surface("wire", 7)      = {sWire[]};
Physical Volume("gold", 8)       = {vWire[]};

// The entity table circuitRF would read back and check (overview 1e): name, expected, found, tags.
Printf("# name count tags  (SHAPE=%g FOOT=%g)", SHAPE, FOOT) > "entities.txt";
Printf("air %g", #vAir[]) >> "entities.txt";
Printf("gold_volume %g", #vWire[]) >> "entities.txt";
Printf("substrate %g", #vSub[]) >> "entities.txt";
Printf("outer_pec %g", #sOuter[]) >> "entities.txt";
Printf("pads %g", #sPad[]) >> "entities.txt";
Printf("port1 %g", #sP1[]) >> "entities.txt";
Printf("port2 %g", #sP2[]) >> "entities.txt";
Printf("wire %g", #sWire[]) >> "entities.txt";
Printf("contact %g", #sContact[]) >> "entities.txt";
// Did the fragment keep the input volume tags (Geometry.OCCBooleanPreserveNumbering)?
Printf("tag_substrate before %g after %g", sub, vSub[0]) >> "entities.txt";
Printf("tag_air before %g after %g", air2[0], vAir[0]) >> "entities.txt";
Printf("fragment_returned %g entities", #frag[]) >> "entities.txt";
allS[] = Surface{:};
Printf("all_surfaces %g", #allS[]) >> "entities.txt";
allV[] = Volume{:};
Printf("all_volumes %g", #allV[]) >> "entities.txt";

// ---- mesh ----------------------------------------------------------------------------------
Mesh.MeshSizeMax = 150;
Mesh.MeshSizeMin = 2;
Mesh.MeshSizeFromPoints = 0;
Mesh.MeshSizeExtendFromBoundary = 0;
Field[1] = Distance; Field[1].SurfacesList = {sWire[], sContact[]}; Field[1].Sampling = 40;
Field[2] = Threshold; Field[2].InField = 1;
Field[2].SizeMin = 2.0; Field[2].SizeMax = 150; Field[2].DistMin = 1; Field[2].DistMax = 800;
Field[3] = Distance; Field[3].SurfacesList = {sPad[], sP1[], sP2[]}; Field[3].Sampling = 20;
Field[4] = Threshold; Field[4].InField = 3;
Field[4].SizeMin = 15; Field[4].SizeMax = 150; Field[4].DistMin = 0; Field[4].DistMax = 500;
Field[6] = Constant; Field[6].VolumesList = {vWire[]}; Field[6].VIn = 4; Field[6].VOut = 1e22;
Field[5] = Min; Field[5].FieldsList = {2, 4, 6};
Background Field = 5;
Mesh.ElementOrder = 2;
Mesh.HighOrderOptimize = 2;
Mesh.MshFileVersion = 2.2;
Mesh.Binary = 1;
