#!/bin/bash
set -e

rm -f /usr/bin/circuitrf

update-desktop-database -q 2>/dev/null || true
update-mime-database /usr/share/mime 2>/dev/null || true
gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true
