using System.Globalization;
using System.Numerics;
using CircuitRF.Core.Design;
using CircuitRF.Core.Elaboration;
using CircuitRF.Core.Netlist;
using CircuitRF.Engine;
using CircuitRF.Engine.HarmonicBalance;
using Xunit;
using Xunit.Abstractions;

namespace CircuitRF.Engine.Tests.HarmonicBalance;

/// <summary>
/// Generates the self-consistent two-tone regression golden for Hero 5 by running the circuitRF HB
/// engine and writing the converged V and I_nl over the mixIndex axis to CSV.
///
/// Label: SELF-GENERATED REGRESSION — NOT independently validated against other simulators.
/// Run with:  dotnet test --filter GenerateHero5Golden
/// The test passes if every swept point converges, then writes the golden files.
/// </summary>
public class Hero5GoldenGenerator(ITestOutputHelper output)
{
    // Bounded golden sweep (the cnl sweeps further; two-tone is stiffer at high drive — keep the
    // regression in the well-converged low/mid-drive range; the owner can extend after a convergence
    // study). Generator and regression MUST use the same range.
    public const double GoldenStart = -20, GoldenStop = -8, GoldenStep = 4;

    internal static string Hero5Dir()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            var cand = Path.Combine(dir, "testdata", "Hero5");
            if (Directory.Exists(cand)) return cand;
            dir = Path.GetDirectoryName(dir);
        }
        throw new DirectoryNotFoundException("testdata/Hero5 not found");
    }

    [Fact]
    public void GenerateHero5Golden()
    {
        var dir       = Hero5Dir();
        var (lib, tb) = CnlReader.ReadFile(Path.Combine(dir, "hero5.cnl"));
        var netlist   = new Elaborator(lib).Elaborate(tb);
        var hba       = tb.Analyses.OfType<HarmonicBalanceAnalysis>().First();
        var p         = HbEngine.Resolve(hba, netlist.ResolvedGlobals)
                        with { SweepStart = GoldenStart, SweepStop = GoldenStop, SweepStep = GoldenStep };

        output.WriteLine($"Hero 5: f1={p.ToneFreqsHz[0]/1e9:F4} f2={p.ToneFreqsHz[1]/1e9:F4} GHz, " +
                         $"MaxMixOrder={p.MaxMixOrder}, sweep {p.SweepStart}..{p.SweepStop} step {p.SweepStep} dBm");

        var result = new HbEngine(netlist, tb).Run(p);
        var grid   = result.Grid!;

        int converged = result.Trace.Steps.Count(s => s.Converged);
        int total     = result.Trace.TotalSteps;
        output.WriteLine($"Convergence: {converged}/{total} sweep points converged.");
        Assert.True(converged == total,
            $"Some sweep points did not converge ({converged}/{total}). Cannot write golden.");

        var names = result.InterfaceNodeNames;
        int gateIdx  = Array.FindIndex(names, n => n.Contains("n_gate",  StringComparison.OrdinalIgnoreCase));
        int drainIdx = Array.FindIndex(names, n => n.Contains("n_drain", StringComparison.OrdinalIgnoreCase));
        Assert.True(gateIdx >= 0 && drainIdx >= 0);

        WriteGolden(dir, "hero5_self_V_n_gate.csv",   "n_gate",  "V (interface voltage)",       result, grid, result.V,   gateIdx,  isV: true);
        WriteGolden(dir, "hero5_self_V_n_drain.csv",  "n_drain", "V (interface voltage)",       result, grid, result.V,   drainIdx, isV: true);
        WriteGolden(dir, "hero5_self_INl_n_gate.csv", "n_gate",  "I_nl (device current, A)",    result, grid, result.INl, gateIdx,  isV: false);
        WriteGolden(dir, "hero5_self_INl_n_drain.csv","n_drain", "I_nl (device current, A)",    result, grid, result.INl, drainIdx, isV: false);

        output.WriteLine("Golden files written to " + dir);
    }

    private static void WriteGolden(string dir, string filename, string nodeName, string quantity,
        HbResult r, MixingGrid grid, Complex[][,] data, int nodeIdx, bool isV)
    {
        var path = Path.Combine(dir, filename);
        using var w = new StreamWriter(path);
        double f1 = r.ToneFreqsHz[0], f2 = r.ToneFreqsHz[1];

        w.WriteLine("# SELF-GENERATED REGRESSION DATA — NOT INDEPENDENTLY VALIDATED");
        w.WriteLine("# Generated by circuitRF two-tone HB engine (Phase 4c).");
        w.WriteLine("# A future cross-check against other simulators with the identical SDD FET is owed.");
        w.WriteLine($"# Circuit: hero5.cnl  |  Node: {nodeName}  |  Quantity: {quantity}");
        w.WriteLine($"# f1 = {f1/1e9:F4} GHz, f2 = {f2/1e9:F4} GHz  |  MaxMixOrder = {grid.MaxMixOrder}");
        w.WriteLine("# Columns: k1; k2; freq_Hz; Pave_dBm; Re; Im");
        w.WriteLine("k1; k2; freq_Hz; Pave_dBm; Re; Im");

        var ci = CultureInfo.InvariantCulture;
        for (int si = 0; si < r.SweepValues.Length; si++)
        {
            double pIn = r.SweepValues[si];
            for (int m = 0; m < grid.MixCount; m++)
            {
                var (k1, k2) = grid.ToneOf(m);
                double freqHz = k1 * f1 + k2 * f2;
                Complex v = data[si][nodeIdx, m];
                double im = m == 0 ? 0.0 : v.Imaginary;   // (0,0) DC is real
                w.WriteLine($"{k1.ToString(ci)}; {k2.ToString(ci)}; {freqHz.ToString(ci)}; " +
                            $"{pIn.ToString(ci)}; {v.Real.ToString("G8", ci)}; {im.ToString("G8", ci)}");
            }
        }
    }
}
