using System.Numerics;
using CircuitRF.Core.Design;
using CircuitRF.Core.Elaboration;
using CircuitRF.Core.Netlist;
using CircuitRF.Engine;
using CircuitRF.Engine.HarmonicBalance;
using Xunit;
using Xunit.Abstractions;

namespace CircuitRF.Engine.Tests.HarmonicBalance;

/// <summary>
/// Phase 4c Step 6 — two-tone engine integration on Hero 5.
///
/// Runs the full <see cref="HbEngine.Run"/> two-tone path on testdata/Hero5/hero5.cnl (real
/// netlist: V_nTone two-tone drive, abs(freq)-banded source/load, GaN SDD) over a short low-drive
/// sweep, and verifies:
///   - the result carries the mixing lattice and V/INl are on the mixIndex axis (M = 31 for order 5);
///   - every swept point converges;
///   - the DC operating point is preserved (gate ≈ -3.05 V, drain ≈ 48 V);
///   - the carriers (1,0)/(0,1) develop and the IM3 product (2,-1) — never driven — is generated
///     by the device mixing, landing at the expected frequency.
///
/// This is the wiring/structure gate; the physics golden + 3:1 slope are the Step-8 Hero-5 gate.
/// </summary>
public class Hero5IntegrationTests(ITestOutputHelper output)
{
    private static string Hero5Dir()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            var cand = Path.Combine(dir, "testdata", "Hero5");
            if (Directory.Exists(cand)) return cand;
            dir = Path.GetDirectoryName(dir);
        }
        throw new DirectoryNotFoundException("testdata/Hero5 not found");
    }

    [Fact]
    public void RunTwoTone_Hero5_ConvergesAndMixesOnMixIndexAxis()
    {
        var dir       = Hero5Dir();
        var (lib, tb) = CnlReader.ReadFile(Path.Combine(dir, "hero5.cnl"));
        var netlist   = new Elaborator(lib).Elaborate(tb);
        var hba       = tb.Analyses.OfType<HarmonicBalanceAnalysis>().First();
        var p         = HbEngine.Resolve(hba, netlist.ResolvedGlobals);

        // Keep the test fast and in the clean low-drive region: -20..-16 dBm (5 points).
        p = p with { SweepStop = -16.0 };
        Assert.True(p.IsMultiTone);
        Assert.Equal(2, p.ToneFreqsHz.Length);

        var engine = new HbEngine(netlist, tb);
        var result = engine.Run(p);

        // ── Result is on the 2-D mixing-lattice axis ──
        Assert.True(result.IsMultiTone);
        Assert.NotNull(result.Grid);
        var grid = result.Grid!;
        int M = grid.MixCount;
        Assert.Equal(1 + 5 * 6, M);                          // order-5 diamond
        double f1 = result.ToneFreqsHz[0], f2 = result.ToneFreqsHz[1];

        int gate  = Array.FindIndex(result.InterfaceNodeNames, s => s.Contains("gate",  StringComparison.OrdinalIgnoreCase));
        int drain = Array.FindIndex(result.InterfaceNodeNames, s => s.Contains("drain", StringComparison.OrdinalIgnoreCase));
        Assert.True(gate >= 0 && drain >= 0);

        int nSweep = result.SweepValues.Length;
        Assert.Equal(nSweep, result.V.Length);
        Assert.Equal(M, result.V[0].GetLength(1));           // second axis = mixIndex

        // ── Every point converged ──
        foreach (var step in result.Trace.Steps)
            Assert.True(step.Converged,
                $"Two-tone HB did not converge at Pavl={step.Pin_dBm:F1} dBm " +
                $"(final ‖F‖={step.IterTrace.LastOrDefault()?.ResidualNorm:E3}).");

        // ── Inspect the top (highest-drive) point ──
        var V  = result.V[nSweep - 1];
        int c10 = grid.IndexOf(1, 0), c01 = grid.IndexOf(0, 1);
        int im3 = grid.IndexOf(2, -1), im2 = grid.IndexOf(1, -1);
        Assert.True(c10 >= 0 && c01 >= 0 && im3 >= 0 && im2 >= 0);

        output.WriteLine($"Hero5 two-tone: N={result.InterfaceNodeNames.Length}, M={M}, sweep {nSweep} pts");
        output.WriteLine($"  DC: gate={V[gate,0].Real:F3} V, drain={V[drain,0].Real:F3} V");
        output.WriteLine($"  carrier(1,0)={V[drain,c10].Magnitude:E3}  carrier(0,1)={V[drain,c01].Magnitude:E3}");
        output.WriteLine($"  IM2 (1,-1)={V[drain,im2].Magnitude:E3}   IM3 (2,-1)={V[drain,im3].Magnitude:E3}");

        // ── DC operating point preserved by the self-consistent (0,0) solve ──
        Assert.Equal(-3.05, V[gate, 0].Real, 0.5);
        Assert.True(V[drain, 0].Real > 40.0, $"drain DC={V[drain,0].Real:F2} V, expected ≈48 V");

        // ── Carriers developed; IM3 generated by mixing (not driven) ──
        Assert.True(V[drain, c10].Magnitude > 1e-5, "carrier (1,0) not developed");
        Assert.True(V[drain, c01].Magnitude > 1e-5, "carrier (0,1) not developed");
        Assert.True(result.INl[nSweep - 1][drain, im3].Magnitude > 1e-12,
            "IM3 (2,-1) mixing product absent — two-tone mixing failed.");

        // ── mixIndex axis is interpretable: (1,0) → f1, (2,-1) → 2f1-f2 ──
        Assert.Equal(f1,            grid.FrequencyOf(c10, f1, f2), 1.0);
        Assert.Equal(2 * f1 - f2,   grid.FrequencyOf(im3, f1, f2), 1.0);
    }
}
