using System.Numerics;
using CircuitRF.Core.Design;
using CircuitRF.Core.Elaboration;
using CircuitRF.Core.Netlist;
using CircuitRF.Engine;
using CircuitRF.Engine.HarmonicBalance;
using RfCore.Data;
using Xunit;
using Xunit.Abstractions;

namespace CircuitRF.Engine.Tests.HarmonicBalance;

/// <summary>
/// Phase 4c Step 6 — two-tone engine integration on Hero 5.
///
/// Runs the full <see cref="HbEngine.Run"/> two-tone path on testdata/Hero5/hero5.cnl (real
/// netlist: V_nTone two-tone drive, abs(freq)-banded source/load, GaN SDD) over a short low-drive
/// sweep, and verifies:
///   - the result carries the mixing lattice and V/INl are on the mixIndex axis (M = 31 for order 5);
///   - every swept point converges;
///   - the DC operating point is preserved (gate ≈ -3.05 V, drain ≈ 48 V);
///   - the carriers (1,0)/(0,1) develop and the IM3 product (2,-1) — never driven — is generated
///     by the device mixing, landing at the expected frequency.
///
/// This is the wiring/structure gate; the physics golden + 3:1 slope are the Step-8 Hero-5 gate.
/// </summary>
public class Hero5IntegrationTests(ITestOutputHelper output)
{
    private static string Hero5Dir()
    {
        var dir = AppContext.BaseDirectory;
        while (dir is not null)
        {
            var cand = Path.Combine(dir, "testdata", "Hero5");
            if (Directory.Exists(cand)) return cand;
            dir = Path.GetDirectoryName(dir);
        }
        throw new DirectoryNotFoundException("testdata/Hero5 not found");
    }

    [Fact]
    public void RunTwoTone_Hero5_ConvergesAndMixesOnMixIndexAxis()
    {
        var dir       = Hero5Dir();
        var (lib, tb) = CnlReader.ReadFile(Path.Combine(dir, "hero5.cnl"));
        var netlist   = new Elaborator(lib).Elaborate(tb);
        var hba       = tb.Analyses.OfType<HarmonicBalanceAnalysis>().First();
        var p         = HbEngine.Resolve(hba, netlist.ResolvedGlobals);

        // Keep the test fast and in the clean low-drive region: -20..-16 dBm (5 points).
        p = p with { SweepStop = -16.0 };
        Assert.True(p.IsMultiTone);
        Assert.Equal(2, p.ToneFreqsHz.Length);

        var engine = new HbEngine(netlist, tb);
        var ds = engine.Run(p);
        var sweepVals = ds["Converged"].Axes[0].Values;

        // ── Result is on the 2-D mixing-lattice axis ──
        Assert.True(p.IsMultiTone);
        var grid = new MixingGrid(p.MaxMixOrder);
        int M = grid.MixCount;
        Assert.Equal(1 + 5 * 6, M);                          // order-5 diamond
        double f1 = p.ToneFreqsHz[0], f2 = p.ToneFreqsHz[1];

        string[] nodeNames = ds["V"].Axes[0].Labels!;
        int gate  = Array.FindIndex(nodeNames, s => s.Contains("gate",  StringComparison.OrdinalIgnoreCase));
        int drain = Array.FindIndex(nodeNames, s => s.Contains("drain", StringComparison.OrdinalIgnoreCase));
        Assert.True(gate >= 0 && drain >= 0);

        int nSweep = sweepVals.Length;
        Assert.Equal(M, ds["V"].Axes[1].Length);              // second axis = mixIndex

        // ── Every point converged ──
        for (int si = 0; si < nSweep; si++)
            Assert.True((double)ds["Converged"][si] > 0.5,
                $"Two-tone HB did not converge at Pavl={sweepVals[si]:F1} dBm.");

        // ── Inspect the top (highest-drive) point ──
        int c10 = grid.IndexOf(1, 0), c01 = grid.IndexOf(0, 1);
        int im3 = grid.IndexOf(2, -1), im2 = grid.IndexOf(1, -1);
        Assert.True(c10 >= 0 && c01 >= 0 && im3 >= 0 && im2 >= 0);

        int last = nSweep - 1;
        double gateDc  = ((Complex)ds["V"][gate,  0, last]).Real;
        double drainDc = ((Complex)ds["V"][drain, 0, last]).Real;
        output.WriteLine($"Hero5 two-tone: N={nodeNames.Length}, M={M}, sweep {nSweep} pts");
        output.WriteLine($"  DC: gate={gateDc:F3} V, drain={drainDc:F3} V");
        output.WriteLine($"  carrier(1,0)={((Complex)ds["V"][drain,c10,last]).Magnitude:E3}  " +
                         $"carrier(0,1)={((Complex)ds["V"][drain,c01,last]).Magnitude:E3}");
        output.WriteLine($"  IM2 (1,-1)={((Complex)ds["V"][drain,im2,last]).Magnitude:E3}   " +
                         $"IM3 (2,-1)={((Complex)ds["V"][drain,im3,last]).Magnitude:E3}");

        // ── DC operating point preserved by the self-consistent (0,0) solve ──
        Assert.Equal(-3.05, gateDc, 0.5);
        Assert.True(drainDc > 40.0, $"drain DC={drainDc:F2} V, expected ≈48 V");

        // ── Carriers developed; IM3 generated by mixing (not driven) ──
        Assert.True(((Complex)ds["V"][drain, c10, last]).Magnitude > 1e-5, "carrier (1,0) not developed");
        Assert.True(((Complex)ds["V"][drain, c01, last]).Magnitude > 1e-5, "carrier (0,1) not developed");
        Assert.True(((Complex)ds["I:M1:d"][im3, last]).Magnitude > 1e-12,
            "IM3 (2,-1) mixing product absent — two-tone mixing failed.");

        // ── mixIndex axis is interpretable: (1,0) → f1, (2,-1) → 2f1-f2 ──
        Assert.Equal(f1,            grid.FrequencyOf(c10, f1, f2), 1.0);
        Assert.Equal(2 * f1 - f2,   grid.FrequencyOf(im3, f1, f2), 1.0);
    }
}
