// Generated by circuitRF for Palace (brief-em3d-7). Do not edit: circuitRF rewrites this file from
// the setup, and an unchanged file reuses the mesh beside it. Units: micrometres (Palace L0 = 1e-6).
// Run by circuitRF as:  gmsh model.geo -3 -o model.msh    (writes entities.txt beside it)

SetFactory("OpenCASCADE");
Geometry.OCCBooleanPreserveNumbering = 1;
Geometry.OCCBoundsUseStl = 1;
e = 0.001;

// ---- solids, in construction order -------------------------------------------------------
// RO4350: Dielectric, RO4350, order 1
v = newv; Box(v) = {-3000, -4000, 35, 9000, 8000, 508};
s0[] = {v};
// air: Air, Air, order 2
v = newv; Box(v) = {-3000, -4000, 543, 9000, 8000, 3035};
s1[] = {v};
// Top Copper (1 oz)/A: Conductor, Top Copper (1 oz), order 3
cl[] = {};
p = newp;
Point(p + 0) = {0, 500, 543};
Point(p + 1) = {3000, 500, 543};
Point(p + 2) = {3000, 1000, 543};
Point(p + 3) = {0, 1000, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
cl[] += {c};
s = news; Plane Surface(s) = {cl[]};
bs[] = {s};
ex[] = Extrude {0, 0, 35} { Surface{bs[]}; };
s2[] = {ex[1]};
// Top Copper (1 oz)/B: Conductor, Top Copper (1 oz), order 4
cl[] = {};
p = newp;
Point(p + 0) = {0, -1000, 543};
Point(p + 1) = {3000, -1000, 543};
Point(p + 2) = {3000, -500, 543};
Point(p + 3) = {0, -500, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
cl[] += {c};
s = news; Plane Surface(s) = {cl[]};
bs[] = {s};
ex[] = Extrude {0, 0, 35} { Surface{bs[]}; };
s3[] = {ex[1]};
// via/1: Conductor, Plated Through-Hole, order 5
v = newv; Cylinder(v) = {2800, 750, 35, 0, 0, 543, 150};
s4[] = {v};
// via/1/fill: Air, Air, order 6
v = newv; Cylinder(v) = {2800, 750, 35, 0, 0, 543, 125};
s5[] = {v};
// via/2: Conductor, Plated Through-Hole, order 7
v = newv; Cylinder(v) = {2800, -750, 35, 0, 0, 543, 150};
s6[] = {v};
// via/2/fill: Air, Air, order 8
v = newv; Cylinder(v) = {2800, -750, 35, 0, 0, 543, 125};
s7[] = {v};

// ---- disjoint by construction order: each solid loses what a higher-order solid takes -----
s0[] = BooleanDifference{ Volume{s0[]}; Delete; }{ Volume{s4[], s5[], s6[], s7[]}; };
s1[] = BooleanDifference{ Volume{s1[]}; Delete; }{ Volume{s2[], s3[], s4[], s5[], s6[], s7[]}; };
s2[] = BooleanDifference{ Volume{s2[]}; Delete; }{ Volume{s4[], s5[]}; };
s3[] = BooleanDifference{ Volume{s3[]}; Delete; }{ Volume{s6[], s7[]}; };
s4[] = BooleanDifference{ Volume{s4[]}; Delete; }{ Volume{s5[]}; };
s6[] = BooleanDifference{ Volume{s6[]}; Delete; }{ Volume{s7[]}; };

// ---- the air box, and the background: what no solid claims inside it --------------------
bx = newv; Box(bx) = {-3000, -4000, 35, 9000, 8000, 3543};
bg[] = BooleanDifference{ Volume{bx}; Delete; }{ Volume{s0[], s1[], s2[], s3[], s4[], s5[], s6[], s7[]}; };
// Conductors are voids: their surfaces carry Palace's conductivity boundary.
Recursive Delete { Volume{s2[], s3[], s4[], s6[]}; }

// ---- sheets and port sheets --------------------------------------------------------------
// port/1: from airbox/zmin to Top Copper (1 oz)/A
p = newp;
Point(p + 0) = {0, 500, 35};
Point(p + 1) = {0, 1000, 35};
Point(p + 2) = {0, 1000, 543};
Point(p + 3) = {0, 500, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
s = news; Plane Surface(s) = {c}; p0[] = {s};
// port/2: from airbox/zmin to Top Copper (1 oz)/B
p = newp;
Point(p + 0) = {0, -1000, 35};
Point(p + 1) = {0, -500, 35};
Point(p + 2) = {0, -500, 543};
Point(p + 3) = {0, -1000, 543};
l = newc;
Line(l + 0) = {p + 0, p + 1};
Line(l + 1) = {p + 1, p + 2};
Line(l + 2) = {p + 2, p + 3};
Line(l + 3) = {p + 3, p + 0};
c = newcl; Curve Loop(c) = {l:l + 3};
s = news; Plane Surface(s) = {c}; p1[] = {s};

// ---- one fragment: imprints the shared faces and the sheets, splits no volume -------------
frag[] = BooleanFragments{ Volume{s0[], s1[], s5[], s7[], bg[]}; Delete; }{ Surface{p0[], p1[]}; Delete; };
allV[] = Volume{:};
allS[] = Surface{:};
single[] = CombinedBoundary{ Volume{allV[]}; };
For k In {0:#single[]-1}
  single[k] = Abs(single[k]);
EndFor
claimed[] = {};

// ---- surfaces, recovered by what circuitRF placed; each face claimed once ------------------
// port/1
q0[] = Surface In BoundingBox{0 - e, 500 - e, 35 - e, 0 + e, 1000 + e, 543 + e};
q0[] -= claimed[];
claimed[] += q0[];
// port/2
q1[] = Surface In BoundingBox{0 - e, -1000 - e, 35 - e, 0 + e, -500 + e, 543 + e};
q1[] -= claimed[];
claimed[] += q1[];
// air box xmin
f0[] = Surface In BoundingBox{-3000 - e, -4000 - e, 35 - e, -3000 + e, 4000 + e, 3578 + e};
f0[] -= claimed[];
claimed[] += f0[];
// air box xmax
f1[] = Surface In BoundingBox{6000 - e, -4000 - e, 35 - e, 6000 + e, 4000 + e, 3578 + e};
f1[] -= claimed[];
claimed[] += f1[];
// air box ymin
f2[] = Surface In BoundingBox{-3000 - e, -4000 - e, 35 - e, 6000 + e, -4000 + e, 3578 + e};
f2[] -= claimed[];
claimed[] += f2[];
// air box ymax
f3[] = Surface In BoundingBox{-3000 - e, 4000 - e, 35 - e, 6000 + e, 4000 + e, 3578 + e};
f3[] -= claimed[];
claimed[] += f3[];
// air box zmin
f4[] = Surface In BoundingBox{-3000 - e, -4000 - e, 35 - e, 6000 + e, 4000 + e, 35 + e};
f4[] -= claimed[];
claimed[] += f4[];
// air box zmax
f5[] = Surface In BoundingBox{-3000 - e, -4000 - e, 3578 - e, 6000 + e, 4000 + e, 3578 + e};
f5[] -= claimed[];
claimed[] += f5[];
voids[] = single[];
voids[] -= claimed[];
// conductor via/1
c4[] = Surface In BoundingBox{2650 - e, 600 - e, 35 - e, 2950 + e, 900 + e, 578 + e};
x[] = c4[];
x[] -= voids[];
c4[] -= x[];
c4[] -= claimed[];
claimed[] += c4[];
// conductor via/2
c6[] = Surface In BoundingBox{2650 - e, -900 - e, 35 - e, 2950 + e, -600 + e, 578 + e};
x[] = c6[];
x[] -= voids[];
c6[] -= x[];
c6[] -= claimed[];
claimed[] += c6[];
// conductor Top Copper (1 oz)/A
c2[] = Surface In BoundingBox{0 - e, 500 - e, 543 - e, 3000 + e, 1000 + e, 578 + e};
x[] = c2[];
x[] -= voids[];
c2[] -= x[];
c2[] -= claimed[];
claimed[] += c2[];
// conductor Top Copper (1 oz)/B
c3[] = Surface In BoundingBox{0 - e, -1000 - e, 543 - e, 3000 + e, -500 + e, 578 + e};
x[] = c3[];
x[] -= voids[];
c3[] -= x[];
c3[] -= claimed[];
claimed[] += c3[];
rest[] = single[];
rest[] -= claimed[];

// ---- physical groups: attributes are circuitRF's (groups.json) --------------------------
Physical Volume("RO4350", 1) = {s0[]};
Physical Volume("air", 2) = {s1[]};
Physical Surface("Top Copper (1 oz)/A", 3) = {c2[]};
Physical Surface("Top Copper (1 oz)/B", 4) = {c3[]};
Physical Surface("via/1", 5) = {c4[]};
Physical Volume("via/1/fill", 6) = {s5[]};
Physical Surface("via/2", 7) = {c6[]};
Physical Volume("via/2/fill", 8) = {s7[]};
Physical Volume("background", 9) = {bg[]};
Physical Surface("port/1", 10) = {q0[]};
Physical Surface("port/2", 11) = {q1[]};
Physical Surface("airbox/xmin", 12) = {f0[]};
Physical Surface("airbox/xmax", 13) = {f1[]};
Physical Surface("airbox/ymin", 14) = {f2[]};
Physical Surface("airbox/ymax", 15) = {f3[]};
Physical Surface("airbox/zmin", 16) = {f4[]};
Physical Surface("airbox/zmax", 17) = {f5[]};

// ---- the entity table circuitRF checks before it believes this mesh (R-em3d7-3b) ---------
Printf("# circuitRF entity table: group <attribute> <count> <volume tags lost in the fragment>") > "entities.txt";
lost[] = s0[];
lost[] -= allV[];
Printf("group 1 %g %g", #s0[], #lost[]) >> "entities.txt";
lost[] = s1[];
lost[] -= allV[];
Printf("group 2 %g %g", #s1[], #lost[]) >> "entities.txt";
Printf("group 3 %g 0", #c2[]) >> "entities.txt";
Printf("group 4 %g 0", #c3[]) >> "entities.txt";
Printf("group 5 %g 0", #c4[]) >> "entities.txt";
lost[] = s5[];
lost[] -= allV[];
Printf("group 6 %g %g", #s5[], #lost[]) >> "entities.txt";
Printf("group 7 %g 0", #c6[]) >> "entities.txt";
lost[] = s7[];
lost[] -= allV[];
Printf("group 8 %g %g", #s7[], #lost[]) >> "entities.txt";
lost[] = bg[];
lost[] -= allV[];
Printf("group 9 %g %g", #bg[], #lost[]) >> "entities.txt";
Printf("group 10 %g 0", #q0[]) >> "entities.txt";
Printf("group 11 %g 0", #q1[]) >> "entities.txt";
Printf("group 12 %g 0", #f0[]) >> "entities.txt";
Printf("group 13 %g 0", #f1[]) >> "entities.txt";
Printf("group 14 %g 0", #f2[]) >> "entities.txt";
Printf("group 15 %g 0", #f3[]) >> "entities.txt";
Printf("group 16 %g 0", #f4[]) >> "entities.txt";
Printf("group 17 %g 0", #f5[]) >> "entities.txt";
Printf("all_volumes %g", #allV[]) >> "entities.txt";
Printf("classified_volumes %g", #s0[] + #s1[] + #s5[] + #s7[] + #bg[]) >> "entities.txt";
Printf("all_surfaces %g", #allS[]) >> "entities.txt";
Printf("single_sided %g", #single[]) >> "entities.txt";
Printf("unclassified_single_sided %g", #rest[]) >> "entities.txt";

// ---- the initial mesh: Palace's adaptive refinement converges the answer ------------------
// Largest element: 0.1 of the air box's largest side (a static solve has no wavelength);
// 0.5 of the smallest at conductors and sheets; at most 1/4 of each port
// sheet's smaller side at the ports; growing by 1.3.
Mesh.MeshSizeMax = 900;
Mesh.MeshSizeFromPoints = 0;
Mesh.MeshSizeExtendFromBoundary = 0;
Mesh.MeshSizeFromCurvature = 12;
Field[1] = Constant; Field[1].VIn = 900; Field[1].VolumesList = {s0[]};
Field[2] = Constant; Field[2].VIn = 900; Field[2].VolumesList = {s1[]};
Field[3] = Constant; Field[3].VIn = 900; Field[3].VolumesList = {s5[]};
Field[4] = Constant; Field[4].VIn = 900; Field[4].VolumesList = {s7[]};
Field[5] = Constant; Field[5].VIn = 900; Field[5].VolumesList = {bg[]};
Field[6] = Distance; Field[6].SurfacesList = {c2[], c3[], c4[], c6[]}; Field[6].Sampling = 50;
Field[7] = Threshold; Field[7].InField = 6; Field[7].SizeMin = 450; Field[7].SizeMax = 900; Field[7].DistMin = 450; Field[7].DistMax = 1950;
Field[8] = Distance; Field[8].SurfacesList = {q0[], q1[]}; Field[8].Sampling = 50;
Field[9] = Threshold; Field[9].InField = 8; Field[9].SizeMin = 125; Field[9].SizeMax = 900; Field[9].DistMin = 125; Field[9].DistMax = 2708.333333333;
Field[10] = Min; Field[10].FieldsList = {1, 2, 3, 4, 5, 7, 9};
Background Field = 10;
Mesh.ElementOrder = 2;
Mesh.HighOrderOptimize = 2;
Mesh.MshFileVersion = 2.2;
Mesh.Binary = 1;
