using System.Numerics;
using RfCore;

namespace CircuitRF.Engine.Loadpull;

/// <summary>
/// Builds a recommended-terminations .gam file after a loadpull_pursuit run.
/// loadpull_pursuit.md §5.
///
/// Structure:
///   the VSWR1 DISC around MXP sampled VSWR1_res rings × VSWR1_res angles — focused
///   the VSWR1 DISC around MXE sampled the same way — focused
///   the VSWR2 DISC around MXE sampled VSWR2_res rings × VSWR2_res angles,
///       minus any point already inside a focused disc — broad
///   MXP and MXE points themselves
///
/// Non-convergent exclusion: drop any output point within nonconvergentVSWR of a
/// known unscorable termination; warn the caller.
///
/// VSWR circle in Z domain (§5.1 — validated Z form only).
/// </summary>
public static class GamWriter
{
    public sealed record GamBuilderParams(
        Complex MxpZ,
        Complex MxeZ,
        IReadOnlyList<Complex> UnscorableZ,
        double Vswr1           = 1.5,
        int    Vswr1Resolution = 4,
        double Vswr2           = 3.0,
        int    Vswr2Resolution = 4,
        bool   KeepNonconverging    = false,
        double NonconvergentVswr    = 1.05);

    public sealed record GamBuilderResult(
        IReadOnlyList<Complex> Points,
        IReadOnlyList<string>  Warnings);

    // ── Entry point ───────────────────────────────────────────────────────────

    public static GamBuilderResult Build(GamBuilderParams p)
    {
        var warnings = new List<string>();

        // Step 2-4: the focused sampling — the VSWR1 DISC around each optimum.
        var focusedMxp = SampleVswrDisc(p.MxpZ, p.Vswr1, p.Vswr1Resolution);
        var focusedMxe = SampleVswrDisc(p.MxeZ, p.Vswr1, p.Vswr1Resolution);

        // Step 5-7: the broad sampling — the VSWR2 DISC around MXE, minus whatever a focused disc
        // already covers. The exclusion tests the DISC, not a bounding box: a broad point in what
        // used to be a box corner is outside the VSWR1 circle, so the focused sampling never
        // covered it and discarding it left a hole.
        var broadPts = SampleVswrDisc(p.MxeZ, p.Vswr2, p.Vswr2Resolution)
            .Where(z => RfHelpers.VswrFromZ(z, p.MxpZ) > p.Vswr1
                     && RfHelpers.VswrFromZ(z, p.MxeZ) > p.Vswr1)
            .ToList();

        // Step 8: collect focused + broad + optima.
        var all = new List<Complex>();
        all.AddRange(focusedMxp);
        all.AddRange(focusedMxe);
        all.AddRange(broadPts);
        all.Add(p.MxpZ);
        all.Add(p.MxeZ);

        // Deduplicate (by VSWR proximity within a tight tolerance).
        all = Deduplicate(all, vswr: 1.005);

        // Non-convergent exclusion (unless keepNonconvergingPoints).
        if (!p.KeepNonconverging && p.UnscorableZ.Count > 0)
        {
            int before = all.Count;
            all = all.Where(z => !NearUnscorable(z, p.UnscorableZ, p.NonconvergentVswr)).ToList();
            int removed = before - all.Count;
            if (removed > 0)
            {
                string w = $"Removed {removed} grid point(s) within {p.NonconvergentVswr:F2} VSWR " +
                           $"of non-convergent terminations (keepNonconvergingPoints=false).";
                warnings.Add(w);
                Console.Error.WriteLine($"[GamWriter] {w}");
            }
        }

        return new GamBuilderResult(all, warnings);
    }

    // ── Write to file ─────────────────────────────────────────────────────────

    /// <summary>
    /// Writes a recommended-terminations grid. With <paramref name="freqHz"/> set, the block is tagged with
    /// a <c>freq=&lt;f&gt;Hz</c> directive line (round-trippable by GamReader's Layer-C reader). With
    /// <paramref name="append"/> true, the block is appended to an existing multi-frequency file (the
    /// <c>#</c> header is written only when the file is new/empty) — this is how a frequency-swept pursuit
    /// accumulates one block per frequency without the per-point overwrite.
    /// </summary>
    public static void WriteFile(string path, GamBuilderResult result, double z0 = 50.0,
        double? freqHz = null, bool append = false)
    {
        bool needHeader = !append || !File.Exists(path) || new FileInfo(path).Length == 0;
        using var w = new StreamWriter(path, append: append);
        if (needHeader)
        {
            // Header line: GamReader expects the form keyword on a '#'-prefixed header line.
            w.WriteLine($"# impedance Z0={z0} re+j*imag");
            w.WriteLine($"# Generated by circuitRF GamWriter (loadpull_pursuit.md §5)");
        }
        if (result.Warnings.Count > 0)
            foreach (var wn in result.Warnings)
                w.WriteLine($"# WARNING: {wn}");
        // Frequency block delimiter (bare directive — NOT '#', which is a comment token).
        if (freqHz is { } f)
            w.WriteLine($"freq={f.ToString("G10", System.Globalization.CultureInfo.InvariantCulture)}Hz");
        foreach (var z in result.Points)
            w.WriteLine($"{z.Real:G10}{(z.Imaginary >= 0 ? "+" : "")}{z.Imaginary:G10}j");
    }

    // ── Grid sampling ─────────────────────────────────────────────────────────

    /// <summary>
    /// Samples the constant-VSWR DISC around <paramref name="centre"/> — <paramref name="n"/> rings ×
    /// <paramref name="n"/> angles, laid out in the reflection plane referenced to the centre, and
    /// returned as impedances.
    ///
    /// <para><b>Why this is not a box sample (2026-08-23).</b> The broad grid used to be
    /// <c>VSWR2_res × VSWR2_res</c> equally-spaced points across the <i>bounding box</i> of this
    /// circle. A constant-VSWR circle about R spans <c>R/v … R·v</c>, so at <c>VSWR2 = 20</c> about
    /// 95 % of the box's width lies ABOVE the centre and 5 % below it: with a linear lattice, only
    /// ONE of ten columns fell below the centre's resistance, and its rows were spaced so far apart
    /// (the box is as tall as it is wide) that none of them landed near the centre's reactance. The
    /// measured effect on a real run — MXE at 124.8 Ω, <c>VSWR2 = 20</c>, 10 × 10 — was that the
    /// lowest-resistance termination anywhere within VSWR 20 of MXE was <b>40.2 Ω, a VSWR of 3.1</b>,
    /// and it came from the VSWR1 box around MXP rather than from the broad sampling at all. The
    /// low-impedance reach was set by VSWR1; VSWR2 bought nothing but Smith-chart rim (65 of 134
    /// points at |Γ| &gt; 0.95, and 40 of them FURTHER than VSWR2 from MXE, since a box's corners
    /// reach well past the circle they bound — one was at VSWR 2010).</para>
    ///
    /// <para>Sampling the circle instead makes the parameter mean what it says: the outermost ring is
    /// at exactly VSWR2 from the centre in every direction, so the low-impedance extreme
    /// <c>Re/VSWR2 + j·Im</c> is always a grid point. Rings are equally spaced in |Γ|, which is a
    /// gentle geometric progression in VSWR (at VSWR2 = 20, n = 10: 1.2, 1.44, 1.77, 2.2, 2.75, 3.55,
    /// 4.79, 6.99, 11.9, 20) — dense where the contours turn, sparse out at the rim, which is the
    /// density a 2-D interpolator wants. Alternate rings are offset half an angular step so the
    /// points do not line up into radial spokes.</para>
    ///
    /// <para>The centre itself is not emitted (rings start at k = 1); the caller adds MXP and MXE.</para>
    /// </summary>
    private static List<Complex> SampleVswrDisc(Complex centre, double vswr, int n)
    {
        var pts = new List<Complex>(n * n);
        if (n < 1 || vswr <= 1.0) return pts;

        double gMax = (vswr - 1.0) / (vswr + 1.0);

        for (int k = 1; k <= n; k++)
        {
            double mag = gMax * k / n;
            // Offset alternate rings by half a step, counting inward from the OUTER ring so the
            // outermost one always keeps its cardinal points — the VSWR2 extremes are the whole
            // reason the setting exists, and staggering them away would be a silent loss.
            double offset = ((n - k) % 2) * Math.PI / n;

            for (int j = 0; j < n; j++)
            {
                double theta = 2.0 * Math.PI * j / n + offset;
                var    gamma = Complex.FromPolarCoordinates(mag, theta);
                var    z     = ZFromGammaAbout(centre, gamma);

                if (z.Real > 1e-6)   // require positive real part (physical impedance)
                    pts.Add(z);
            }
        }
        return pts;
    }

    /// <summary>
    /// Inverse of <see cref="RfHelpers.VswrFromZ"/>'s reflection coefficient: given
    /// <c>gamma = (Z − centre)/(Z + conj(centre))</c>, returns Z. At <c>gamma = 0</c> this is the
    /// centre, and at <c>gamma = −|g|</c> (real, negative) it is <c>Re(centre)/vswr + j·Im(centre)</c>
    /// — the low-impedance extreme of the constant-VSWR circle.
    /// </summary>
    private static Complex ZFromGammaAbout(Complex centre, Complex gamma)
        => (centre + gamma * Complex.Conjugate(centre)) / (Complex.One - gamma);

    // ── Deduplication ─────────────────────────────────────────────────────────

    private static List<Complex> Deduplicate(List<Complex> pts, double vswr)
    {
        var result = new List<Complex>(pts.Count);
        foreach (var z in pts)
        {
            bool dup = result.Any(r => RfHelpers.VswrFromZ(z, r) <= vswr);
            if (!dup) result.Add(z);
        }
        return result;
    }

    // ── Non-convergent proximity check ────────────────────────────────────────

    private static bool NearUnscorable(Complex z, IReadOnlyList<Complex> unscorable, double vswr)
        => unscorable.Any(u => RfHelpers.VswrFromZ(z, u) <= vswr);
}
