using System.Numerics;
using RfCore;

namespace CircuitRF.Engine.Loadpull;

/// <summary>
/// Builds a recommended-terminations .gam file after a loadpull_pursuit run.
/// loadpull_pursuit.md §5.
///
/// Structure:
///   box1 (VSWR1 around MXP) sampled VSWR1_res × VSWR1_res — focused
///   box2 (VSWR1 around MXE) sampled VSWR1_res × VSWR1_res — focused
///   box4 (VSWR2 around MXE, union with box1+box2) sampled VSWR2_res × VSWR2_res
///       minus any point inside box1 or box2 — broad
///   MXP and MXE points themselves
///
/// Non-convergent exclusion: drop any output point within nonconvergentVSWR of a
/// known unscorable termination; warn the caller.
///
/// VSWR circle in Z domain (§5.1 — validated Z form only).
/// </summary>
public static class GamWriter
{
    public sealed record GamBuilderParams(
        Complex MxpZ,
        Complex MxeZ,
        IReadOnlyList<Complex> UnscorableZ,
        double Vswr1           = 1.5,
        int    Vswr1Resolution = 4,
        double Vswr2           = 3.0,
        int    Vswr2Resolution = 4,
        bool   KeepNonconverging    = false,
        double NonconvergentVswr    = 1.05);

    public sealed record GamBuilderResult(
        IReadOnlyList<Complex> Points,
        IReadOnlyList<string>  Warnings);

    // ── Entry point ───────────────────────────────────────────────────────────

    public static GamBuilderResult Build(GamBuilderParams p)
    {
        var warnings = new List<string>();

        // Step 2-3: VSWR1 boxes around MXP and MXE.
        var (xmin1, xmax1, ymin1, ymax1) = VswrCircleBox(p.MxpZ, p.Vswr1);
        var (xmin2, xmax2, ymin2, ymax2) = VswrCircleBox(p.MxeZ, p.Vswr1);

        var box1Pts = SampleBox(xmin1, xmax1, ymin1, ymax1, p.Vswr1Resolution);
        var box2Pts = SampleBox(xmin2, xmax2, ymin2, ymax2, p.Vswr1Resolution);

        // Step 5-7: VSWR2 box around MXE → box3 → combined box4.
        var (xmin3, xmax3, ymin3, ymax3) = VswrCircleBox(p.MxeZ, p.Vswr2);
        double xmin4 = Math.Min(Math.Min(xmin1, xmin2), xmin3);
        double xmax4 = Math.Max(Math.Max(xmax1, xmax2), xmax3);
        double ymin4 = Math.Min(Math.Min(ymin1, ymin2), ymin3);
        double ymax4 = Math.Max(Math.Max(ymax1, ymax2), ymax3);

        var box4Pts = SampleBox(xmin4, xmax4, ymin4, ymax4, p.Vswr2Resolution)
            .Where(z => !InsideBox(z, xmin1, xmax1, ymin1, ymax1)
                     && !InsideBox(z, xmin2, xmax2, ymin2, ymax2))
            .ToList();

        // Step 8: collect focused + broad + optima.
        var all = new List<Complex>();
        all.AddRange(box1Pts);
        all.AddRange(box2Pts);
        all.AddRange(box4Pts);
        all.Add(p.MxpZ);
        all.Add(p.MxeZ);

        // Deduplicate (by VSWR proximity within a tight tolerance).
        all = Deduplicate(all, vswr: 1.005);

        // Non-convergent exclusion (unless keepNonconvergingPoints).
        if (!p.KeepNonconverging && p.UnscorableZ.Count > 0)
        {
            int before = all.Count;
            all = all.Where(z => !NearUnscorable(z, p.UnscorableZ, p.NonconvergentVswr)).ToList();
            int removed = before - all.Count;
            if (removed > 0)
            {
                string w = $"Removed {removed} grid point(s) within {p.NonconvergentVswr:F2} VSWR " +
                           $"of non-convergent terminations (keepNonconvergingPoints=false).";
                warnings.Add(w);
                Console.Error.WriteLine($"[GamWriter] {w}");
            }
        }

        return new GamBuilderResult(all, warnings);
    }

    // ── Write to file ─────────────────────────────────────────────────────────

    public static void WriteFile(string path, GamBuilderResult result, double z0 = 50.0)
    {
        using var w = new StreamWriter(path);
        // Header line: GamReader expects form keyword on a '#'-prefixed header line.
        w.WriteLine($"# impedance Z0={z0} re+j*imag");
        w.WriteLine($"# Generated by circuitRF GamWriter (loadpull_pursuit.md §5)  Points={result.Points.Count}");
        if (result.Warnings.Count > 0)
            foreach (var wn in result.Warnings)
                w.WriteLine($"# WARNING: {wn}");
        foreach (var z in result.Points)
            w.WriteLine($"{z.Real:G10}{(z.Imaginary >= 0 ? "+" : "")}{z.Imaginary:G10}j");
    }

    // ── VSWR-circle box (§5.1, Z domain) ─────────────────────────────────────

    /// <summary>
    /// Returns the bounding box of the constant-VSWR circle around <paramref name="z"/>
    /// in the Z plane.
    ///
    /// §5.1 formula:
    ///   gamma   = (vswr − 1)/(vswr + 1)
    ///   z_center = z.Real·(1+gamma²)/(1-gamma²) + j·z.Imag
    ///   z_radius = z.Real·2·gamma/(1−gamma²)
    ///   box: [z_center.Real ± z_radius, z_center.Imag ± z_radius]
    ///
    /// The circle is symmetric about the real axis only for z.Imag = 0.
    /// The Im bounds are [z.Imag - z_radius, z.Imag + z_radius] by the formula.
    /// </summary>
    private static (double Xmin, double Xmax, double Ymin, double Ymax)
        VswrCircleBox(Complex z, double vswr)
    {
        double r     = Math.Max(z.Real, 1e-3);   // guard against near-zero real part
        double gamma = (vswr - 1.0) / (vswr + 1.0);
        double g2    = gamma * gamma;
        double denom = 1.0 - g2;
        double zCR   = r * (1.0 + g2) / denom;   // center real
        double zCI   = z.Imaginary;               // center imag (same as z.Imag per §5.1)
        double zRad  = r * 2.0 * gamma / denom;   // radius

        return (zCR - zRad, zCR + zRad, zCI - zRad, zCI + zRad);
    }

    // ── Grid sampling ─────────────────────────────────────────────────────────

    private static List<Complex> SampleBox(
        double xmin, double xmax, double ymin, double ymax, int n)
    {
        var pts = new List<Complex>(n * n);
        for (int ix = 0; ix < n; ix++)
        for (int iy = 0; iy < n; iy++)
        {
            double x = n > 1 ? xmin + ix * (xmax - xmin) / (n - 1) : (xmin + xmax) / 2;
            double y = n > 1 ? ymin + iy * (ymax - ymin) / (n - 1) : (ymin + ymax) / 2;
            if (x > 1e-6)   // require positive real part (physical impedance)
                pts.Add(new Complex(x, y));
        }
        return pts;
    }

    private static bool InsideBox(Complex z,
        double xmin, double xmax, double ymin, double ymax)
        => z.Real >= xmin && z.Real <= xmax
        && z.Imaginary >= ymin && z.Imaginary <= ymax;

    // ── Deduplication ─────────────────────────────────────────────────────────

    private static List<Complex> Deduplicate(List<Complex> pts, double vswr)
    {
        var result = new List<Complex>(pts.Count);
        foreach (var z in pts)
        {
            bool dup = result.Any(r => RfHelpers.VswrFromZ(z, r) <= vswr);
            if (!dup) result.Add(z);
        }
        return result;
    }

    // ── Non-convergent proximity check ────────────────────────────────────────

    private static bool NearUnscorable(Complex z, IReadOnlyList<Complex> unscorable, double vswr)
        => unscorable.Any(u => RfHelpers.VswrFromZ(z, u) <= vswr);
}
